const navItems = [
  ["home","Home","⌂"],["positioning","Project Positioning","◎"],["world","Story World","◈"],["characters","Character Profiles","♙"],["relations","Character Relationships","⇄"],["season","Season 1: 30 Episodes","30"],["ideas","Story Topic Library","✦"],["episode","Episode Sheet","▤"],["scripts","Script Center","✎"],["production","Production Progress","▦"],["schedule","Shoot Schedule","◷"],["team","Team Members","♟"],["supporting","Supporting Characters","♧"],["singapore","Singapore Reference Library","SG"],["analytics","Publishing & Analytics","↗"],["brand","Brand Guidelines","◆"],["public","Internal & Public Sites","◉"]
];

const episodes = [
[1,"Meeting the Landlord","Move-in Arc"],[2,"Everything Was “Okay” During the Viewing","Move-in Arc"],[3,"The First Day Moving In","Move-in Arc"],[4,"Who Gets the Largest Room","Move-in Arc"],[5,"The Landlord’s Twenty Rules","Move-in Arc"],[6,"Will We Ever Get the Deposit Back","Move-in Arc"],
[7,"How Long Can We Run the Air-Conditioner","Living Habits Arc"],[8,"Doing Laundry at Midnight","Living Habits Arc"],[9,"Who Left the Lights On Again","Living Habits Arc"],[10,"Whose Food Is in the Fridge","Living Habits Arc"],[11,"Hotpot at Home","Living Habits Arc"],[12,"Can We Bring Durian Home","Living Habits Arc"],[13,"Who Cleans the Bathroom","Living Habits Arc"],[14,"Do We Need Permission to Bring Friends Home","Living Habits Arc"],[15,"Who Owns the Living Room","Living Habits Arc"],
[16,"Reserving a Seat with Tissue","Singapore Culture Arc"],[17,"How to Order at a Hawker Centre","Singapore Culture Arc"],[18,"Why Does Everyone Say “Can”","Singapore Culture Arc"],[19,"Missing the Stop on the First Bus Ride","Singapore Culture Arc"],[20,"What You Cannot Do on the MRT","Singapore Culture Arc"],[21,"How to Dispose of Rubbish Properly","Singapore Culture Arc"],[22,"Why Singapore Fines Everything","Singapore Culture Arc"],[23,"Why Nobody Carries an Umbrella","Singapore Culture Arc"],
[24,"Joseph Wants to Move Out","Relationship Arc"],[25,"Angeline Wants to Turn the Living Room into an Office","Relationship Arc"],[26,"James Suddenly Raises the Rent","Relationship Arc"],[27,"Their First Festival Together","Relationship Arc"],[28,"The Landlord Is Sick","Relationship Arc"],[29,"A New Tenant Comes for a Viewing","Relationship Arc"],[30,"Who Is Really in Charge","Relationship Arc"]
];

const topicGroups = {
"Shared Living":["Rent","Deposit","Utilities","Air-Conditioning","Laundry","Cleaning the Bathroom","Cleaning","Noise","Bringing Friends Home","Fridge","Cooking","Deliveries","Pets","Daily Routine","Shared Areas"],
"Singapore Culture":["Chope","Singlish","Hawker Centre","Queueing","MC","HDB","Condo","MRT","Bus","ERP","COE","CPF","Singpass","National Day","Hawker Culture"],
"Newcomers from China":["Finding a Home","SIM Card","Opening a Bank Account","Seeing a Doctor","Finding a Job","Applying for a Pass","Transport","Shopping","Food","Schools","Tenancy Agreement","Agent","Weather","English Accent"],
"The Trio’s Relationships":["Arguments","Silent Treatment","Birthdays","Breakups","Job Loss","Illness","Borrowing Money","Misunderstandings","Secrets","Helping Each Other","New Friends","Family Visits"],
"Festivals & Trends":["Chinese New Year","National Day","Mid-Autumn Festival","Christmas","Hari Raya Puasa","Deepavali","Singles’ Day","Gaokao","Singapore General Election","Concerts","New Policies"]
};

const defaultIdeas = [
 {title:"The Air-Conditioner Remote Is Missing",category:"Shared Living",summary:"James limits air-conditioner use, but the remote disappears. It is eventually found hidden in the fridge by Joseph.",lead:"All Three",scene:"Living Room",status:"Idea Box"},
 {title:"Tissue Is Not Rubbish",category:"Singapore Culture",summary:"Joseph throws away tissue left on a table. Angeline returns to find that someone else has taken the reserved seat.",lead:"Joseph",scene:"Hawker Centre",status:"For Discussion"}
];

let state = {
  page: location.hash.replace('#','') || 'home',
  ideas: SharedIdeas.getLocal(defaultIdeas)
};

const nav = document.getElementById('nav');
const content = document.getElementById('content');
const pageTitle = document.getElementById('pageTitle');
const sidebar = document.getElementById('sidebar');

function badge(text, cls=''){ return `<span class="badge ${cls}">${text}</span>`; }
function card(title, body, extra=''){ return `<article class="card ${extra}"><h4>${title}</h4>${body}</article>`; }
function section(title, subtitle, body){ return `<section class="section"><div class="section-header"><div><h3>${title}</h3><p>${subtitle||''}</p></div></div>${body}</section>`; }

function renderNav(){
  nav.innerHTML = navItems.map(([id,label,icon])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');
  nav.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{ location.hash=btn.dataset.page; sidebar.classList.remove('open'); });
}

const pages = {
home(){
 return `<div class="hero"><p class="eyebrow">Season 1 · Internal HQ</p><h3>Three people under one roof use comedy to portray the real cultural shocks newcomers from China face in Singapore.</h3><p>James is the landlord, while Angeline and Joseph are tenants. Set mainly in James’s living room, the project builds a long-running short-drama universe through consistent character relationships, domestic conflict, and authentic Singapore culture.</p><div class="hero-actions"><button class="primary-btn" onclick="location.hash='season'">View Season 1</button><button class="ghost-btn" onclick="location.hash='characters'">View Characters</button><button class="ghost-btn" onclick="openIdeaModal()">Add Story Idea</button></div></div>
 ${section('Current Production Status','Season 1: The New Tenants Arrive',`<div class="grid grid-4">
 ${statCard('Planned Episodes','30','0%')}${statCard('Topics Confirmed','30','100%')}${statCard('Scripts Completed','0','0%')}${statCard('Filmed','0','0%')}
 </div>`)}
 ${section('Project Essentials','Four points every team member must understand first',`<div class="grid grid-2">${card('Project Overview','<p>James is the landlord, and Angeline and Joseph are tenants. Three very different people live under one roof in Singapore, using everyday conflicts to reveal local life, culture, and social rules.</p>')}${card('Core Positioning','<div class="callout">Use light comedy to help Chinese audiences understand the real Singapore.</div>')}${card('Emotional Core','<p>They appear to annoy one another, but have effectively become a family. Comedy comes from conflict; long-term engagement comes from deepening relationships.</p>')}${card('Expansion','<p>The living room is the main early-stage set. Later, the world can expand to the kitchen, entrance, downstairs area, hawker centres, supermarkets, MRT stations, bus stops, and recurring supporting characters.</p>')}</div>`)}
 ${section('Quick Access','Open daily creative and production work',`<div class="grid grid-3">${quick('Character Profiles','Keep character traits, functions, and performance boundaries consistent','characters')}${quick('Story Topic Library','Store long-term topics and new ideas','ideas')}${quick('Production Progress','Track topics, scripts, filming, and post-production','production')}</div>`)}`;
},
positioning(){ return introPage('Project Positioning','This is not just a comedy account. It is an expandable short-drama IP.',[
 ['Project Name','Working title: Under One Roof. The title may change, but the story world and character relationships can be established now.'],
 ['One-line Introduction','Two tenants move into a Singapore landlord’s home and gradually learn about Singapore through chaotic shared living.'],
 ['Target Audience','Chinese audiences interested in Singapore; people planning to move to Singapore; Chinese residents already in Singapore; local Singaporean Chinese; and viewers who enjoy light lifestyle comedy.'],
 ['Content Features','Authentic Singapore culture, cultural differences between Chinese newcomers and Singaporeans, shared living, light comedy, useful information, stable character relationships, and a continuing story world.']
], rules()); },
world(){ return introPage('Story World','The living room is only the stage; the character relationships are the real core.',[
 ['Story Background','James owns or rents a home in Singapore and lets rooms to Angeline and Joseph. Their different habits, backgrounds, and personalities create frequent conflict. James knows Singapore’s rules, while Angeline and Joseph create problems by misunderstanding or challenging them.'],
 ['Recurring Locations','Living room, sofa, dining table, kitchen, bedroom doors, front door, corridor, downstairs area, lift, nearby hawker centre, supermarket, and bus stop. Early episodes focus on James’s living room, with outdoor locations added later.'],
 ['Story-world Rules','James is the landlord; Angeline and Joseph are long-term tenants; the three are also friends; every character can have a job and independent life; the home is the main setting but not the only one; supporting characters can appear in person, by phone, video call, or in outdoor scenes.'],
 ['Long-term Expansion','Future stories may cover jobs, entrepreneurship, romance, family, education, festivals, policies, and neighbourhood life while preserving the trio’s core relationship.']
]); },
characters(){ return `${section('Core Characters','Characterisation must remain stable, while every character needs growth and weaknesses',`<div class="grid grid-3">${character('James','Landlord','J','avatar-james',['Rule-focused','Rational','Calm','Slightly Stubborn','Acts annoyed but helps the tenants'],'Represents Singapore’s rules, explains local culture, stops ridiculous behaviour, and cleans up the final mess.',['Must not lecture like a teacher in every episode','Must not lose his temper in every episode','Must not portray Singaporeans as cold','Needs his own weaknesses and comic moments'])}${character('Angeline','Tenant','A','avatar-angeline',['Quick-thinking','Strong-minded','Turns everything into an opportunity','Likes to control situations','Hates losing out'],'Drives the plot, creates conflict, challenges James’s rules, and turns ordinary events into businesses or major plans.',['Must not be only calculating and forceful','Needs to lose sometimes','Needs a warm and authentic side','Must not always be right'])}${character('Joseph','Tenant','J','avatar-joseph',['Curious','Naive','Trusting','Unusual Ideas','Sometimes Overconfident'],'Represents a newcomer to Singapore, asks the audience’s questions, misunderstands culture, and creates unexpected comedy.',['Must not always appear foolish','Needs moments of intelligence','Should occasionally solve the problem','Must not be bullied in every episode'])}</div>`)}
 ${section('Typical Reactions & Lines','Use these to maintain character consistency while writing',`<div class="grid grid-3">${card('James','<ul class="list"><li>Emphasises rules and fines</li><li>“This is Singapore.”</li><li>Silently stares at the two tenants</li><li>Quietly helps solve the problem</li></ul>')}${card('Angeline','<ul class="list"><li>“Why not?”</li><li>“Wouldn’t this be more efficient?”</li><li>“Can this make money?”</li><li>Acts first and informs others later</li></ul>')}${card('Joseph','<ul class="list"><li>“Really?”</li><li>“That is not how it works in China.”</li><li>“Why?”</li><li>Acts after understanding only half the explanation</li></ul>')}</div>`)}`; },
relations(){ return `${section('Character Relationships','Recurring relationships determine how conflict works in each episode',`<div class="grid grid-2">${card('James × Angeline','<p><strong>Rule-maker vs Rule-challenger</strong></p><p>They argue frequently but respect each other’s abilities.</p>')}${card('James × Joseph','<p><strong>Landlord vs Accident-prone Tenant</strong></p><p>James often has to clean up Joseph’s mess.</p>')}${card('Angeline × Joseph','<p><strong>Leader vs Follower</strong></p><p>Angeline often leads Joseph into a plan, and both end up in trouble.</p>')}${card('The Trio','<div class="callout"><strong>They appear to annoy one another but have effectively become a family.</strong></div>')}</div>`)}
 ${section('Relationship Development Principles','Season 1 needs gradual relationship growth, not only standalone jokes',`<div class="timeline"><div class="timeline-item"><h4>Strangers Testing Boundaries</h4><p>At first, everyone protects themselves through rules and small schemes.</p></div><div class="timeline-item"><h4>Conflict and Dependence</h4><p>Their habits clash, but they begin helping one another.</p></div><div class="timeline-item"><h4>Becoming a Real Family</h4><p>Illness, moving out, and a new tenant make them realise how important they are to one another.</p></div></div>`)}`; },
season(){ const phases=['Move-in Arc','Living Habits Arc','Singapore Culture Arc','Relationship Arc']; return `${section('Season 1: The New Tenants Arrive','Thirty episodes form Season 1, focusing on moving in, adapting, and building relationships',`<div class="tabs">${phases.map((p,i)=>`<button class="tab-btn ${i===0?'active':''}" onclick="filterEpisodes('${p}',this)">${p}</button>`).join('')}<button class="tab-btn" onclick="filterEpisodes('All',this)">All</button></div><div id="episodeGrid" class="episode-grid">${renderEpisodes('Move-in Arc')}</div>`)}`; },
ideas(){ return `${section('Story Topic Library','Long-term topic categories beyond Season 1',`<div class="grid grid-3">${Object.entries(topicGroups).map(([k,v])=>card(k,`<div class="filters">${v.map(x=>badge(x)).join('')}</div>`)).join('')}</div>`)}${section('Team Idea Box','Entries use one shared dataset. After Cloudflare D1 is connected, all three members can see updates across devices.',`<div id="ideasTable">${ideasTable()}</div>`)}`; },
episode(){ return `${section('Episode SheetTemplate','Every episode should use the same fields',`<div class="table-wrap"><table><thead><tr><th>Field</th><th>Example</th></tr></thead><tbody>${[['Episode','EP01'],['Title','New TenantArrive'],['Arc','Move-in Arc'],['Core Cultural Point','SingaporeHousing & Tenancy'],['Main Cast','James、Angeline、Joseph'],['Supporting Cast','None'],['Scene','Living Room'],['Duration','2–4 minutes'],['Story Status','Idea / Outline / Script / Filmed / Edited / Published'],['Writer','Name'],['Director','Name'],['Shoot Date','Date'],['Publication Date','Date'],['Platforms','Douyin / Xiaohongshu / WeChat Channels / YouTube'],['Props','Contract, Suitcases, Keys'],['Notes','Verify tenancy information']].map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td></tr>`).join('')}</tbody></table></div>`)}${section('Episode Structure','Every final script must include',`<div class="grid grid-3">${['Opening Hook: What happens in the first three seconds','Conflict: Who wants what, and who stops them','Twist: What unexpected event happens at the end','Cultural Point: What the audience genuinely learns','Full Dialogue: Organised by character','Shot List: Wide shots, close-ups, and reaction shots','Publishing Copy: Titles and descriptions for each platform'].map((x,i)=>card(`0${i+1}`,`<p>${x}</p>`)).join('')}</div>`)}`; },
scripts(){ return `${section('Script Center','Maintain one authoritative version to prevent filming the wrong draft',kanban([['Idea Box',['The Air-Conditioner Remote Is Missing','Why Singaporeans Queue Everywhere']],['For Discussion',['Tissue Is Not Rubbish','Who Gets the Largest Room']],['Writing',['Meeting the Landlord']],['Final',[]]]))}${section('Version Control Rules','Every script must be traceable',`<div class="grid grid-3">${card('Required Fields','<ul class="list"><li>Version Number</li><li>Last Editor</li><li>Revision Date</li><li>Revision Notes</li><li>Approved By</li></ul>')}${card('Status Flow','<p>Idea Box → For Discussion → Approved → Writing → Revision → Final → Filmed → Published</p>')}${card('Core Rule','<p>Only the Final version may be used on set. Any improvised wording must be added to the latest script after filming.</p>')}</div>`)}`; },
production(){ return `${section('Production Progress','Complete production board from topic selection to publication',kanban([['Pre-production',['Topic Selection','Outline','Script','Scene','Cast','Props','Wardrobe']],['Production',['To Film','Scheduled','Filming','Reshoot Required','Completed']],['Post-production',['Rough Cut','Final Cut','Subtitles','Sound Effects','Thumbnail','Review']],['Publishing',['Ready to Publish','Published','Performance Review']]]))}`; },
schedule(){ return `${section('Shoot Schedule','Film 4–8 episodes per session instead of scheduling one episode at a time',`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Time</th><th>Location</th><th>Episodes</th><th>Attendees</th><th>Wardrobe & Props</th><th>Status</th></tr></thead><tbody><tr><td>TBC</td><td>TBC</td><td>James’s Living Room</td><td>EP01–EP04</td><td>James / Angeline / Joseph</td><td>Keys, Suitcases, Tenancy Agreement</td><td>${badge('To Schedule','yellow')}</td></tr></tbody></table></div>`)}${section('Required Shoot Records','Prevent omissions',`<div class="grid grid-3">${['Date','Time','Location','Episodes','Cast Present','Crew','Required Wardrobe','Required Props','Estimated Completion Time','Outdoor Location Required','Reshoot Required'].map(x=>card(x,'<p>Updated by the producer or on-set lead.</p>')).join('')}</div>`)}`; },
team(){ return `${section('Core Team','Current permanent members',`<div class="grid grid-3">${teamCard('James','Landlord / Actor / Location Host','Plays the landlord, coordinates the location, and checks Singapore cultural accuracy')}${teamCard('Angeline','Tenant / Actor / Project Lead','Leads project direction, story development, market positioning, and the Chinese audience perspective')}${teamCard('Joseph','Tenant / Actor','Represents the audience, delivers comic reactions, and drives cultural-misunderstanding stories')}</div>`)}${section('Future Team Roles','Create member profiles and permissions as the team expands',`<div class="grid grid-4">${['Cast','Writer','Director','Camera','Sound','Editor','Subtitles','Operations','Business','Props','Wardrobe','Producer'].map(x=>card(x,'<p>May be a permanent or project-based role.</p>')).join('')}</div>`)}${section('Member Profile Fields','Standardised records',`<div class="callout">Name, photo, role, contact details, join date, permanent-member status, responsibilities, viewing permission, editing permission, and administrator permission.</div>`)}`; },
supporting(){ return `${section('Supporting & Guest Characters','Supporting characters should recur and gradually build a complete universe',`<div class="grid grid-3">${['Next-door Neighbour','James’s Mother','Property Agent','Delivery Rider','Cleaner','Angeline’s Client','Joseph’s Friend','New Tenant','ICA Officer','Boss','Colleague','Food Delivery Rider','Hawker Stall Owner'].map(x=>card(x,'<p>Record characterisation, relationship to the main cast, first appearance, repeatable storylines, and actor details.</p>')).join('')}</div>`)}`; },
singapore(){ const cats=['Housing & Tenancy','Transport','Food','Work','Education','Laws & Fines','Festivals','Language','Social Customs','Government Services','Healthcare','Banking','Mobile & Internet']; return `${section('Singapore Reference Library','All cultural and policy information must be accurate and sourced',`<div class="grid grid-4">${cats.map(x=>card(x,'<p>Store the topic explanation, official source, last verification date, related episodes, and whether it has been used.</p>')).join('')}</div>`)}${section('Reference Entry Standard','Prevent inaccurate information from appearing in the series',`<div class="table-wrap"><table><thead><tr><th>Field</th><th>Requirement</th></tr></thead><tbody><tr><td>Topic</td><td>Define one filmable question</td></tr><tr><td>Plain-language Explanation</td><td>Explain it in audience-friendly language</td></tr><tr><td>Official Source</td><td>Prioritise government agencies, statutory boards, or official operators</td></tr><tr><td>Last Verified</td><td>Policies and fees must be kept current</td></tr><tr><td>Related Episodes</td><td>Identify where the information can be used</td></tr><tr><td>Used</td><td>Prevent duplication or support sequels</td></tr></tbody></table></div>`)}`; },
analytics(){ return `${section('Publishing & Analytics','Record every release consistently to identify what genuinely works',`<div class="grid grid-4">${['Views','Likes','Comments','Shares','Saves','New Followers','Completion Rate','Top Comment'].map((x,i)=>statCard(x,'—','0%')).join('')}</div>`)}${section('Review Questions','Data should determine what to film next, not merely report past results',`<div class="grid grid-2">${card('Content Performance','<ul class="list"><li>Which Singapore cultural topics perform best?</li><li>Which conflicts are funniest?</li><li>Which topics deserve sequels?</li></ul>')}${card('Character Performance','<ul class="list"><li>Which character is most popular?</li><li>Which relationship does the audience prefer?</li><li>Which platform performs best?</li></ul>')}</div>`)}`; },
brand(){ return `${section('Brand & Visual Guidelines','Maintain consistency as the team grows',`<div class="grid grid-3">${['Logo','Chinese Name','English Name','Typography','Brand Colours','Opening','Closing','Subtitle Style','Thumbnail Template','Character Name Treatment','Music Guidelines','Logo Rules'].map(x=>card(x,'<p>Upload or complete the final standard after brand approval.</p>')).join('')}</div>`)}${section('Current Interim Guidelines','Visual direction used for Version 1',`<div class="grid grid-3">${card('Primary Colours','<p>Deep navy represents a stable story world; warm orange represents domestic conflict and comic rhythm.</p>')}${card('Visual Character','<p>Natural, modern, and clear, without a cheap or exaggerated variety-show look.</p>')}${card('Subtitle Principle','<p>For Chinese releases, use Chinese subtitles while retaining key Singlish or English terms with natural explanations.</p>')}</div>`)}`; },
public(){ return `${section('Site Structure','Build the internal site first and open a public site later',`<div class="grid grid-2">${card('Internal Site','<ul class="list"><li>Script</li><li>Shoot Schedule</li><li>Contact Details</li><li>Unreleased Content</li><li>Production Budget</li><li>Internal Discussions</li><li>Performance Data</li></ul>')}${card('Public Site','<ul class="list"><li>Project Introduction</li><li>Character Introduction</li><li>Published Episodes</li><li>Behind the Scenes</li><li>Collaboration</li><li>Casting</li><li>Brand Partnerships</li><li>Contact Details</li></ul>')}</div>`)}${section('Version 1 Completion Standard','Any new member must understand the following within 30 minutes',`<div class="callout">What the project is, whom they play or what they are responsible for, current progress, and the next action.</div>`)}`; }
};

function statCard(label,num,percent){ return `<article class="card"><div class="stat"><div><div class="stat-label">${label}</div><div class="stat-number">${num}</div></div>${badge(percent)}</div><div class="progress"><span style="width:${percent}"></span></div></article>`; }
function quick(title,desc,page){ return `<article class="card"><h4>${title}</h4><p>${desc}</p><button class="ghost-btn" onclick="location.hash='${page}'">Open</button></article>`; }
function introPage(title,subtitle,items,extra=''){ return `${section(title,subtitle,`<div class="grid grid-2">${items.map(x=>card(x[0],`<p>${x[1]}</p>`)).join('')}</div>`)}${extra}`; }
function rules(){ const r=['Every episode needs a story, not just information','Every episode needs conflict; the trio cannot simply talk throughout','Each episode covers one core issue','Singapore information must be accurate','Do not demean any country or group','Comedy should come from character, not crude clowning','Commercial integration must not damage the story']; return section('ContentPrinciple','Mandatory creative rules',`<div class="grid grid-3">${r.map((x,i)=>card(`Principle ${i+1}`,`<p>${x}</p>`)).join('')}</div>`); }
function character(name,role,letter,avatar,traits,func,limits){ return `<article class="card character-card"><div class="character-avatar ${avatar}">${letter}</div><span class="badge">${role}</span><h4 style="font-size:22px;margin-top:10px">${name}</h4><p><strong>Core Traits</strong></p><div class="filters">${traits.map(x=>badge(x)).join('')}</div><p><strong>Story Function</strong></p><p>${func}</p><p><strong>Performance Boundaries</strong></p><ul class="list">${limits.map(x=>`<li>${x}</li>`).join('')}</ul></article>`; }
function renderEpisodes(filter){ return episodes.filter(e=>filter==='All'||e[2]===filter).map(e=>`<article class="episode"><div class="episode-num">EP${String(e[0]).padStart(2,'0')}</div><h4>${e[1]}</h4><p>${e[2]}</p></article>`).join(''); }
window.filterEpisodes=(filter,btn)=>{ document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); document.getElementById('episodeGrid').innerHTML=renderEpisodes(filter); };
function ideasTable(){ if(!state.ideas.length) return '<div class="empty">No ideas yet</div>'; return `<div class="table-wrap"><table><thead><tr><th>Title</th><th>Category</th><th>One-line Story</th><th>Character</th><th>Scene</th><th>Status</th></tr></thead><tbody>${state.ideas.map(i=>`<tr><td><strong>${i.title}</strong></td><td>${i.category}</td><td>${i.summary}</td><td>${i.lead}</td><td>${i.scene}</td><td>${badge(SharedIdeas.statusLabel(i.statusCode || i.status, 'en'), (i.statusCode || i.status)==='discussion' || i.status==='For Discussion' ? 'yellow' : '')}</td></tr>`).join('')}</tbody></table></div>`; }
function kanban(cols){ return `<div class="kanban">${cols.map(([name,items])=>`<div class="kanban-col"><h4>${name}<span>${items.length}</span></h4>${items.map(i=>`<div class="kanban-item"><strong>${i}</strong><br><small>Awaiting owner update</small></div>`).join('')}</div>`).join('')}</div>`; }
function teamCard(name,title,desc){ return `<article class="card"><div class="character-avatar ${name==='James'?'avatar-james':name==='Angeline'?'avatar-angeline':'avatar-joseph'}">${name[0]}</div><h4>${name}</h4><span class="badge">${title}</span><p>${desc}</p></article>`; }

function render(){ if(!pages[state.page]) state.page='home'; renderNav(); pageTitle.textContent=navItems.find(x=>x[0]===state.page)?.[1]||'Home'; content.innerHTML=pages[state.page](); }
window.addEventListener('hashchange',()=>{ state.page=location.hash.replace('#','')||'home'; render(); window.scrollTo(0,0); });

document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');
const modal=document.getElementById('ideaModal');
window.openIdeaModal=()=>{ modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); };
document.getElementById('addIdeaBtn').onclick=openIdeaModal;
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>{ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); });
document.getElementById('ideaForm').onsubmit=async(e)=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(e.target)); const saved=await SharedIdeas.add({...d,statusCode:'idea'}); state.ideas.unshift(saved); e.target.reset(); modal.classList.remove('open'); if(state.page==='ideas') render(); };
document.getElementById('resetBtn').onclick=async()=>{ await SharedIdeas.reset(); state.ideas=JSON.parse(JSON.stringify(defaultIdeas)); SharedIdeas.setLocal(state.ideas); render(); };
SharedIdeas.load(defaultIdeas).then(ideas=>{ state.ideas=ideas; render(); });
