const navGroups = [
  {id:'home', label:'Home Workspace', icon:'⌂', page:'home'},
  {id:'project', label:'Project Setup', icon:'◎', children:[['positioning','Project Positioning'],['world','Story World'],['brand','Brand Guidelines'],['public','Internal & Public Sites']]},
  {id:'characters-assets', label:'Characters & Assets', icon:'♙', children:[['characters','Character Profiles'],['relations','Character Relationships'],['supporting','Supporting Characters']]},
  {id:'episode-management', label:'Episode Management', icon:'▤', children:[['season','All Episodes'],['special','Specials'],['scripts','Script Center'],['production','Production Progress']]},
  {id:'shooting', label:'Shoot Center', icon:'◷', children:[['availability-common','Team Availability'],['schedule','Shoot Schedule & Call Sheets']]},
  {id:'resources', label:'Creative Library', icon:'✦', children:[['ideas','Story Topic Library'],['singapore','Singapore Reference Library']]},
  {id:'team-group', label:'Team Members', icon:'♟', page:'team'},
  {id:'publishing', label:'Publishing & Review', icon:'↗', page:'analytics'}
];
const navItems = navGroups.flatMap(g => g.page ? [[g.page,g.label,g.icon]] : g.children.map(([id,label])=>[id,label,g.icon]));

const episodes = [
[1,"The Wealthy Student Rents the Smallest Room","Move-in Arc"],[2,"The Landlord’s Twenty Rules","Move-in Arc"],[3,"She Arrived with Just One Carry-On","Move-in Arc"],[4,"The Living Room Is Not Your Storage Room","Move-in Arc"],[5,"This Room Is Not Good Enough for This Bed","Move-in Arc"],[6,"The Landlord Won’t Let Her Change the Lock","Move-in Arc"],
[7,"The Air-Con Remote Has Gone Missing","Household Habits"],[8,"One Meal, Three Ways to Split the Bill","Household Habits"],[9,"She Hired Someone to Clean Her Room","Household Habits"],[10,"The Delivery Rider Knows the House Better Than the Landlord","Household Habits"],[11,"Who Opened My Parcel?","Household Habits"],[12,"Joseph Turns the Living Room into a Studio","Household Habits"],
[13,"The Landlord Brings Clients Home for a Viewing","Household Habits"],[14,"She Ends Up in a Property Advertisement","Household Habits"],[15,"The Sofa Was Returned Three Times","Household Habits"],[16,"The Downstairs Neighbour Comes Up to Complain","Singapore Culture"],[17,"Her First Warning from Management","Singapore Culture"],[18,"Even Money Cannot Buy This Time Slot","Singapore Culture"],
[19,"Joseph Posts the Wrong Video","Singapore Culture"],[20,"One Bad Review Keeps Three People Awake","Singapore Culture"],[21,"The 11 P.M. “Are You There?” Message","Singapore Culture"],[22,"Whose Job Did AI Just Do?","Singapore Culture"],[23,"A Quote That Is Seventy Percent Cheaper","Singapore Culture"],[24,"When Is the Payment Actually Coming?","Relationship Arc"],
[25,"Friend or Client?","Relationship Arc"],[26,"She Calculates Her Tuition Fees for the First Time","Relationship Arc"],[27,"Rent Killed a Good Business","Relationship Arc"],[28,"What Happens to People Who Cannot Use the App?","Relationship Arc"],[29,"This Room Is Suddenly No Longer for Rent","Relationship Arc"],[30,"Under One Roof","Relationship Arc"]
];

const topicGroups = {
"Shared Living":["Rent","Deposit","Utilities","Air-Conditioning","Laundry","Cleaning the Bathroom","Cleaning","Noise","Bringing Friends Home","Fridge","Cooking","Deliveries","Pets","Daily Routine","Shared Areas"],
"Singapore Culture":["Chope","Singlish","Hawker Centre","Queueing","MC","HDB","Condo","MRT","Bus","ERP","COE","CPF","Singpass","National Day","Hawker Culture"],
"Newcomers from China":["Finding a Home","SIM Card","Opening a Bank Account","Seeing a Doctor","Finding a Job","Applying for a Pass","Transport","Shopping","Food","Schools","Tenancy Agreement","Agent","Weather","English Accent"],
"The Trio’s Relationships":["Arguments","Silent Treatment","Birthdays","Breakups","Job Loss","Illness","Borrowing Money","Misunderstandings","Secrets","Helping Each Other","New Friends","Family Visits"],
"Festivals & Trends":["Chinese New Year","National Day","Mid-Autumn Festival","Christmas","Hari Raya Puasa","Deepavali","Singles’ Day","Gaokao","Singapore General Election","Concerts","New Policies"]
};

const defaultIdeas = [
 {title:"The Air-Conditioner Remote Is Missing",category:"Shared Living",summary:"James limits air-conditioner use, but the remote disappears. It is eventually found hidden in the fridge by Joseph.",lead:"All Three",scene:"Living Room",status:"Idea Box"},
 {title:"Tissue Is Not Rubbish",category:"Singapore Culture",summary:"Joseph throws away tissue left on a table. Angeline returns to find that someone else has taken the reserved seat.",lead:"Joseph",scene:"Hawker Centre",status:"For Discussion"},
 {title:"Why Does Someone Rich Rent a Small Room?",category:"Chinese International Students",summary:"A visitor asks why Angeline rents only one tiny room. She insists that she is not broke—the wide-angle listing photos misled her—while James argues that the photos were technically accurate.",lead:"All Three",scene:"Living Room",status:"For Discussion"}
];


function parseRoute(raw){
  const route=(raw||'home').replace(/^#/,'');
  let m;
  if((m=route.match(/^episode-(\d{1,2})$/))) return {page:'season',episode:+m[1],route};
  if((m=route.match(/^(season|scripts|analytics)-season-([123])$/))) return {page:m[1],season:+m[2],route};
  if((m=route.match(/^production-(board|list|calendar)-season-([123])$/))) return {page:'production',productionView:m[1],season:+m[2],route};
  if(route==='production') return {page:'production',productionView:'board',season:1,route};
  if((m=route.match(/^schedule-(cards|calendar|list)$/))) return {page:'schedule',scheduleView:m[1],route};
  if(route==='schedule') return {page:'schedule',scheduleView:'cards',route};
  return {page:route,route};
}
function currentRoute(){return parseRoute(location.hash.replace('#','')||'home');}
function goRoute(route){if(location.hash.replace('#','')===route){render();}else{location.hash=route;}}

let state = {
  page: currentRoute().page,
  ideas: SharedIdeas.getLocal(defaultIdeas)
};

const nav = document.getElementById('nav');
const content = document.getElementById('content');
const pageTitle = document.getElementById('pageTitle');
const sidebar = document.getElementById('sidebar');

function badge(text, cls=''){ return `<span class="badge ${cls}">${text}</span>`; }
function card(title, body, extra=''){ return `<article class="card ${extra}"><h4>${title}</h4>${body}</article>`; }
function section(title, subtitle, body){ return `<section class="section"><div class="section-header"><div><h3>${title}</h3><p>${subtitle||''}</p></div></div>${body}</section>`; }

function renderNav(){
  nav.innerHTML = navGroups.map(group=>{
    if(group.page){
      return `<button class="nav-btn nav-primary ${state.page===group.page?'active':''}" data-page="${group.page}"><span class="nav-icon">${group.icon}</span><span>${group.label}</span></button>`;
    }
    const active = group.children.some(([id])=>id===state.page || (id==='season'&&state.page==='season') || (id==='production'&&state.page==='production') || (id==='schedule'&&state.page==='schedule') || (id==='availability-common'&&state.page.startsWith('availability')));
    return `<div class="nav-group ${active?'open':''}" data-nav-group="${group.id}">
      <button class="nav-group-toggle ${active?'active-parent':''}" type="button"><span class="nav-icon">${group.icon}</span><span>${group.label}</span><span class="nav-chevron">⌄</span></button>
      <div class="nav-submenu">${group.children.map(([id,label])=>`<button class="nav-sub-btn ${state.page===id || (id==='season'&&state.page==='season') || (id==='production'&&state.page==='production') || (id==='schedule'&&state.page==='schedule') || (id==='availability-common'&&state.page.startsWith('availability'))?'active':''}" data-page="${id}">${label}</button>`).join('')}</div>
    </div>`;
  }).join('');
  nav.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{ goRoute(btn.dataset.page==='season'?'season-season-1':btn.dataset.page==='production'?'production-board-season-1':btn.dataset.page==='schedule'?'schedule-cards':btn.dataset.page); sidebar.classList.remove('open'); });
  nav.querySelectorAll('.nav-group-toggle').forEach(btn=>btn.onclick=()=>btn.closest('.nav-group').classList.toggle('open'));
}

const pages = {
home(){ return SharedEpisodes.dashboardPage('en'); },
positioning(){ return introPage('Project Positioning','This is not just a comedy account. It is an expandable short-drama IP.',[
 ['Project Name','Working title: Under One Roof. The title may change, but the story world and character relationships can be established now.'],
 ['One-line Introduction','A wealthy Chinese international student mistakenly signs for a room far smaller than it looked online, then moves in with a property-agent landlord and a social media advertising tenant.'],
 ['Target Audience','Chinese audiences interested in Singapore; people planning to move to Singapore; Chinese residents already in Singapore; local Singaporean Chinese; and viewers who enjoy light lifestyle comedy.'],
 ['Content Features','Authentic Singapore culture, international-student culture shock, shared living, property, social media marketing, campus life, client stories, light comedy, useful information, stable character relationships, and a continuing story world.']
], rules()); },
world(){ return introPage('Story World','The living room is only the stage; the character relationships are the real core.',[
 ['Story Background','James is the landlord and also works in property. Joseph is a long-term tenant who works in social media marketing, content production, and advertising. Angeline is a wealthy Chinese international student who has just arrived in Singapore. To prove that she can live independently, she rejects the luxury apartment arranged by her parents and signs a one-year tenancy after seeing only polished online photos. On arrival, she discovers that the room is far smaller than expected, but refuses to lose her deposit or admit to her family that she chose badly.'],
 ['Recurring Locations','Living room, sofa, dining table, kitchen, bedroom doors, front door, corridor, downstairs area, lift, nearby hawker centre, supermarket, and bus stop. Early episodes focus on James’s living room, with outdoor locations added later.'],
 ['Story-world Rules','James is the landlord and a property professional; Angeline is a wealthy Chinese international student and a new tenant; Joseph is a social media marketer, advertising professional, and long-term tenant; Angeline comes from a wealthy family but insists that she is living independently; her fixed reason for staying in the small room is that she trusted wide-angle photos, signed a one-year lease, refuses to lose the deposit, and will not admit the mistake to her parents; the three gradually become friends.'],
 ['Long-term Expansion','Future themes may include Singapore campus life, international-student routines, property, renting and buying homes, advertising, content creation, clients, friendship, romance, family, festivals, policy, and neighbours, while retaining the long-running joke that she is wealthy but trapped by her lease and pride.']
]); },
characters(){ return `${section('Core Characters','Keep their real professions, while heightening personality traits for comedy',`<div class="grid grid-3">${character('James','Landlord / Property Professional','J','avatar-james',['Rule-oriented','Rational','Protects property value','Understands clients','Appears annoyed but still helps'],'Views every situation through property value, rental return, client needs, and Singapore rules; introduces property, housing, and local-life storylines.',['Must not sell property in every episode','Must not only talk about rules','Must not treat clients as plot devices','Needs wrong judgments and moments when the tenants outsmart him'])}${character('Angeline','New Tenant / Wealthy Chinese International Student','A','avatar-angeline',['Wealthy background','Acts quickly','Pampered but not cruel','Uses money and efficiency to solve problems','Too proud to admit mistakes','Not yet integrated into Singapore'],'Represents newly arrived Chinese viewers. Her honest reactions to room size, house rules, Singlish, public transport, hawker centres, and campus culture drive the comedy. The central joke is that she is not short of money—she simply refuses to lose the deposit or admit that she chose badly.',['Must not only show off wealth','Must not look down on locals','Must not lack all common sense','Must not solve every episode with money','Must gradually become independent and adapt to Singapore'])}${character('Joseph','Tenant / Social Media Marketer','J','avatar-joseph',['Sensitive to attention','Always sees content opportunities','Understands advertising','Creative and unpredictable','Sometimes goes too far for results'],'Judges every event by whether it can be filmed, go viral, or justify ad spend; turns domestic conflict into content and creates new complications.',['Must not only hold a phone','Must not appear professionally incompetent','Should genuinely solve marketing problems','Needs failed predictions and reversals'])}</div>`)}
 ${section('Typical Reactions & Lines','Use these to maintain character consistency while writing',`<div class="grid grid-3">${card('James','<ul class="list"><li>“This will affect the property value.”</li><li>“A client is coming for a viewing.”</li><li>Calculates rent, return, and risk first</li><li>Still ends up cleaning up the tenants’ mess</li></ul>')}${card('Angeline','<ul class="list"><li>“I am not broke. The photos misled me.”</li><li>“How much would it cost to solve this?”</li><li>“Why is that not allowed in Singapore?”</li><li>Complains about the small room but refuses to admit she chose badly</li></ul>')}${card('Joseph','<ul class="list"><li>“Wait, do that again. I did not record it.”</li><li>“Let us test it with a small ad budget first.”</li><li>Judges every conflict by its content potential</li><li>Often makes situations more complicated for better footage</li></ul>')}</div>`)}`; },
relations(){ return `${section('Character Relationships','Recurring relationships determine how conflict works in each episode',`<div class="grid grid-2">${card('James × Angeline','<p><strong>Landlord Rules vs Wealthy Student</strong></p><p>James enforces the lease, deposit, and house rules. Angeline assumes money can solve most problems, yet refuses to waste her deposit or admit that the listing photos misled her.</p>')}${card('James × Joseph','<p><strong>Professional Viewings vs Content Traffic</strong></p><p>James needs an orderly client experience, while Joseph wants to film, create a hook, or test advertising performance.</p>')}${card('Angeline × Joseph','<p><strong>Privileged Student Life vs Content Traffic</strong></p><p>Joseph sees Angeline’s culture shock as perfect content. She dislikes being filmed without warning, yet still cares about whether she looks good on camera.</p>')}${card('The Trio','<div class="callout"><strong>They appear to annoy one another but have effectively become a family.</strong></div>')}</div>`)}
 ${section('Relationship Development Principles','Season 1 needs gradual relationship growth, not only standalone jokes',`<div class="timeline"><div class="timeline-item"><h4>Strangers Testing Boundaries</h4><p>At first, everyone protects themselves through rules and small schemes.</p></div><div class="timeline-item"><h4>Conflict and Dependence</h4><p>Their habits clash, but they begin helping one another.</p></div><div class="timeline-item"><h4>Becoming a Real Family</h4><p>Illness, moving out, and a new tenant make them realise how important they are to one another.</p></div></div>`)}`; },
episodeManagement(){ return SharedEpisodes.managementPage('en'); },
season(){ const r=currentRoute(); setTimeout(()=>{if(r.season)SharedEpisodes.setSeason(r.season);},80); return SharedEpisodes.seasonPage('en'); },
special(){ return SharedSpecial.page('en'); },
ideas(){ return `${section('Story Topic Library','Long-term topic categories beyond Season 1',`<div class="grid grid-3">${Object.entries(topicGroups).map(([k,v])=>card(k,`<div class="filters">${v.map(x=>badge(x)).join('')}</div>`)).join('')}</div>`)}${section('Team Idea Box','Entries use one shared dataset. After Cloudflare D1 is connected, all three members can see updates across devices.',`<div id="ideasTable">${ideasTable()}</div>`)}`; },
episode(){ return `${section('Episode SheetTemplate','Every episode should use the same fields',`<div class="table-wrap"><table><thead><tr><th>Field</th><th>Example</th></tr></thead><tbody>${[['Episode','EP01'],['Title','The Rich Student Rented the Smallest Room'],['Arc','Move-in Arc'],['Core Cultural Point','SingaporeHousing & Tenancy'],['Main Cast','James, Angeline and Joseph'],['Supporting Cast','None'],['Scene','Living Room'],['Duration','4–7 minutes'],['Story Status','Idea / Outline / Script / Filmed / Edited / Published'],['Writer','Name'],['Director','Name'],['Shoot Date','Date'],['Publication Date','Date'],['Platforms','Douyin / Xiaohongshu / WeChat Channels / YouTube'],['Props','Contract, Suitcases, Keys'],['Notes','Keep the wide-angle photos, one-year lease, deposit, and pride logic consistent']].map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td></tr>`).join('')}</tbody></table></div>`)}${section('Episode Structure','Every final script must include',`<div class="grid grid-3">${['Opening Hook: Establish the abnormal situation within 10–20 seconds','Act One Setup: Character goal, setting, stakes and starting conflict','Act Two Escalation: At least two failed attempts and a midpoint reversal','Act Three Climax: The three approaches collide and create a consequence','Relationship Beat: Reveal a weakness or change the trio’s relationship','Full Scene Dialogue: Organised by scene, action and character','Shot & Sound Plan: Coverage, reactions, blocking, subtitles and sound','Release Review: First-30-second retention, completion and next-episode conversion'].map((x,i)=>card(`0${i+1}`,`<p>${x}</p>`)).join('')}</div>`)}`; },
scripts(){ const r=currentRoute(); setTimeout(()=>{if(r.season)SharedEpisodes.setSeason(r.season);},80); return SharedEpisodes.scriptsPage('en'); },
production(){ const r=currentRoute(); setTimeout(()=>{if(r.season)SharedEpisodes.setSeason(r.season); if(r.productionView)SharedEpisodes.setProductionView(r.productionView);},80); return SharedEpisodes.productionPage('en'); },
availability(){ return availabilityPageEn(); },
'availability-common'(){ return availabilityPageEn('overlap'); },
'availability-members'(){ return availabilityPageEn('people'); },
'availability-dates'(){ return availabilityPageEn('week'); },
schedule(){ const r=currentRoute(); scheduleViewModeEn=r.scheduleView||'cards'; return schedulePageEn(); },
team(){ return teamPage('en'); },
supporting(){ return supportingPage('en'); },
singapore(){ const cats=['Housing & Tenancy','Transport','Food','Work','Education','Laws & Fines','Festivals','Language','Social Customs','Government Services','Healthcare','Banking','Mobile & Internet']; return `${section('Singapore Reference Library','All cultural and policy information must be accurate and sourced',`<div class="grid grid-4">${cats.map(x=>card(x,'<p>Store the topic explanation, official source, last verification date, related episodes, and whether it has been used.</p>')).join('')}</div>`)}${section('Reference Entry Standard','Prevent inaccurate information from appearing in the series',`<div class="table-wrap"><table><thead><tr><th>Field</th><th>Requirement</th></tr></thead><tbody><tr><td>Topic</td><td>Define one filmable question</td></tr><tr><td>Plain-language Explanation</td><td>Explain it in audience-friendly language</td></tr><tr><td>Official Source</td><td>Prioritise government agencies, statutory boards, or official operators</td></tr><tr><td>Last Verified</td><td>Policies and fees must be kept current</td></tr><tr><td>Related Episodes</td><td>Identify where the information can be used</td></tr><tr><td>Used</td><td>Prevent duplication or support sequels</td></tr></tbody></table></div>`)}`; },
analytics(){ const r=currentRoute(); setTimeout(()=>{if(r.season)SharedEpisodes.setSeason(r.season);},80); return SharedEpisodes.analyticsPage('en'); },
brand(){ return SharedBrand.page('en'); },
public(){ return `${section('Site Structure','Build the internal site first and open a public site later',`<div class="grid grid-2">${card('Internal Site','<ul class="list"><li>Script</li><li>Shoot Schedule</li><li>Contact Details</li><li>Unreleased Content</li><li>Production Budget</li><li>Internal Discussions</li><li>Performance Data</li></ul>')}${card('Public Site','<ul class="list"><li>Project Introduction</li><li>Character Introduction</li><li>Published Episodes</li><li>Behind the Scenes</li><li>Collaboration</li><li>Casting</li><li>Brand Partnerships</li><li>Contact Details</li></ul>')}</div>`)}${section('Version 1 Completion Standard','Any new member must understand the following within 30 minutes',`<div class="callout">What the project is, whom they play or what they are responsible for, current progress, and the next action.</div>`)}`; }
};

const episodeHooksEn = [
'“This is my room? My wardrobe at home is bigger.”','Angeline opens her phone: “Where is the room from the photos?”','James goes silent when the eighth suitcase enters.','A guest asks the obvious question: “If you are rich, why do you live here?”','James unfolds a house-rule list that reaches the floor.','James says the deposit is non-refundable; Angeline instantly changes her position.',
'James finds the air-conditioner and the window open at the same time.','Angeline stares at the washing machine: “Which button calls the helper?”','James places the electricity bill on the table.','Joseph accidentally eats Angeline’s imported ingredients.','Angeline announces that every chore will be outsourced.','James smells durian and rushes into the living room.','The camera starts with Angeline in gloves outside the toilet.','James comes home to a living room full of unknown classmates.','Angeline opens a design plan: “This living room needs an upgrade.”',
'Angeline throws away a tissue packet that was reserving a seat.','Angeline stands with her tray: “Nobody brings it to the table?”','Angeline asks seriously: “Does can can mean even more can?”','The bus leaves before she realises she passed her stop.','She is about to drink when James and Joseph shout at once.','She stands in the corridor holding rubbish: “Where exactly does this go?”','James lists three things money still cannot let her do.','A storm begins; only Angeline panics and runs for an umbrella.',
'Joseph points the camera at her: “First time doing chores. Action.”','She wants to spend a small-room budget redesigning a small room.','James brings in a client while Angeline is insulting the room.','Her family stops answering, so she must solve the problem alone.','The video goes viral, but every comment asks whether she can clean a toilet.','Her parents call: “Show us where you are living.”','Angeline packs to leave, then realises she does not want to.'
];
function episodeDetailEn(ep){ const [num,title,phase]=ep; const hook=episodeHooksEn[num-1]; const isFirst=num===1; return {
 status:isFirst?'First Script Draft':'Story Outline',duration:'4–7 minutes',scene:num<=15?'James’s living room / bedroom entrance':'Living room + essential exterior',cast:'James, Angeline, Joseph',hook,
 five:`Within the first 30 seconds, establish the characters, the episode event and all three positions so the audience understands why the situation will keep escalating.`,
 goal:`Angeline tries to solve “${title}” in her own way while protecting her image as wealthy, independent, and never wrong.`,
 obstacle:`James insists on Singapore rules, tenancy logic, or property management; Joseph turns the conflict into a content opportunity and makes it worse.`,
 mid:`Act Two must contain at least two failed attempts. First make the problem appear easy to solve, then reveal that the real obstacle is a rule, pride, misunderstanding or the trio’s relationship.`,
 climax:`In Act Three, all three approaches collide in a complete climax, consequence and relationship shift. The reversal must pay off the title rather than end with only one joke.`,
 ending:`End on one short reversal and a comment question: who was actually more reasonable?`,
 culture:`Use only one genuine Singapore-life point connected to “${title}”. Verify any policy, fee, or legal claim before publishing.`,
 script:isFirst?[
 '【Shot 1 / Wide at entrance】Angeline enters with several suitcases and looks around.','Angeline: Where is my room?','James points to a small door: Here.','Angeline: I asked for my room, not the storeroom.','James: That is your room.','【Shot 2 / Phone close-up】Angeline compares the listing photos.','Angeline: It was much bigger in the photos.','James: The photos did not lie. It was a wide-angle lens.','Joseph raises his phone: That reaction was good. Say it again—I missed it.','Angeline: I want to cancel the lease.','James: Early termination means no deposit refund.','【Pause + three reaction shots】','Angeline: Actually… a smaller room feels safer.'
 ]:[`[Act One · Scene 1 / Opening] ${hook}`,'[Act One · Scene 2] Establish the event of the day, the relationships and why this problem must be dealt with now.','[Act One · Scene 3] Angeline proposes a seemingly effective solution; James objects from a landlord or local-rules perspective; Joseph sees a content opportunity.','[Act One Turn] A new condition appears, preventing anyone from simply walking away.','[Act Two · Scene 4] First attempt: Angeline takes control but fails because of overconfidence or unfamiliarity with local life.','[Act Two · Scene 5] James takes over with the safe solution, which Angeline or Joseph disrupts.','[Act Two · Scene 6] Joseph intervenes for reach, advertising or footage. It appears to work briefly, then creates a larger consequence.','[Midpoint Reversal] They realise the real problem is not money but a rule, pride, misunderstanding or lack of trust.','[Act Two Back Half] The three blame one another. An older tension resurfaces and one character exposes a genuine weakness.','[Low Point] The plan fails completely and now affects the property, a client, school or their relationship.','[Act Three · Scene 7] They are forced to cooperate, with each character contributing a genuine strength.','[Climax] Pay off the episode title through action, dialogue and a relationship reversal—not only a punchline.','[Consequence] Resolve the main problem or leave a believable cost, showing what changed.','[Tag Scene] Return to normal life, then introduce a small new conflict or next-episode thread.','[End Gag] Add a 10–20 second character beat that can also be cut into a promotional clip.']
};}
window.openEpisodeDetail=(number)=>{ const ep=episodes.find(e=>e[0]===number);if(!ep)return;const d=episodeDetailEn(ep);
 document.getElementById('episodeModalTitle').textContent=`EP${String(ep[0]).padStart(2,'0')} · ${ep[1]}`;document.getElementById('episodeModalEyebrow').textContent='Episode Creative Workspace';
 document.getElementById('episodeModalBody').innerHTML=`<div class="episode-summary-grid">${[['Phase',ep[2]],['Status',d.status],['Target Length',d.duration],['Main Location',d.scene]].map(x=>`<div class="episode-summary-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>
 <div class="metric-strip"><div class="metric-box"><strong>Episode Length</strong><span>Target 4–7 minutes, allowing complete scenes and relationship development.</span></div><div class="metric-box"><strong>Three-act Structure</strong><span>Act One setup, Act Two escalation, Act Three climax and consequence.</span></div><div class="metric-box"><strong>Scene Count</strong><span>Use roughly 4–7 scenes; each must move plot or relationship forward.</span></div><div class="metric-box"><strong>Release Metrics</strong><span>First-30-second retention, average watch time, completion and next-episode conversion.</span></div></div>
 <div class="script-grid">${[['Title / Thumbnail Line',ep[1]],['Opening Hook / First 20 Seconds',d.hook],['Act One Setup / First 30 Seconds',d.five],['Character Goal',d.goal],['Obstacle & Escalation',d.obstacle],['Midpoint Turn',d.mid],['Climax / Final Twist',d.climax],['Ending Hook',d.ending],['Singapore Culture Point',d.culture]].map((x,i)=>`<div class="script-block ${i===8?'full':''}"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}<div class="script-block full"><h4>Full Script / Scene Dialogue</h4><ol class="script-lines">${d.script.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="script-block full"><h4>Post-release Data</h4><p>Platform, release date, final runtime, first-30-second retention, one-minute retention, average watch time, completion rate, next-episode conversion, like rate, comment rate, share rate, save rate, new followers, best comment, and next-episode improvement.</p></div></div>`;
 const m=document.getElementById('episodeModal');m.classList.add('open');m.setAttribute('aria-hidden','false');};
const episodeModal=document.getElementById('episodeModal');document.querySelectorAll('[data-close-episode-modal]').forEach(x=>x.onclick=()=>{episodeModal.classList.remove('open');episodeModal.setAttribute('aria-hidden','true');});

function statCard(label,num,percent){ return `<article class="card"><div class="stat"><div><div class="stat-label">${label}</div><div class="stat-number">${num}</div></div>${badge(percent)}</div><div class="progress"><span style="width:${percent}"></span></div></article>`; }
function quick(title,desc,page){ return `<article class="card"><h4>${title}</h4><p>${desc}</p><button class="ghost-btn" onclick="location.hash='${page}'">Open</button></article>`; }
function introPage(title,subtitle,items,extra=''){ return `${section(title,subtitle,`<div class="grid grid-2">${items.map(x=>card(x[0],`<p>${x[1]}</p>`)).join('')}</div>`)}${extra}`; }
function rules(){ const r=['Every episode needs a story, not just information','Every episode needs conflict; the trio cannot simply talk throughout','Each episode covers one core issue','Singapore information must be accurate','Do not demean any country or group','Comedy should come from character, not crude clowning','Commercial integration must not damage the story']; return section('ContentPrinciple','Mandatory creative rules',`<div class="grid grid-3">${r.map((x,i)=>card(`Principle ${i+1}`,`<p>${x}</p>`)).join('')}</div>`); }
function character(name,role,letter,avatar,traits,func,limits){ return `<article class="card character-card"><div class="character-avatar ${avatar}">${letter}</div><span class="badge">${role}</span><h4 style="font-size:22px;margin-top:10px">${name}</h4><p><strong>Core Traits</strong></p><div class="filters">${traits.map(x=>badge(x)).join('')}</div><p><strong>Story Function</strong></p><p>${func}</p><p><strong>Performance Boundaries</strong></p><ul class="list">${limits.map(x=>`<li>${x}</li>`).join('')}</ul></article>`; }
function renderEpisodes(filter){ return episodes.filter(e=>filter==='All'||e[2]===filter).map(e=>`<article class="episode" role="button" tabindex="0" onclick="openEpisodeDetail(${e[0]})" onkeydown="if(event.key==='Enter')openEpisodeDetail(${e[0]})"><div class="episode-num">EP${String(e[0]).padStart(2,'0')}</div><h4>${e[1]}</h4><p>${e[2]} · Open drama outline and scene script</p></article>`).join(''); }
window.filterEpisodes=(filter,btn)=>{ document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); document.getElementById('episodeGrid').innerHTML=renderEpisodes(filter); };
function ideasTable(){ if(!state.ideas.length) return '<div class="empty">No ideas yet</div>'; return `<div class="table-wrap"><table><thead><tr><th>Title</th><th>Category</th><th>One-line Story</th><th>Character</th><th>Scene</th><th>Status</th></tr></thead><tbody>${state.ideas.map(i=>`<tr><td><strong>${i.title}</strong></td><td>${i.category}</td><td>${i.summary}</td><td>${i.lead}</td><td>${i.scene}</td><td>${badge(SharedIdeas.statusLabel(i.statusCode || i.status, 'en'), (i.statusCode || i.status)==='discussion' || i.status==='For Discussion' ? 'yellow' : '')}</td></tr>`).join('')}</tbody></table></div>`; }
function kanban(cols){ return `<div class="kanban">${cols.map(([name,items])=>`<div class="kanban-col"><h4>${name}<span>${items.length}</span></h4>${items.map(i=>`<div class="kanban-item"><strong>${i}</strong><br><small>Awaiting owner update</small></div>`).join('')}</div>`).join('')}</div>`; }
function teamCard(name,title,desc){ return `<article class="card"><div class="character-avatar ${name==='James'?'avatar-james':name==='Angeline'?'avatar-angeline':'avatar-joseph'}">${name[0]}</div><h4>${name}</h4><span class="badge">${title}</span><p>${desc}</p></article>`; }

function render(){ const r=currentRoute(); state.page=r.page; if(!pages[state.page]) state.page='home'; renderNav(); const availabilityTitle=['availability','availability-common','availability-members','availability-dates'].includes(state.page)?'Team Availability':null; pageTitle.textContent=availabilityTitle||navItems.find(x=>x[0]===state.page)?.[1]||'Home'; content.dataset.page=state.page; content.innerHTML=pages[state.page](); const r2=currentRoute(); if(r2.episode){setTimeout(()=>SharedEpisodes.open(r2.episode),180);} }
window.addEventListener('hashchange',()=>{ state.page=currentRoute().page; render(); window.scrollTo(0,0); });

document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');
const modal=document.getElementById('ideaModal');
window.openIdeaModal=()=>{ modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); };
document.getElementById('addIdeaBtn')?.addEventListener('click',openIdeaModal);
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>{ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); });
document.getElementById('ideaForm').onsubmit=async(e)=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(e.target)); const saved=await SharedIdeas.add({...d,statusCode:'idea'}); state.ideas.unshift(saved); e.target.reset(); modal.classList.remove('open'); if(state.page==='ideas') render(); };

// Render immediately from local data so the dashboard never waits for D1/API startup.
render();

// Refresh shared ideas in the background. Only redraw the ideas page when its data changes.
const refreshSharedIdeas = () => SharedIdeas.load(defaultIdeas, { timeoutMs: 3500 }).then(ideas=>{
  const changed = JSON.stringify(ideas) !== JSON.stringify(state.ideas);
  state.ideas = ideas;
  if(changed && state.page==='ideas') render();
}).catch(()=>{});

if('requestIdleCallback' in window){
  requestIdleCallback(refreshSharedIdeas, { timeout: 1200 });
}else{
  setTimeout(refreshSharedIdeas, 0);
}

const productionStagesEn=[
 {id:'outline',name:'Topic & Outline',color:'purple',episodes:[1,2,3,4,5,6]},
 {id:'writing',name:'Script Writing',color:'blue',episodes:[7,8,9,10,11]},
 {id:'locked',name:'Script Locked',color:'cyan',episodes:[12,13,14,15]},
 {id:'shoot',name:'Ready to Shoot',color:'yellow',episodes:[16,17,18,19]},
 {id:'filmed',name:'Filming Complete',color:'orange',episodes:[20,21,22]},
 {id:'post',name:'Post-production',color:'pink',episodes:[23,24,25]},
 {id:'publish',name:'Ready / Published',color:'green',episodes:[26,27,28,29,30]}
];
const productionMetaEn={};
Object.entries({1:['Angeline','High','2026-08-02','Props incomplete',72],2:['Joseph','Medium','2026-08-02','Outline approval pending',45],3:['Angeline','High','2026-08-02','Suitcase count unconfirmed',55],4:['James','Medium','2026-08-09','None',35],5:['James','High','2026-08-09','House rules list pending',30],6:['Angeline','High','2026-08-09','Deposit clause needs verification',40],7:['Joseph','Medium','2026-08-16','None',48],8:['Angeline','Medium','2026-08-16','Laundry scene pending',42],9:['James','Low','2026-08-16','None',38],10:['Angeline','Medium','2026-08-23','Imported-food props',40],11:['Joseph','Medium','2026-08-23','Service price verification',44],12:['James','Medium','2026-08-23','None',70],13:['Angeline','High','2026-08-30','Cleaning props',76],14:['Joseph','Medium','2026-08-30','Supporting cast unconfirmed',74],15:['James','Low','2026-08-30','Furniture plan pending',71],16:['Joseph','High','2026-09-06','Hawker-centre location',82],17:['Angeline','High','2026-09-06','Tray-return exterior',84],18:['James','Medium','2026-09-06','Singlish line review',80],19:['Angeline','Medium','2026-09-13','Bus exterior',79],20:['Joseph','High','2026-09-13','Backup confirmation',88],21:['James','Medium','2026-09-13','Pickup shot needed',86],22:['Angeline','High','2026-09-20','Fine claim verification',90],23:['Joseph','Medium','2026-09-20','Rough cut in progress',92],24:['Joseph','High','2026-09-20','Waiting for subtitles',94],25:['Angeline','Medium','2026-09-27','Room makeover footage',91],26:['James','High','2026-09-27','Thumbnail pending',96],27:['Angeline','High','2026-09-27','Release time unset',97],28:['Joseph','High','2026-10-04','Platform title pending',98],29:['Angeline','High','2026-10-04','Parent-call props',95],30:['All Three','High','2026-10-04','Final approval',99]}).forEach(([k,v])=>productionMetaEn[k]=v);
function productionCardEn(n){const ep=episodes.find(e=>e[0]===n),m=productionMetaEn[n],blocked=m[3]!=='None';return `<article class="prod-card ${blocked?'is-blocked':''}" onclick="openEpisodeDetail(${n})"><div class="prod-card-top"><span>EP${String(n).padStart(2,'0')}</span><span class="priority priority-${m[1].toLowerCase()}">${m[1]}</span></div><h4>${ep[1]}</h4><div class="prod-meta"><span>Owner: ${m[0]}</span><span>Shoot: ${m[2]}</span></div><div class="prod-progress"><i style="width:${m[4]}%"></i></div><div class="prod-card-bottom"><span>${m[4]}%</span><span class="${blocked?'blocker':'clear'}">${blocked?'⚠ '+m[3]:'✓ No open issue'}</span></div></article>`;}
function productionDashboardEn(){const total=episodes.length,locked=4,shoot=4,post=3,pub=5,blocked=Object.values(productionMetaEn).filter(x=>x[3]!=='None').length;return `${section('Production Overview','Each card represents one episode and moves through the production stages; red marks an issue that still needs attention',`<div class="production-toolbar"><div class="production-tabs"><button class="active" onclick="setProdViewEn('board',this)">Board</button><button onclick="setProdViewEn('list',this)">List</button><button onclick="setProdViewEn('calendar',this)">Shoot Calendar</button></div><div class="production-filters"><input id="prodSearchEn" placeholder="Search episode or title" oninput="filterProductionEn()"><select id="prodOwnerEn" onchange="filterProductionEn()"><option value="">All owners</option><option>Angeline</option><option>James</option><option>Joseph</option><option>All Three</option></select><select id="prodPriorityEn" onchange="filterProductionEn()"><option value="">All priorities</option><option>High</option><option>Medium</option><option>Low</option></select><label><input type="checkbox" id="prodBlockedEn" onchange="filterProductionEn()"> Issues only</label></div></div><div class="prod-stats">${[['Total Episodes',total],['Scripts Locked',locked],['Ready to Shoot',shoot],['Post-production',post],['Ready / Published',pub],['Open Issues',blocked]].map((x,i)=>`<div class="prod-stat s${i}"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div id="productionViewEn">${renderProdBoardEn()}</div>`)}`;}
function renderProdBoardEn(){return `<div class="episode-kanban">${productionStagesEn.map(st=>`<section class="episode-stage stage-${st.color}"><header><div><span class="stage-dot"></span><h4>${st.name}</h4></div><strong>${st.episodes.length}</strong></header><div class="stage-cards">${st.episodes.map(productionCardEn).join('')}</div></section>`).join('')}</div>`;}
function renderProdListEn(){return `<div class="table-wrap prod-table"><table><thead><tr><th>Episode</th><th>Title</th><th>Stage</th><th>Owner</th><th>Priority</th><th>Shoot Date</th><th>Progress</th><th>Open Issue</th></tr></thead><tbody>${productionStagesEn.flatMap(st=>st.episodes.map(n=>{const ep=episodes.find(e=>e[0]===n),m=productionMetaEn[n];return `<tr onclick="openEpisodeDetail(${n})"><td>EP${String(n).padStart(2,'0')}</td><td><strong>${ep[1]}</strong></td><td><span class="stage-pill stage-${st.color}">${st.name}</span></td><td>${m[0]}</td><td>${m[1]}</td><td>${m[2]}</td><td>${m[4]}%</td><td>${m[3]}</td></tr>`;})).join('')}</tbody></table></div>`;}
function renderProdCalendarEn(){const by={};Object.entries(productionMetaEn).forEach(([n,m])=>{(by[m[2]]??=[]).push(+n)});return `<div class="shoot-calendar">${Object.keys(by).sort().map(d=>`<article><header><strong>${d}</strong><span>${by[d].length} episodes</span></header><div>${by[d].map(n=>{const ep=episodes.find(e=>e[0]===n);return `<button onclick="openEpisodeDetail(${n})"><b>EP${String(n).padStart(2,'0')}</b><span>${ep[1]}</span></button>`}).join('')}</div></article>`).join('')}</div>`;}
window.setProdViewEn=(v,btn)=>{document.querySelectorAll('.production-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('productionViewEn').innerHTML=v==='board'?renderProdBoardEn():v==='list'?renderProdListEn():renderProdCalendarEn();};
window.filterProductionEn=()=>{const q=(document.getElementById('prodSearchEn')?.value||'').toLowerCase(),owner=document.getElementById('prodOwnerEn')?.value||'',pri=document.getElementById('prodPriorityEn')?.value||'',blocked=document.getElementById('prodBlockedEn')?.checked;document.querySelectorAll('.prod-card').forEach(card=>{const n=+card.querySelector('.prod-card-top span').textContent.replace('EP',''),m=productionMetaEn[n],ep=episodes.find(e=>e[0]===n);card.style.display=((!q||ep[1].toLowerCase().includes(q)||String(n).includes(q))&&(!owner||m[0]===owner)&&(!pri||m[1]===pri)&&(!blocked||m[3]!=='None'))?'':'none';});};

/* v64 shared team availability */
let availabilityEn=[];
const availabilitySeedEn=[
 {member:'Angeline',availabilityDate:'2026-08-04',dayOfWeek:2,startTime:'10:00',endTime:'14:00',note:'Morning and lunch hours'},
 {member:'James',availabilityDate:'2026-08-04',dayOfWeek:2,startTime:'11:00',endTime:'16:00',note:'Available before late afternoon'},
 {member:'Joseph',availabilityDate:'2026-08-04',dayOfWeek:2,startTime:'12:00',endTime:'18:00',note:'Afternoons preferred'},
 {member:'Angeline',availabilityDate:'2026-08-08',dayOfWeek:6,startTime:'10:00',endTime:'17:00',note:'Saturday preferred'},
 {member:'James',availabilityDate:'2026-08-08',dayOfWeek:6,startTime:'09:00',endTime:'15:00',note:''},
 {member:'Joseph',availabilityDate:'2026-08-08',dayOfWeek:6,startTime:'11:00',endTime:'19:00',note:''}
];
const weekEn=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const memberClassEn={Angeline:'av-angeline',James:'av-james',Joseph:'av-joseph'};

const availabilityNoteTranslationsEn={
 '\u4e0a\u5348\u4e0e\u5348\u9910\u65f6\u6bb5':'Morning and lunch hours',
 '\u4e0b\u5348\u524d\u53ef\u62cd':'Available before late afternoon',
 '\u5348\u540e\u8f83\u65b9\u4fbf':'Afternoons preferred',
 '\u5468\u516d\u4f18\u5148':'Saturday preferred'
};
function availabilityNoteEn(note=''){
 const value=String(note||'').trim();
 if(!value)return '';
 if(availabilityNoteTranslationsEn[value])return availabilityNoteTranslationsEn[value];
 return /[\u3400-\u9fff]/.test(value)?'Note entered in Chinese':value;
}
function availabilityPageEn(mode='overlap'){availabilityModeEn=mode;setTimeout(initAvailabilityEn,0);return `${section('Team Availability','Record the exact dates and times when Angeline, James and Joseph are free. The system automatically finds slots that work for all three.',`<div class="availability-head"><div><span class="availability-kicker">Shared team planning</span><p>Add individual availability first, then schedule filming from the common slots.</p></div><button class="primary-btn" onclick="openAvailabilityEn()">＋ Add Availability</button></div><div class="availability-tabs"><button class="${mode==='overlap'?'active':''}" onclick="setAvailabilityViewEn('overlap')">Common Slots</button><button class="${mode==='people'?'active':''}" onclick="setAvailabilityViewEn('people')">By Member</button><button class="${mode==='week'?'active':''}" onclick="setAvailabilityViewEn('week')">Date Overview</button></div><div id="availabilityViewEn"><div class="empty">Loading team availability…</div></div>`)}`;}
async function initAvailabilityEn(){availabilityEn=await SharedAvailability.load(availabilitySeedEn);renderAvailabilityEn();}
let availabilityModeEn='overlap';
window.setAvailabilityViewEn=(v)=>{const route=v==='people'?'availability-members':v==='week'?'availability-dates':'availability-common';location.hash=route;};
function toMinEn(t){const [h,m]=String(t).split(':').map(Number);return h*60+m}function fmtMinEn(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function dateLabelEn(v){if(!v)return 'Date not set';const d=new Date(v+'T00:00:00');return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} · ${weekEn[(d.getDay()+6)%7]}`}
function commonSlotsEn(){const out=[];const dates=[...new Set(availabilityEn.map(x=>x.availabilityDate).filter(Boolean))];for(const date of dates){const groups=['Angeline','James','Joseph'].map(m=>availabilityEn.filter(x=>x.member===m&&x.availabilityDate===date));if(groups.some(g=>!g.length))continue;for(const a of groups[0])for(const j of groups[1])for(const o of groups[2]){const s=Math.max(toMinEn(a.startTime),toMinEn(j.startTime),toMinEn(o.startTime)),e=Math.min(toMinEn(a.endTime),toMinEn(j.endTime),toMinEn(o.endTime));if(e-s>=60)out.push({availabilityDate:date,startTime:fmtMinEn(s),endTime:fmtMinEn(e),minutes:e-s})}}return out.sort((a,b)=>a.availabilityDate.localeCompare(b.availabilityDate)||a.startTime.localeCompare(b.startTime));}
function renderAvailabilityEn(){const el=document.getElementById('availabilityViewEn');if(!el)return;if(availabilityModeEn==='people')el.innerHTML=renderAvailabilityPeopleEn();else if(availabilityModeEn==='week')el.innerHTML=renderAvailabilityWeekEn();else el.innerHTML=renderAvailabilityOverlapEn();}
function renderAvailabilityOverlapEn(){const slots=commonSlotsEn();return `<div class="availability-summary"><div><span>Time Blocks</span><strong>${availabilityEn.length}</strong></div><div><span>Common Slots</span><strong>${slots.length}</strong></div><div><span>Members Included</span><strong>3 / 3</strong></div></div>${slots.length?`<div class="common-slot-grid">${slots.map((x,i)=>`<article class="common-slot-card"><div class="common-slot-day"><span>${dateLabelEn(x.availabilityDate)}</span><strong>${x.startTime}–${x.endTime}</strong></div><p>All three are available · ${Math.round(x.minutes/60*10)/10} hours</p><div class="common-members"><span class="av-angeline">A</span><span class="av-james">J</span><span class="av-joseph">J</span></div><button class="mini-btn" onclick="useCommonSlotEn(${i})">Schedule a Shoot</button></article>`).join('')}</div>`:`<div class="availability-empty"><strong>No common slot yet</strong><p>Add or adjust individual availability and the system will recalculate the overlap.</p></div>`}`;}
function renderAvailabilityPeopleEn(){return `<div class="availability-people">${['Angeline','James','Joseph'].map(m=>`<article class="availability-person"><header><div class="member-avatar ${memberClassEn[m]}">${m[0]}</div><div><strong>${m}</strong><span>${availabilityEn.filter(x=>x.member===m).length} time blocks</span></div><button class="mini-btn" onclick="openAvailabilityEn('', '${m}')">＋ Add</button></header><div class="availability-list">${availabilityEn.filter(x=>x.member===m).sort((a,b)=>(a.availabilityDate||'').localeCompare(b.availabilityDate||'')||a.startTime.localeCompare(b.startTime)).map(x=>`<button onclick="openAvailabilityEn('${x.id}')"><b>${dateLabelEn(x.availabilityDate)}</b><span>${x.startTime}–${x.endTime}</span><small>${availabilityNoteEn(x.note)||'Click to edit'}</small></button>`).join('')||'<p class="empty-inline">Not entered</p>'}</div></article>`).join('')}</div>`;}
function renderAvailabilityWeekEn(){const dates=[...new Set(availabilityEn.map(x=>x.availabilityDate).filter(Boolean))].sort();return `<div class="availability-week">${dates.map(date=>{const a=availabilityEn.filter(x=>x.availabilityDate===date).sort((x,y)=>x.startTime.localeCompare(y.startTime));return `<article><header><strong>${dateLabelEn(date)}</strong><span>${a.length} blocks</span></header><div>${a.map(x=>`<button class="${memberClassEn[x.member]}" onclick="openAvailabilityEn('${x.id}')"><b>${x.member}</b><span>${x.startTime}–${x.endTime}</span></button>`).join('')}</div></article>`}).join('')||'<div class="availability-empty"><strong>No dated availability yet</strong></div>'}</div>`;}
function availabilityFormEn(x={}){return `<form id="availabilityFormEn" class="form-grid"><input type="hidden" name="id" value="${x.id||''}"><label><span>Member</span><select name="member">${['Angeline','James','Joseph'].map(m=>`<option ${x.member===m?'selected':''}>${m}</option>`).join('')}</select></label><label><span>Date</span><input type="date" name="availabilityDate" value="${x.availabilityDate||''}" required onchange="syncAvailabilityDayEn(this)"></label><input type="hidden" name="dayOfWeek" value="${x.dayOfWeek||1}"><label><span>Start Time</span><input type="time" name="startTime" value="${x.startTime||'10:00'}" required></label><label><span>End Time</span><input type="time" name="endTime" value="${x.endTime||'14:00'}" required></label><label class="full"><span>Note</span><input name="note" value="${availabilityNoteEn(x.note)}" placeholder="Example: confirm one day in advance"></label><div class="modal-actions full">${x.id?'<button type="button" class="danger-btn" onclick="deleteAvailabilityEn()">Delete</button>':''}<span class="modal-spacer"></span><button type="button" class="ghost-btn" onclick="closeAvailabilityModalEn()">Cancel</button><button class="primary-btn">Save Availability</button></div></form>`;}
window.syncAvailabilityDayEn=input=>{const f=input.form;if(!input.value||!f)return;const d=new Date(input.value+'T00:00:00');f.dayOfWeek.value=((d.getDay()+6)%7)+1;};
window.openAvailabilityEn=(id='',member='')=>{const x=availabilityEn.find(i=>String(i.id)===String(id))||{member};showAvailabilityModalEn(x.id?'Edit Availability':'Add Availability',availabilityFormEn(x));setTimeout(()=>document.getElementById('availabilityFormEn').onsubmit=saveAvailabilityEn,0);};
async function saveAvailabilityEn(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.endTime<=d.startTime){alert('End time must be later than start time');return}let y=d.id?await SharedAvailability.update(d):await SharedAvailability.add(d);availabilityEn=d.id?availabilityEn.map(x=>String(x.id)===String(d.id)?y:x):[...availabilityEn,y];closeAvailabilityModalEn();renderAvailabilityEn();}
window.deleteAvailabilityEn=async()=>{const id=document.querySelector('#availabilityFormEn [name=id]').value;if(confirm('Delete this time block?')){await SharedAvailability.remove(id);availabilityEn=availabilityEn.filter(x=>String(x.id)!==String(id));closeAvailabilityModalEn();renderAvailabilityEn();}};
window.useCommonSlotEn=i=>{const x=commonSlotsEn()[i];if(!x)return;location.hash='schedule';setTimeout(()=>openShootDayEn(),120);};
function showAvailabilityModalEn(title,body){let m=document.getElementById('availabilityModalEn');if(!m){m=document.createElement('div');m.id='availabilityModalEn';m.className='modal';m.innerHTML='<div class="modal-card"><div class="modal-header"><h3 id="availabilityModalTitleEn"></h3><button class="icon-btn" onclick="closeAvailabilityModalEn()">×</button></div><div id="availabilityModalBodyEn"></div></div>';document.body.appendChild(m)}document.getElementById('availabilityModalTitleEn').textContent=title;document.getElementById('availabilityModalBodyEn').innerHTML=body;m.classList.add('open');}
window.closeAvailabilityModalEn=()=>document.getElementById('availabilityModalEn')?.classList.remove('open');


/* v14 shared shoot schedule */
const defaultShootDaysEn=[{id:'seed-1',date:'2026-08-02',callTime:'09:00',startTime:'10:00',endTime:'17:30',location:"James's Home",episodes:'EP01–EP04',cast:'James / Angeline / Joseph',crew:'On-set lead TBC',owner:'Angeline',status:'planning',issues:'Eight suitcases still need to be prepared',timeline:'09:00 Crew and cast call; equipment setup\n09:30 Rehearsal and lighting test\n10:00 Film EP01\n11:30 Film EP02\n13:00 Lunch\n14:00 Film EP03\n15:30 Film EP04\n17:00 Pickups and establishing shots\n17:30 Back up footage and wrap',wardrobeProps:'EP01: Arrival look; eight suitcases, phone, keys\nEP02: Continuity from EP01; rental photos, phone\nEP03: Second casual look; hangers, shoe boxes\nEP04: Indoor casual look; tenancy agreement, calculator',notes:'Confirm parking and lift access for moving luggage.'}];
let shootDaysEn=[];const shootStatusEn={planning:'Planning',confirmed:'Confirmed',shooting:'Filming',completed:'Completed',reshoot:'Reshoot Required'};let scheduleViewModeEn='cards';let scheduleMonthEn=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function schedulePageEn(){setTimeout(initScheduleEn,0);return `${section('Calendar & Production Schedule','Track shoots, editing, meetings and other team items in one shared schedule.',`<div class="schedule-head"><div class="schedule-stats" id="scheduleStatsEn"></div><div class="schedule-head-actions"><button class="primary-btn" onclick="openCalendarEventEn()">＋ New Calendar Item</button></div></div><div class="schedule-toolbar"><div class="production-tabs"><button class="${scheduleViewModeEn==='cards'?'active':''}" onclick="setScheduleViewEn('cards',this)">Item Cards</button><button class="${scheduleViewModeEn==='calendar'?'active':''}" onclick="setScheduleViewEn('calendar',this)">Calendar</button><button class="${scheduleViewModeEn==='list'?'active':''}" onclick="setScheduleViewEn('list',this)">List</button></div><select id="scheduleStatusEn" onchange="renderScheduleEn()"><option value="">All Statuses</option>${Object.entries(shootStatusEn).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><input id="scheduleSearchEn" placeholder="Search date, location or episode" oninput="renderScheduleEn()"></div><div id="scheduleViewEn"><div class="empty">Loading schedule…</div></div>`)}`;}
async function initScheduleEn(){shootDaysEn=(await SharedSchedules.load(defaultShootDaysEn)).map(x=>({eventType:'shoot',title:'',assignee:'',...x}));renderScheduleEn();}function filteredShootDaysEn(){const q=(document.getElementById('scheduleSearchEn')?.value||'').toLowerCase(),st=document.getElementById('scheduleStatusEn')?.value||'';return shootDaysEn.filter(x=>(!st||x.status===st)&&(!q||[x.date,x.location,x.episodes,x.cast].join(' ').toLowerCase().includes(q)));}function scheduleStatsEn(){const a=shootDaysEn,ep=new Set(a.flatMap(x=>(x.episodes.match(/EP\d+/g)||[])));return [['Calendar Items',a.length],['Episodes Linked',ep.size],['Items Remaining',a.filter(x=>x.status!=='completed').length],['Items With Notes',a.filter(x=>x.issues||x.notes).length]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');}
function shootCardEn(x){return `<article class="shoot-day-card status-${x.status}"><header><div><span>${x.date||'Date TBC'}</span><h4>${x.location||'Location TBC'}</h4></div><span class="shoot-status">${shootStatusEn[x.status]||x.status}</span></header><div class="shoot-day-core"><div><small>Call / Wrap</small><strong>${x.callTime||'—'}–${x.endTime||'—'}</strong></div><div><small>Episodes</small><strong>${x.episodes||'—'}</strong></div><div><small>Owner</small><strong>${x.owner||'—'}</strong></div></div><p class="shoot-cast"><b>Cast:</b> ${x.cast||'TBC'}</p>${x.issues?`<div class="shoot-issue">⚠ ${x.issues}</div>`:'<div class="shoot-clear">✓ No open items</div>'}<footer><button class="ghost-btn" onclick="viewShootDayEn('${x.id}')">View Call Sheet</button><button class="ghost-btn" onclick="openShootDayEn('${x.id}')">Edit</button></footer></article>`;}
window.setScheduleViewEn=(v,b)=>{scheduleViewModeEn=v;const route=`schedule-${v}`;if(location.hash.replace('#','')!==route){location.hash=route;return;}document.querySelectorAll('.schedule-toolbar .production-tabs button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');renderScheduleEn();};function calendarLabelEn(){return scheduleMonthEn.toLocaleDateString('en-US',{month:'long',year:'numeric'});} 
function monthKeyEn(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function calendarEventsEn(){const key=monthKeyEn(scheduleMonthEn);return filteredShootDaysEn().filter(x=>(x.date||'').startsWith(key));}
function renderMonthCalendarEn(){const y=scheduleMonthEn.getFullYear(),m=scheduleMonthEn.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay();const events=calendarEventsEn();let cells='';for(let i=0;i<offset;i++)cells+='<div class="month-cell outside"></div>';for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,items=events.filter(x=>x.date===date).sort((a,b)=>(a.startTime||a.callTime||'').localeCompare(b.startTime||b.callTime||''));cells+=`<div class="month-cell"><button class="month-day-number" onclick="openCalendarEventEn('', '${date}')">${d}</button><div class="month-events">${items.map(x=>{const type=x.eventType||'other';const time=x.startTime||x.callTime||'';const labels={shoot:'Shoot',editing:'Editing',meeting:'Meeting',other:'Other'};const label=x.title||x.episodes||labels[type];return `<button class="month-event ${type}" onclick="openCalendarEventEn('${x.id}')"><span>${time}</span><b>${label}</b><small>${x.assignee||x.owner||x.location||'Unassigned'}</small></button>`}).join('')}</div></div>`}return `<div class="month-calendar"><header><button class="month-nav" onclick="changeScheduleMonthEn(-1)">‹</button><h3>${calendarLabelEn()}</h3><button class="month-nav" onclick="changeScheduleMonthEn(1)">›</button></header><div class="month-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="month-grid">${cells}</div><footer><span><i class="legend-dot shoot"></i>Shoot</span><span><i class="legend-dot editing"></i>Editing</span><span><i class="legend-dot meeting"></i>Meeting</span><span><i class="legend-dot other"></i>Other</span></footer></div>`;}
window.changeScheduleMonthEn=n=>{scheduleMonthEn=new Date(scheduleMonthEn.getFullYear(),scheduleMonthEn.getMonth()+n,1);renderScheduleEn();};
window.setScheduleViewEn=(v,b)=>{scheduleViewModeEn=v;const route=`schedule-${v}`;if(location.hash.replace('#','')!==route){location.hash=route;return;}document.querySelectorAll('.schedule-toolbar .production-tabs button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');renderScheduleEn();};window.renderScheduleEn=()=>{const el=document.getElementById('scheduleViewEn');if(!el)return;document.getElementById('scheduleStatsEn').innerHTML=scheduleStatsEn();const a=filteredShootDaysEn();if(scheduleViewModeEn==='list')el.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Time</th><th>Title / Episodes</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.date}</td><td>${({shoot:'Shoot',editing:'Editing',meeting:'Meeting',other:'Other'})[x.eventType]||'Other'}</td><td>${x.startTime||x.callTime||'—'}–${x.endTime||'—'}</td><td>${x.title||x.episodes||'—'}</td><td>${x.assignee||x.owner||'—'}</td><td>${shootStatusEn[x.status]||x.status}</td><td><button class="mini-btn" onclick="openCalendarEventEn('${x.id}')">View</button></td></tr>`).join('')}</tbody></table></div>`;else if(scheduleViewModeEn==='calendar')el.innerHTML=renderMonthCalendarEn();else el.innerHTML=a.length?`<div class="calendar-item-grid">${a.map(x=>{const type=x.eventType||'other',typeLabel=({shoot:'Shoot',editing:'Editing',meeting:'Meeting',other:'Other'})[type]||'Other',owner=x.assignee||x.owner||'Unassigned',time=`${x.startTime||x.callTime||'—'}–${x.endTime||'—'}`,title=x.title||x.episodes||'Untitled item';return `<article class="calendar-item-card type-${type}" onclick="openCalendarEventEn('${x.id}')"><header><div><span class="calendar-type-badge">${typeLabel}</span><strong>${x.date||'—'}</strong></div><span class="calendar-status">${shootStatusEn[x.status]||x.status||'Planning'}</span></header><h4>${title}</h4><div class="calendar-item-meta"><div><small>Time</small><b>${time}</b></div><div><small>Owner</small><b>${owner}</b></div><div><small>Episodes</small><b>${x.episodes||'—'}</b></div></div>${x.location?`<p class="calendar-location">Location: ${x.location}</p>`:''}${x.notes||x.issues?`<p class="calendar-note">${x.notes||x.issues}</p>`:''}<footer><span>Click to view or edit</span><b>→</b></footer></article>`}).join('')}</div>`:'<div class="empty">No matching calendar items</div>';};
function calendarEventFormEn(x={}){return `<form id="calendarEventFormEn" class="form-grid"><input type="hidden" name="id" value="${x.id||''}"><label><span>Item Type</span><select name="eventType" required><option value="shoot" ${x.eventType==='shoot'?'selected':''}>Shoot</option><option value="editing" ${x.eventType==='editing'?'selected':''}>Editing</option><option value="meeting" ${x.eventType==='meeting'?'selected':''}>Meeting</option><option value="other" ${x.eventType==='other'||!x.eventType?'selected':''}>Other</option></select></label><label><span>Assigned to</span><select name="assignee"><option value="">Unassigned</option>${['Angeline','James','Joseph'].map(n=>`<option ${x.assignee===n||x.owner===n?'selected':''}>${n}</option>`).join('')}</select></label><label><span>Date</span><input type="date" name="date" value="${x.date||''}" required></label><label><span>Start Time</span><input type="time" name="startTime" value="${x.startTime||x.callTime||'10:00'}" required></label><label><span>End Time</span><input type="time" name="endTime" value="${x.endTime||'12:00'}" required></label><label class="full"><span>Item</span><input name="title" value="${x.title||x.episodes||''}" placeholder="e.g. shoot EP03 / rough-cut edit / cast meeting" required></label><label class="full"><span>Episodes</span><input name="episodes" value="${x.episodes||''}" placeholder="e.g. EP03, EP04"></label><label class="full"><span>Location</span><input name="location" value="${x.location||''}" placeholder="e.g. James's house / Zoom / office"></label><label class="full"><span>Notes</span><textarea name="notes" rows="4">${x.notes||''}</textarea></label><input type="hidden" name="status" value="${x.status||'planning'}"><div class="modal-actions full">${x.id?'<button type="button" class="danger-btn" onclick="deleteCalendarEventEn()">Delete</button>':''}<span class="modal-spacer"></span><button type="button" class="ghost-btn" onclick="closeScheduleModalEn()">Cancel</button><button class="primary-btn">Save Item</button></div></form>`;}
window.openCalendarEventEn=(id='',date='')=>{const x=shootDaysEn.find(i=>String(i.id)===String(id))||{eventType:'other',date};showScheduleModalEn(x.id?'Edit Calendar Item':'New Calendar Item',calendarEventFormEn(x));setTimeout(()=>document.getElementById('calendarEventFormEn').onsubmit=saveCalendarEventEn,0);};async function saveCalendarEventEn(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.endTime<=d.startTime){alert('End time must be later than start time');return}let y=d.id?await SharedSchedules.update(d):await SharedSchedules.add(d);shootDaysEn=d.id?shootDaysEn.map(x=>String(x.id)===String(d.id)?y:x):[...shootDaysEn,y];closeScheduleModalEn();renderScheduleEn();}window.deleteCalendarEventEn=async()=>{const id=document.querySelector('#calendarEventFormEn [name=id]').value;if(confirm('Delete this calendar event?')){await SharedSchedules.remove(id);shootDaysEn=shootDaysEn.filter(x=>String(x.id)!==String(id));closeScheduleModalEn();renderScheduleEn();}};
function shootFormEn(x={}){return `<form id="shootDayFormEn" class="form-grid"><input type="hidden" name="id" value="${x.id||''}"><label><span>Shoot Date</span><input type="date" name="date" value="${x.date||''}" required></label><label><span>Status</span><select name="status">${Object.entries(shootStatusEn).map(([k,v])=>`<option value="${k}" ${x.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label><span>Call Time</span><input type="time" name="callTime" value="${x.callTime||''}"></label><label><span>Camera Start</span><input type="time" name="startTime" value="${x.startTime||''}"></label><label><span>Estimated Wrap</span><input type="time" name="endTime" value="${x.endTime||''}"></label><label><span>Owner</span><input name="owner" value="${x.owner||''}"></label><label class="full"><span>Location</span><input name="location" value="${x.location||''}" required></label><label class="full"><span>Episodes</span><input name="episodes" value="${x.episodes||''}" placeholder="e.g. EP01–EP04"></label><label class="full"><span>Cast</span><input name="cast" value="${x.cast||''}"></label><label class="full"><span>Crew</span><input name="crew" value="${x.crew||''}"></label><label class="full"><span>Detailed Timeline (one item per line)</span><textarea name="timeline" rows="8">${x.timeline||''}</textarea></label><label class="full"><span>Wardrobe & Props by Episode</span><textarea name="wardrobeProps" rows="6">${x.wardrobeProps||''}</textarea></label><label class="full"><span>Open Items</span><textarea name="issues" rows="3">${x.issues||''}</textarea></label><label class="full"><span>Location, Parking, Contact and Other Notes</span><textarea name="notes" rows="4">${x.notes||''}</textarea></label><div class="modal-actions full">${x.id?'<button type="button" class="danger-btn" onclick="deleteShootDayEn()">Delete</button>':''}<span class="modal-spacer"></span><button type="button" class="ghost-btn" onclick="closeScheduleModalEn()">Cancel</button><button class="primary-btn">Save Shoot Day</button></div></form>`;}
window.openShootDayEn=id=>{const x=shootDaysEn.find(i=>String(i.id)===String(id))||{};showScheduleModalEn(x.id?'Edit Shoot Day':'New Shoot Day',shootFormEn(x));setTimeout(()=>document.getElementById('shootDayFormEn').onsubmit=saveShootDayEn,0);};async function saveShootDayEn(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));let y=d.id?await SharedSchedules.update(d):await SharedSchedules.add(d);shootDaysEn=d.id?shootDaysEn.map(x=>String(x.id)===String(d.id)?y:x):[y,...shootDaysEn];closeScheduleModalEn();renderScheduleEn();}window.deleteShootDayEn=async()=>{const id=document.querySelector('#shootDayFormEn [name=id]').value;if(confirm('Delete this shoot day?')){await SharedSchedules.remove(id);shootDaysEn=shootDaysEn.filter(x=>String(x.id)!==String(id));closeScheduleModalEn();renderScheduleEn();}};
window.viewShootDayEn=id=>{const x=shootDaysEn.find(i=>String(i.id)===String(id));if(!x)return;showScheduleModalEn(`${x.date} · Daily Call Sheet`,`<div class="call-sheet"><div class="call-sheet-hero"><div><span>${shootStatusEn[x.status]}</span><h3>${x.location}</h3><p>${x.episodes}</p></div><div><small>Call Time</small><strong>${x.callTime||'—'}</strong><small>Estimated Wrap</small><strong>${x.endTime||'—'}</strong></div></div><div class="call-sheet-grid"><div><small>Owner</small><strong>${x.owner||'—'}</strong></div><div><small>Cast</small><strong>${x.cast||'—'}</strong></div><div><small>Crew</small><strong>${x.crew||'—'}</strong></div></div><h4>Daily Timeline</h4><div class="timeline-lines">${(x.timeline||'Not entered').split('\n').map(t=>`<p>${t}</p>`).join('')}</div><h4>Wardrobe & Props</h4><div class="call-sheet-text">${(x.wardrobeProps||'Not entered').replace(/\n/g,'<br>')}</div><h4>Open Items</h4><div class="${x.issues?'shoot-issue':'shoot-clear'}">${x.issues||'No open items'}</div><h4>On-set Notes</h4><div class="call-sheet-text">${(x.notes||'None').replace(/\n/g,'<br>')}</div><div class="modal-actions"><button class="ghost-btn" onclick="openShootDayEn('${x.id}')">Edit</button><button class="primary-btn" onclick="window.print()">Print / Save PDF</button></div></div>`);};function showScheduleModalEn(title,body){let m=document.getElementById('scheduleModalEn');if(!m){m=document.createElement('div');m.id='scheduleModalEn';m.className='modal';m.innerHTML='<div class="modal-card schedule-modal-card"><div class="modal-header"><h3 id="scheduleModalTitleEn"></h3><button class="icon-btn" onclick="closeScheduleModalEn()">×</button></div><div id="scheduleModalBodyEn"></div></div>';document.body.appendChild(m)}document.getElementById('scheduleModalTitleEn').textContent=title;document.getElementById('scheduleModalBodyEn').innerHTML=body;m.classList.add('open');}window.closeScheduleModalEn=()=>document.getElementById('scheduleModalEn')?.classList.remove('open');
