const navItems = [
  ["home","Home","⌂"],["positioning","Project Positioning","◎"],["world","Story World","◈"],["characters","Character Profiles","♙"],["relations","Character Relationships","⇄"],["season","Season 1: 30 Episodes","30"],["ideas","Story Topic Library","✦"],["episode","Episode Sheet","▤"],["scripts","Script Center","✎"],["production","Production Progress","▦"],["schedule","Shoot Schedule","◷"],["team","Team Members","♟"],["supporting","Supporting Characters","♧"],["singapore","Singapore Reference Library","SG"],["analytics","Publishing & Analytics","↗"],["brand","Brand Guidelines","◆"],["public","Internal & Public Sites","◉"]
];

const episodes = [
[1,"The Rich Student Rented the Smallest Room","Move-in Arc"],[2,"The Room Did Not Look Like This Online","Move-in Arc"],[3,"She Arrives with Eight Suitcases","Move-in Arc"],[4,"Why Does Someone Rich Rent Only One Room?","Move-in Arc"],[5,"The Landlord’s Twenty Rules","Move-in Arc"],[6,"Which Matters More: Deposit or Pride?","Move-in Arc"],
[7,"Why Can’t the Air-Conditioner Stay On?","Household Habits"],[8,"She Does Her Own Laundry for the First Time","Household Habits"],[9,"Who Left the Lights On Again?","Household Habits"],[10,"Whose Imported Food Is in the Fridge?","Household Habits"],[11,"She Wants to Hire Someone for Every Chore","Household Habits"],[12,"Can Durian Be Brought Home?","Household Habits"],[13,"A Rich Student Cleans the Toilet","Household Habits"],[14,"Must She Inform the Landlord Before Bringing Classmates Home?","Household Habits"],[15,"She Wants to Upgrade the Living Room","Household Habits"],
[16,"Using Tissue to Reserve a Seat","Singapore Culture"],[17,"Carrying Her Own Tray at a Hawker Centre","Singapore Culture"],[18,"Does ‘Can Can’ Mean Even More Possible?","Singapore Culture"],[19,"Missing the Bus Stop","Singapore Culture"],[20,"What Is Not Allowed on the MRT?","Singapore Culture"],[21,"How Should Rubbish Be Disposed Of?","Singapore Culture"],[22,"Fines That Money Cannot Avoid","Singapore Culture"],[23,"Why Does Nobody Panic When It Rains?","Singapore Culture"],
[24,"Joseph Films Her First Chore","Relationship Arc"],[25,"She Wants to Renovate Her Tiny Room","Relationship Arc"],[26,"James Shows a Client the Room She Hates","Relationship Arc"],[27,"She Solves a Problem Without Her Family","Relationship Arc"],[28,"The Toilet-Cleaning Video Goes Viral","Relationship Arc"],[29,"Her Parents Demand a Video Tour","Relationship Arc"],[30,"She Finally Admits That This Feels Like Home","Relationship Arc"]
];

const topicGroups = {
"Shared Living":["Rent","Deposit","Utilities","Air-Conditioning","Laundry","Cleaning the Bathroom","Cleaning","Noise","Bringing Friends Home","Fridge","Cooking","Deliveries","Pets","Daily Routine","Shared Areas"],
"Singapore Culture":["Chope","Singlish","Hawker Centre","Queueing","MC","HDB","Condo","MRT","Bus","ERP","COE","CPF","Singpass","National Day","Hawker Culture"],
"Newcomers from China":["Finding a Home","SIM Card","Opening a Bank Account","Seeing a Doctor","Finding a Job","Applying for a Pass","Transport","Shopping","Food","Schools","Tenancy Agreement","Agent","Weather","English Accent"],
"The Trio’s Relationships":["Arguments","Silent Treatment","Birthdays","Breakups","Job Loss","Illness","Borrowing Money","Misunderstandings","Secrets","Helping Each Other","New Friends","Family Visits"],
"Festivals & Trends":["Chinese New Year","National Day","Mid-Autumn Festival","Christmas","Hari Raya Puasa","Deepavali","Singles’ Day","Gaokao","Singapore General Election","Concerts","New Policies"]
};

const defaultIdeas = [
 {title:"The Air-Conditioner Remote Is Missing",category:"Shared Living",summary:"James limits air-conditioner use, but the remote disappears. It is eventually found hidden in the fridge by Joseph.",lead:"All Three",scene:"Living Room",status:"Idea Box"},
 {title:"Tissue Is Not Rubbish",category:"Singapore Culture",summary:"Joseph throws away tissue left on a table. Angeline returns to find that someone else has taken the reserved seat.",lead:"Joseph",scene:"Hawker Centre",status:"For Discussion"},
 {title:"Why Does Someone Rich Rent a Small Room?",category:"Chinese International Students",summary:"A visitor asks why Angeline rents only one tiny room. She insists that she is not broke—the wide-angle listing photos misled her—while James argues that the photos were technically accurate.",lead:"All Three",scene:"Living Room",status:"For Discussion"}
];

let state = {
  page: location.hash.replace('#','') || 'home',
  ideas: SharedIdeas.getLocal(defaultIdeas)
};

const nav = document.getElementById('nav');
const content = document.getElementById('content');
const pageTitle = document.getElementById('pageTitle');
const sidebar = document.getElementById('sidebar');

function badge(text, cls=''){ return `<span class="badge ${cls}">${text}</span>`; }
function card(title, body, extra=''){ return `<article class="card ${extra}"><h4>${title}</h4>${body}</article>`; }
function section(title, subtitle, body){ return `<section class="section"><div class="section-header"><div><h3>${title}</h3><p>${subtitle||''}</p></div></div>${body}</section>`; }

function renderNav(){
  nav.innerHTML = navItems.map(([id,label,icon])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');
  nav.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{ location.hash=btn.dataset.page; sidebar.classList.remove('open'); });
}

const pages = {
home(){
 return `<div class="hero"><p class="eyebrow">Season 1 · Internal HQ</p><h3>A newly arrived wealthy Chinese international student lives under one roof with a property-agent landlord and a tenant who works in social media advertising.</h3><p>James is the landlord and works in property. Angeline is a wealthy Chinese international student who has only just arrived in Singapore and has not fully adapted to local life. Joseph is a long-term tenant who works in social media marketing and advertising. Set mainly in James’s living room, the series combines culture shock, shared living, property, and content marketing.</p><div class="hero-actions"><button class="primary-btn" onclick="location.hash='season'">View Season 1</button><button class="ghost-btn" onclick="location.hash='characters'">View Characters</button><button class="ghost-btn" onclick="openIdeaModal()">Add Story Idea</button></div></div>
 ${section('Current Production Status','Season 1: The New Tenants Arrive',`<div class="grid grid-4">
 ${statCard('Planned Episodes','30','0%')}${statCard('Topics Confirmed','30','100%')}${statCard('Scripts Completed','0','0%')}${statCard('Filmed','0','0%')}
 </div>`)}
 ${section('Project Essentials','Four points every team member must understand first',`<div class="grid grid-2">${card('Project Overview','<p>James is a landlord and property professional. Angeline is a newly arrived wealthy Chinese international student. Joseph works in social media marketing and advertising. Angeline and Joseph rent rooms from James, and the three gradually move from awkward landlord–tenant relationships to a complicated friendship.</p>')}${card('Core Positioning','<div class="callout">Use light comedy to help Chinese audiences understand real Singapore life, culture, rules, and industry routines through a newly arrived Chinese student.</div>')}${card('Emotional Core','<p>They appear to annoy one another, but have effectively become a family. Comedy comes from conflict; long-term engagement comes from deepening relationships.</p>')}${card('Expansion','<p>The living room is the main early-stage set. Later, the world can expand to the kitchen, entrance, downstairs area, hawker centres, supermarkets, MRT stations, bus stops, and recurring supporting characters.</p>')}</div>`)}
 ${section('Quick Access','Open daily creative and production work',`<div class="grid grid-3">${quick('Character Profiles','Keep character traits, functions, and performance boundaries consistent','characters')}${quick('Story Topic Library','Store long-term topics and new ideas','ideas')}${quick('Production Progress','Track topics, scripts, filming, and post-production','production')}</div>`)}`;
},
positioning(){ return introPage('Project Positioning','This is not just a comedy account. It is an expandable short-drama IP.',[
 ['Project Name','Working title: Under One Roof. The title may change, but the story world and character relationships can be established now.'],
 ['One-line Introduction','A wealthy Chinese international student mistakenly signs for a room far smaller than it looked online, then moves in with a property-agent landlord and a social media advertising tenant.'],
 ['Target Audience','Chinese audiences interested in Singapore; people planning to move to Singapore; Chinese residents already in Singapore; local Singaporean Chinese; and viewers who enjoy light lifestyle comedy.'],
 ['Content Features','Authentic Singapore culture, international-student culture shock, shared living, property, social media marketing, campus life, client stories, light comedy, useful information, stable character relationships, and a continuing story world.']
], rules()); },
world(){ return introPage('Story World','The living room is only the stage; the character relationships are the real core.',[
 ['Story Background','James is the landlord and also works in property. Joseph is a long-term tenant who works in social media marketing, content production, and advertising. Angeline is a wealthy Chinese international student who has just arrived in Singapore. To prove that she can live independently, she rejects the luxury apartment arranged by her parents and signs a one-year tenancy after seeing only polished online photos. On arrival, she discovers that the room is far smaller than expected, but refuses to lose her deposit or admit to her family that she chose badly.'],
 ['Recurring Locations','Living room, sofa, dining table, kitchen, bedroom doors, front door, corridor, downstairs area, lift, nearby hawker centre, supermarket, and bus stop. Early episodes focus on James’s living room, with outdoor locations added later.'],
 ['Story-world Rules','James is the landlord and a property professional; Angeline is a wealthy Chinese international student and a new tenant; Joseph is a social media marketer, advertising professional, and long-term tenant; Angeline comes from a wealthy family but insists that she is living independently; her fixed reason for staying in the small room is that she trusted wide-angle photos, signed a one-year lease, refuses to lose the deposit, and will not admit the mistake to her parents; the three gradually become friends.'],
 ['Long-term Expansion','Future themes may include Singapore campus life, international-student routines, property, renting and buying homes, advertising, content creation, clients, friendship, romance, family, festivals, policy, and neighbours, while retaining the long-running joke that she is wealthy but trapped by her lease and pride.']
]); },
characters(){ return `${section('Core Characters','Keep their real professions, while heightening personality traits for comedy',`<div class="grid grid-3">${character('James','Landlord / Property Professional','J','avatar-james',['Rule-oriented','Rational','Protects property value','Understands clients','Appears annoyed but still helps'],'Views every situation through property value, rental return, client needs, and Singapore rules; introduces property, housing, and local-life storylines.',['Must not sell property in every episode','Must not only talk about rules','Must not treat clients as plot devices','Needs wrong judgments and moments when the tenants outsmart him'])}${character('Angeline','New Tenant / Wealthy Chinese International Student','A','avatar-angeline',['Wealthy background','Acts quickly','Pampered but not cruel','Uses money and efficiency to solve problems','Too proud to admit mistakes','Not yet integrated into Singapore'],'Represents newly arrived Chinese viewers. Her honest reactions to room size, house rules, Singlish, public transport, hawker centres, and campus culture drive the comedy. The central joke is that she is not short of money—she simply refuses to lose the deposit or admit that she chose badly.',['Must not only show off wealth','Must not look down on locals','Must not lack all common sense','Must not solve every episode with money','Must gradually become independent and adapt to Singapore'])}${character('Joseph','Tenant / Social Media Marketer','J','avatar-joseph',['Sensitive to attention','Always sees content opportunities','Understands advertising','Creative and unpredictable','Sometimes goes too far for results'],'Judges every event by whether it can be filmed, go viral, or justify ad spend; turns domestic conflict into content and creates new complications.',['Must not only hold a phone','Must not appear professionally incompetent','Should genuinely solve marketing problems','Needs failed predictions and reversals'])}</div>`)}
 ${section('Typical Reactions & Lines','Use these to maintain character consistency while writing',`<div class="grid grid-3">${card('James','<ul class="list"><li>“This will affect the property value.”</li><li>“A client is coming for a viewing.”</li><li>Calculates rent, return, and risk first</li><li>Still ends up cleaning up the tenants’ mess</li></ul>')}${card('Angeline','<ul class="list"><li>“I am not broke. The photos misled me.”</li><li>“How much would it cost to solve this?”</li><li>“Why is that not allowed in Singapore?”</li><li>Complains about the small room but refuses to admit she chose badly</li></ul>')}${card('Joseph','<ul class="list"><li>“Wait, do that again. I did not record it.”</li><li>“Let us test it with a small ad budget first.”</li><li>Judges every conflict by its content potential</li><li>Often makes situations more complicated for better footage</li></ul>')}</div>`)}`; },
relations(){ return `${section('Character Relationships','Recurring relationships determine how conflict works in each episode',`<div class="grid grid-2">${card('James × Angeline','<p><strong>Landlord Rules vs Wealthy Student</strong></p><p>James enforces the lease, deposit, and house rules. Angeline assumes money can solve most problems, yet refuses to waste her deposit or admit that the listing photos misled her.</p>')}${card('James × Joseph','<p><strong>Professional Viewings vs Content Traffic</strong></p><p>James needs an orderly client experience, while Joseph wants to film, create a hook, or test advertising performance.</p>')}${card('Angeline × Joseph','<p><strong>Privileged Student Life vs Content Traffic</strong></p><p>Joseph sees Angeline’s culture shock as perfect content. She dislikes being filmed without warning, yet still cares about whether she looks good on camera.</p>')}${card('The Trio','<div class="callout"><strong>They appear to annoy one another but have effectively become a family.</strong></div>')}</div>`)}
 ${section('Relationship Development Principles','Season 1 needs gradual relationship growth, not only standalone jokes',`<div class="timeline"><div class="timeline-item"><h4>Strangers Testing Boundaries</h4><p>At first, everyone protects themselves through rules and small schemes.</p></div><div class="timeline-item"><h4>Conflict and Dependence</h4><p>Their habits clash, but they begin helping one another.</p></div><div class="timeline-item"><h4>Becoming a Real Family</h4><p>Illness, moving out, and a new tenant make them realise how important they are to one another.</p></div></div>`)}`; },
season(){ const phases=['Move-in Arc','Living Habits Arc','Singapore Culture Arc','Relationship Arc']; return `${section('Season 1: The New Tenants Arrive','Thirty episodes form Season 1, focusing on moving in, adapting, and building relationships',`<div class="tabs">${phases.map((p,i)=>`<button class="tab-btn ${i===0?'active':''}" onclick="filterEpisodes('${p}',this)">${p}</button>`).join('')}<button class="tab-btn" onclick="filterEpisodes('All',this)">All</button></div><div id="episodeGrid" class="episode-grid">${renderEpisodes('Move-in Arc')}</div>`)}`; },
ideas(){ return `${section('Story Topic Library','Long-term topic categories beyond Season 1',`<div class="grid grid-3">${Object.entries(topicGroups).map(([k,v])=>card(k,`<div class="filters">${v.map(x=>badge(x)).join('')}</div>`)).join('')}</div>`)}${section('Team Idea Box','Entries use one shared dataset. After Cloudflare D1 is connected, all three members can see updates across devices.',`<div id="ideasTable">${ideasTable()}</div>`)}`; },
episode(){ return `${section('Episode SheetTemplate','Every episode should use the same fields',`<div class="table-wrap"><table><thead><tr><th>Field</th><th>Example</th></tr></thead><tbody>${[['Episode','EP01'],['Title','The Rich Student Rented the Smallest Room'],['Arc','Move-in Arc'],['Core Cultural Point','SingaporeHousing & Tenancy'],['Main Cast','James、Angeline、Joseph'],['Supporting Cast','None'],['Scene','Living Room'],['Duration','4–7 minutes'],['Story Status','Idea / Outline / Script / Filmed / Edited / Published'],['Writer','Name'],['Director','Name'],['Shoot Date','Date'],['Publication Date','Date'],['Platforms','Douyin / Xiaohongshu / WeChat Channels / YouTube'],['Props','Contract, Suitcases, Keys'],['Notes','Keep the wide-angle photos, one-year lease, deposit, and pride logic consistent']].map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td></tr>`).join('')}</tbody></table></div>`)}${section('Episode Structure','Every final script must include',`<div class="grid grid-3">${['Opening Hook: Establish the abnormal situation within 10–20 seconds','Act One Setup: Character goal, setting, stakes and starting conflict','Act Two Escalation: At least two failed attempts and a midpoint reversal','Act Three Climax: The three approaches collide and create a consequence','Relationship Beat: Reveal a weakness or change the trio’s relationship','Full Scene Dialogue: Organised by scene, action and character','Shot & Sound Plan: Coverage, reactions, blocking, subtitles and sound','Release Review: First-30-second retention, completion and next-episode conversion'].map((x,i)=>card(`0${i+1}`,`<p>${x}</p>`)).join('')}</div>`)}`; },
scripts(){ return ScriptManager.page('en'); },
production(){ return productionDashboardEn(); },
schedule(){ return `${section('Shoot Schedule','Film 4–8 episodes per session instead of scheduling one episode at a time',`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Time</th><th>Location</th><th>Episodes</th><th>Attendees</th><th>Wardrobe & Props</th><th>Status</th></tr></thead><tbody><tr><td>TBC</td><td>TBC</td><td>James’s Living Room</td><td>EP01–EP04</td><td>James / Angeline / Joseph</td><td>Keys, Suitcases, Tenancy Agreement</td><td>${badge('To Schedule','yellow')}</td></tr></tbody></table></div>`)}${section('Required Shoot Records','Prevent omissions',`<div class="grid grid-3">${['Date','Time','Location','Episodes','Cast Present','Crew','Required Wardrobe','Required Props','Estimated Completion Time','Outdoor Location Required','Reshoot Required'].map(x=>card(x,'<p>Updated by the producer or on-set lead.</p>')).join('')}</div>`)}`; },
team(){ return `${section('Core Team','Current permanent members',`<div class="grid grid-3">${teamCard('James','Landlord / Property Professional / Actor','Covers the landlord and property role, coordinates the location, and checks property and Singapore-living storylines')}${teamCard('Angeline','Actor / Project Lead','Plays a newly arrived wealthy Chinese international student; leads project direction, story development, market positioning, and the Chinese audience perspective')}${teamCard('Joseph','Tenant / Social Media Marketer / Actor','Covers social media, content production, advertising storylines, and the project’s distribution and marketing perspective')}</div>`)}${section('Future Team Roles','Create member profiles and permissions as the team expands',`<div class="grid grid-4">${['Cast','Writer','Director','Camera','Sound','Editor','Subtitles','Operations','Business','Props','Wardrobe','Producer'].map(x=>card(x,'<p>May be a permanent or project-based role.</p>')).join('')}</div>`)}${section('Member Profile Fields','Standardised records',`<div class="callout">Name, photo, role, contact details, join date, permanent-member status, responsibilities, viewing permission, editing permission, and administrator permission.</div>`)}`; },
supporting(){ return `${section('Supporting & Guest Characters','Supporting characters should recur and gradually build a complete universe',`<div class="grid grid-3">${['Next-door Neighbour','James’s Property Client','Buyer or Tenant','Partner Property Agent','Angeline’s Classmate','School Lecturer','Chinese Student Parent','Joseph’s Advertising Client','Content Creator','Platform Account Manager','New Tenant','Delivery Rider','Cleaner','ICA Officer','Hawker Stall Owner'].map(x=>card(x,'<p>Record characterisation, relationship to the main cast, first appearance, repeatable storylines, and actor details.</p>')).join('')}</div>`)}`; },
singapore(){ const cats=['Housing & Tenancy','Transport','Food','Work','Education','Laws & Fines','Festivals','Language','Social Customs','Government Services','Healthcare','Banking','Mobile & Internet']; return `${section('Singapore Reference Library','All cultural and policy information must be accurate and sourced',`<div class="grid grid-4">${cats.map(x=>card(x,'<p>Store the topic explanation, official source, last verification date, related episodes, and whether it has been used.</p>')).join('')}</div>`)}${section('Reference Entry Standard','Prevent inaccurate information from appearing in the series',`<div class="table-wrap"><table><thead><tr><th>Field</th><th>Requirement</th></tr></thead><tbody><tr><td>Topic</td><td>Define one filmable question</td></tr><tr><td>Plain-language Explanation</td><td>Explain it in audience-friendly language</td></tr><tr><td>Official Source</td><td>Prioritise government agencies, statutory boards, or official operators</td></tr><tr><td>Last Verified</td><td>Policies and fees must be kept current</td></tr><tr><td>Related Episodes</td><td>Identify where the information can be used</td></tr><tr><td>Used</td><td>Prevent duplication or support sequels</td></tr></tbody></table></div>`)}`; },
analytics(){ return `${section('Publishing & Analytics','Record every release consistently to identify what genuinely works',`<div class="grid grid-4">${['Views','First-30-second Retention','One-minute Retention','Average Watch Time','Completion Rate','Next-episode Conversion','New Followers','Top Comment'].map((x,i)=>statCard(x,'—','0%')).join('')}</div>`)}${section('Review Questions','Data should determine what to film next, not merely report past results',`<div class="grid grid-2">${card('Content Performance','<ul class="list"><li>Which Singapore cultural topics perform best?</li><li>Which conflicts are funniest?</li><li>Which topics deserve sequels?</li></ul>')}${card('Character Performance','<ul class="list"><li>Which character is most popular?</li><li>Which relationship does the audience prefer?</li><li>Which platform performs best?</li></ul>')}</div>`)}`; },
brand(){ return `${section('Brand & Visual Guidelines','Maintain consistency as the team grows',`<div class="grid grid-3">${['Logo','Chinese Name','English Name','Typography','Brand Colours','Opening','Closing','Subtitle Style','Thumbnail Template','Character Name Treatment','Music Guidelines','Logo Rules'].map(x=>card(x,'<p>Upload or complete the final standard after brand approval.</p>')).join('')}</div>`)}${section('Current Interim Guidelines','Visual direction used for Version 1',`<div class="grid grid-3">${card('Primary Colours','<p>Deep navy represents a stable story world; warm orange represents domestic conflict and comic rhythm.</p>')}${card('Visual Character','<p>Natural, modern, and clear, without a cheap or exaggerated variety-show look.</p>')}${card('Subtitle Principle','<p>For Chinese releases, use Chinese subtitles while retaining key Singlish or English terms with natural explanations.</p>')}</div>`)}`; },
public(){ return `${section('Site Structure','Build the internal site first and open a public site later',`<div class="grid grid-2">${card('Internal Site','<ul class="list"><li>Script</li><li>Shoot Schedule</li><li>Contact Details</li><li>Unreleased Content</li><li>Production Budget</li><li>Internal Discussions</li><li>Performance Data</li></ul>')}${card('Public Site','<ul class="list"><li>Project Introduction</li><li>Character Introduction</li><li>Published Episodes</li><li>Behind the Scenes</li><li>Collaboration</li><li>Casting</li><li>Brand Partnerships</li><li>Contact Details</li></ul>')}</div>`)}${section('Version 1 Completion Standard','Any new member must understand the following within 30 minutes',`<div class="callout">What the project is, whom they play or what they are responsible for, current progress, and the next action.</div>`)}`; }
};

const episodeHooksEn = [
'“This is my room? My wardrobe at home is bigger.”','Angeline opens her phone: “Where is the room from the photos?”','James goes silent when the eighth suitcase enters.','A guest asks the obvious question: “If you are rich, why do you live here?”','James unfolds a house-rule list that reaches the floor.','James says the deposit is non-refundable; Angeline instantly changes her position.',
'James finds the air-conditioner and the window open at the same time.','Angeline stares at the washing machine: “Which button calls the helper?”','James places the electricity bill on the table.','Joseph accidentally eats Angeline’s imported ingredients.','Angeline announces that every chore will be outsourced.','James smells durian and rushes into the living room.','The camera starts with Angeline in gloves outside the toilet.','James comes home to a living room full of unknown classmates.','Angeline opens a design plan: “This living room needs an upgrade.”',
'Angeline throws away a tissue packet that was reserving a seat.','Angeline stands with her tray: “Nobody brings it to the table?”','Angeline asks seriously: “Does can can mean even more can?”','The bus leaves before she realises she passed her stop.','She is about to drink when James and Joseph shout at once.','She stands in the corridor holding rubbish: “Where exactly does this go?”','James lists three things money still cannot let her do.','A storm begins; only Angeline panics and runs for an umbrella.',
'Joseph points the camera at her: “First time doing chores. Action.”','She wants to spend a small-room budget redesigning a small room.','James brings in a client while Angeline is insulting the room.','Her family stops answering, so she must solve the problem alone.','The video goes viral, but every comment asks whether she can clean a toilet.','Her parents call: “Show us where you are living.”','Angeline packs to leave, then realises she does not want to.'
];
function episodeDetailEn(ep){ const [num,title,phase]=ep; const hook=episodeHooksEn[num-1]; const isFirst=num===1; return {
 status:isFirst?'First Script Draft':'Story Outline',duration:'4–7 minutes',scene:num<=15?'James’s living room / bedroom entrance':'Living room + essential exterior',cast:'James, Angeline, Joseph',hook,
 five:`Within the first 30 seconds, establish the characters, the episode event and all three positions so the audience understands why the situation will keep escalating.`,
 goal:`Angeline tries to solve “${title}” in her own way while protecting her image as wealthy, independent, and never wrong.`,
 obstacle:`James insists on Singapore rules, tenancy logic, or property management; Joseph turns the conflict into a content opportunity and makes it worse.`,
 mid:`Act Two must contain at least two failed attempts. First make the problem appear easy to solve, then reveal that the real obstacle is a rule, pride, misunderstanding or the trio’s relationship.`,
 climax:`In Act Three, all three approaches collide in a complete climax, consequence and relationship shift. The reversal must pay off the title rather than end with only one joke.`,
 ending:`End on one short reversal and a comment question: who was actually more reasonable?`,
 culture:`Use only one genuine Singapore-life point connected to “${title}”. Verify any policy, fee, or legal claim before publishing.`,
 script:isFirst?[
 '【Shot 1 / Wide at entrance】Angeline enters with several suitcases and looks around.','Angeline: Where is my room?','James points to a small door: Here.','Angeline: I asked for my room, not the storeroom.','James: That is your room.','【Shot 2 / Phone close-up】Angeline compares the listing photos.','Angeline: It was much bigger in the photos.','James: The photos did not lie. It was a wide-angle lens.','Joseph raises his phone: That reaction was good. Say it again—I missed it.','Angeline: I want to cancel the lease.','James: Early termination means no deposit refund.','【Pause + three reaction shots】','Angeline: Actually… a smaller room feels safer.'
 ]:[`【Act One · Scene 1 / Opening】${hook}`,'【Act One · Scene 2】Establish the event of the day, the relationships and why this problem must be dealt with now.','【Act One · Scene 3】Angeline proposes a seemingly effective solution; James objects from a landlord or local-rules perspective; Joseph sees a content opportunity.','【Act One Turn】A new condition appears, preventing anyone from simply walking away.','【Act Two · Scene 4】First attempt: Angeline takes control but fails because of overconfidence or unfamiliarity with local life.','【Act Two · Scene 5】James takes over with the safe solution, which Angeline or Joseph disrupts.','【Act Two · Scene 6】Joseph intervenes for reach, advertising or footage. It appears to work briefly, then creates a larger consequence.','【Midpoint Reversal】They realise the real problem is not money but a rule, pride, misunderstanding or lack of trust.','【Act Two Back Half】The three blame one another. An older tension resurfaces and one character exposes a genuine weakness.','【Low Point】The plan fails completely and now affects the property, a client, school or their relationship.','【Act Three · Scene 7】They are forced to cooperate, with each character contributing a genuine strength.','【Climax】Pay off the episode title through action, dialogue and a relationship reversal—not only a punchline.','【Consequence】Resolve the main problem or leave a believable cost, showing what changed.','【Tag Scene】Return to normal life, then introduce a small new conflict or next-episode thread.','【End Gag】Add a 10–20 second character beat that can also be cut into a promotional clip.']
};}
window.openEpisodeDetail=(number)=>{ const ep=episodes.find(e=>e[0]===number);if(!ep)return;const d=episodeDetailEn(ep);
 document.getElementById('episodeModalTitle').textContent=`EP${String(ep[0]).padStart(2,'0')} · ${ep[1]}`;document.getElementById('episodeModalEyebrow').textContent='Episode Creative Workspace';
 document.getElementById('episodeModalBody').innerHTML=`<div class="episode-summary-grid">${[['Phase',ep[2]],['Status',d.status],['Target Length',d.duration],['Main Location',d.scene]].map(x=>`<div class="episode-summary-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>
 <div class="metric-strip"><div class="metric-box"><strong>Episode Length</strong><span>Target 4–7 minutes, allowing complete scenes and relationship development.</span></div><div class="metric-box"><strong>Three-act Structure</strong><span>Act One setup, Act Two escalation, Act Three climax and consequence.</span></div><div class="metric-box"><strong>Scene Count</strong><span>Use roughly 4–7 scenes; each must move plot or relationship forward.</span></div><div class="metric-box"><strong>Release Metrics</strong><span>First-30-second retention, average watch time, completion and next-episode conversion.</span></div></div>
 <div class="script-grid">${[['Title / Thumbnail Line',ep[1]],['Opening Hook / First 20 Seconds',d.hook],['Act One Setup / First 30 Seconds',d.five],['Character Goal',d.goal],['Obstacle & Escalation',d.obstacle],['Midpoint Turn',d.mid],['Climax / Final Twist',d.climax],['Ending Hook',d.ending],['Singapore Culture Point',d.culture]].map((x,i)=>`<div class="script-block ${i===8?'full':''}"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}<div class="script-block full"><h4>Full Script / Scene Dialogue</h4><ol class="script-lines">${d.script.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="script-block full"><h4>Post-release Data</h4><p>Platform, release date, final runtime, first-30-second retention, one-minute retention, average watch time, completion rate, next-episode conversion, like rate, comment rate, share rate, save rate, new followers, best comment, and next-episode improvement.</p></div></div>`;
 const m=document.getElementById('episodeModal');m.classList.add('open');m.setAttribute('aria-hidden','false');};
const episodeModal=document.getElementById('episodeModal');document.querySelectorAll('[data-close-episode-modal]').forEach(x=>x.onclick=()=>{episodeModal.classList.remove('open');episodeModal.setAttribute('aria-hidden','true');});

function statCard(label,num,percent){ return `<article class="card"><div class="stat"><div><div class="stat-label">${label}</div><div class="stat-number">${num}</div></div>${badge(percent)}</div><div class="progress"><span style="width:${percent}"></span></div></article>`; }
function quick(title,desc,page){ return `<article class="card"><h4>${title}</h4><p>${desc}</p><button class="ghost-btn" onclick="location.hash='${page}'">Open</button></article>`; }
function introPage(title,subtitle,items,extra=''){ return `${section(title,subtitle,`<div class="grid grid-2">${items.map(x=>card(x[0],`<p>${x[1]}</p>`)).join('')}</div>`)}${extra}`; }
function rules(){ const r=['Every episode needs a story, not just information','Every episode needs conflict; the trio cannot simply talk throughout','Each episode covers one core issue','Singapore information must be accurate','Do not demean any country or group','Comedy should come from character, not crude clowning','Commercial integration must not damage the story']; return section('ContentPrinciple','Mandatory creative rules',`<div class="grid grid-3">${r.map((x,i)=>card(`Principle ${i+1}`,`<p>${x}</p>`)).join('')}</div>`); }
function character(name,role,letter,avatar,traits,func,limits){ return `<article class="card character-card"><div class="character-avatar ${avatar}">${letter}</div><span class="badge">${role}</span><h4 style="font-size:22px;margin-top:10px">${name}</h4><p><strong>Core Traits</strong></p><div class="filters">${traits.map(x=>badge(x)).join('')}</div><p><strong>Story Function</strong></p><p>${func}</p><p><strong>Performance Boundaries</strong></p><ul class="list">${limits.map(x=>`<li>${x}</li>`).join('')}</ul></article>`; }
function renderEpisodes(filter){ return episodes.filter(e=>filter==='All'||e[2]===filter).map(e=>`<article class="episode" role="button" tabindex="0" onclick="openEpisodeDetail(${e[0]})" onkeydown="if(event.key==='Enter')openEpisodeDetail(${e[0]})"><div class="episode-num">EP${String(e[0]).padStart(2,'0')}</div><h4>${e[1]}</h4><p>${e[2]} · Open drama outline and scene script</p></article>`).join(''); }
window.filterEpisodes=(filter,btn)=>{ document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); document.getElementById('episodeGrid').innerHTML=renderEpisodes(filter); };
function ideasTable(){ if(!state.ideas.length) return '<div class="empty">No ideas yet</div>'; return `<div class="table-wrap"><table><thead><tr><th>Title</th><th>Category</th><th>One-line Story</th><th>Character</th><th>Scene</th><th>Status</th></tr></thead><tbody>${state.ideas.map(i=>`<tr><td><strong>${i.title}</strong></td><td>${i.category}</td><td>${i.summary}</td><td>${i.lead}</td><td>${i.scene}</td><td>${badge(SharedIdeas.statusLabel(i.statusCode || i.status, 'en'), (i.statusCode || i.status)==='discussion' || i.status==='For Discussion' ? 'yellow' : '')}</td></tr>`).join('')}</tbody></table></div>`; }
function kanban(cols){ return `<div class="kanban">${cols.map(([name,items])=>`<div class="kanban-col"><h4>${name}<span>${items.length}</span></h4>${items.map(i=>`<div class="kanban-item"><strong>${i}</strong><br><small>Awaiting owner update</small></div>`).join('')}</div>`).join('')}</div>`; }
function teamCard(name,title,desc){ return `<article class="card"><div class="character-avatar ${name==='James'?'avatar-james':name==='Angeline'?'avatar-angeline':'avatar-joseph'}">${name[0]}</div><h4>${name}</h4><span class="badge">${title}</span><p>${desc}</p></article>`; }

function render(){ if(!pages[state.page]) state.page='home'; renderNav(); pageTitle.textContent=navItems.find(x=>x[0]===state.page)?.[1]||'Home'; content.innerHTML=pages[state.page](); }
window.addEventListener('hashchange',()=>{ state.page=location.hash.replace('#','')||'home'; render(); window.scrollTo(0,0); });

document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');
const modal=document.getElementById('ideaModal');
window.openIdeaModal=()=>{ modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); };
document.getElementById('addIdeaBtn')?.addEventListener('click',openIdeaModal);
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>{ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); });
document.getElementById('ideaForm').onsubmit=async(e)=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(e.target)); const saved=await SharedIdeas.add({...d,statusCode:'idea'}); state.ideas.unshift(saved); e.target.reset(); modal.classList.remove('open'); if(state.page==='ideas') render(); };

SharedIdeas.load(defaultIdeas).then(ideas=>{ state.ideas=ideas; render(); });

const productionStagesEn=[
 {id:'outline',name:'Topic & Outline',color:'purple',episodes:[1,2,3,4,5,6]},
 {id:'writing',name:'Script Writing',color:'blue',episodes:[7,8,9,10,11]},
 {id:'locked',name:'Script Locked',color:'cyan',episodes:[12,13,14,15]},
 {id:'shoot',name:'Ready to Shoot',color:'yellow',episodes:[16,17,18,19]},
 {id:'filmed',name:'Filming Complete',color:'orange',episodes:[20,21,22]},
 {id:'post',name:'Post-production',color:'pink',episodes:[23,24,25]},
 {id:'publish',name:'Ready / Published',color:'green',episodes:[26,27,28,29,30]}
];
const productionMetaEn={};
Object.entries({1:['Angeline','High','2026-08-02','Props incomplete',72],2:['Joseph','Medium','2026-08-02','Outline approval pending',45],3:['Angeline','High','2026-08-02','Suitcase count unconfirmed',55],4:['James','Medium','2026-08-09','None',35],5:['James','High','2026-08-09','House rules list pending',30],6:['Angeline','High','2026-08-09','Deposit clause needs verification',40],7:['Joseph','Medium','2026-08-16','None',48],8:['Angeline','Medium','2026-08-16','Laundry scene pending',42],9:['James','Low','2026-08-16','None',38],10:['Angeline','Medium','2026-08-23','Imported-food props',40],11:['Joseph','Medium','2026-08-23','Service price verification',44],12:['James','Medium','2026-08-23','None',70],13:['Angeline','High','2026-08-30','Cleaning props',76],14:['Joseph','Medium','2026-08-30','Supporting cast unconfirmed',74],15:['James','Low','2026-08-30','Furniture plan pending',71],16:['Joseph','High','2026-09-06','Hawker-centre location',82],17:['Angeline','High','2026-09-06','Tray-return exterior',84],18:['James','Medium','2026-09-06','Singlish line review',80],19:['Angeline','Medium','2026-09-13','Bus exterior',79],20:['Joseph','High','2026-09-13','Backup confirmation',88],21:['James','Medium','2026-09-13','Pickup shot needed',86],22:['Angeline','High','2026-09-20','Fine claim verification',90],23:['Joseph','Medium','2026-09-20','Rough cut in progress',92],24:['Joseph','High','2026-09-20','Waiting for subtitles',94],25:['Angeline','Medium','2026-09-27','Room makeover footage',91],26:['James','High','2026-09-27','Thumbnail pending',96],27:['Angeline','High','2026-09-27','Release time unset',97],28:['Joseph','High','2026-10-04','Platform title pending',98],29:['Angeline','High','2026-10-04','Parent-call props',95],30:['All Three','High','2026-10-04','Final approval',99]}).forEach(([k,v])=>productionMetaEn[k]=v);
function productionCardEn(n){const ep=episodes.find(e=>e[0]===n),m=productionMetaEn[n],blocked=m[3]!=='None';return `<article class="prod-card ${blocked?'is-blocked':''}" onclick="openEpisodeDetail(${n})"><div class="prod-card-top"><span>EP${String(n).padStart(2,'0')}</span><span class="priority priority-${m[1].toLowerCase()}">${m[1]}</span></div><h4>${ep[1]}</h4><div class="prod-meta"><span>Owner: ${m[0]}</span><span>Shoot: ${m[2]}</span></div><div class="prod-progress"><i style="width:${m[4]}%"></i></div><div class="prod-card-bottom"><span>${m[4]}%</span><span class="${blocked?'blocker':'clear'}">${blocked?'⚠ '+m[3]:'✓ No blocker'}</span></div></article>`;}
function productionDashboardEn(){const total=episodes.length,locked=4,shoot=4,post=3,pub=5,blocked=Object.values(productionMetaEn).filter(x=>x[3]!=='None').length;return `${section('Production Overview','Each card represents one episode and moves right through the workflow',`<div class="production-toolbar"><div class="production-tabs"><button class="active" onclick="setProdViewEn('board',this)">Board</button><button onclick="setProdViewEn('list',this)">List</button><button onclick="setProdViewEn('calendar',this)">Shoot Calendar</button></div><div class="production-filters"><input id="prodSearchEn" placeholder="Search episode or title" oninput="filterProductionEn()"><select id="prodOwnerEn" onchange="filterProductionEn()"><option value="">All owners</option><option>Angeline</option><option>James</option><option>Joseph</option><option>All Three</option></select><select id="prodPriorityEn" onchange="filterProductionEn()"><option value="">All priorities</option><option>High</option><option>Medium</option><option>Low</option></select><label><input type="checkbox" id="prodBlockedEn" onchange="filterProductionEn()"> Blocked only</label></div></div><div class="prod-stats">${[['Total Episodes',total],['Scripts Locked',locked],['Ready to Shoot',shoot],['Post-production',post],['Ready / Published',pub],['Blocked',blocked]].map((x,i)=>`<div class="prod-stat s${i}"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div id="productionViewEn">${renderProdBoardEn()}</div>`)}`;}
function renderProdBoardEn(){return `<div class="episode-kanban">${productionStagesEn.map(st=>`<section class="episode-stage stage-${st.color}"><header><div><span class="stage-dot"></span><h4>${st.name}</h4></div><strong>${st.episodes.length}</strong></header><div class="stage-cards">${st.episodes.map(productionCardEn).join('')}</div></section>`).join('')}</div>`;}
function renderProdListEn(){return `<div class="table-wrap prod-table"><table><thead><tr><th>Episode</th><th>Title</th><th>Stage</th><th>Owner</th><th>Priority</th><th>Shoot Date</th><th>Progress</th><th>Blocker</th></tr></thead><tbody>${productionStagesEn.flatMap(st=>st.episodes.map(n=>{const ep=episodes.find(e=>e[0]===n),m=productionMetaEn[n];return `<tr onclick="openEpisodeDetail(${n})"><td>EP${String(n).padStart(2,'0')}</td><td><strong>${ep[1]}</strong></td><td><span class="stage-pill stage-${st.color}">${st.name}</span></td><td>${m[0]}</td><td>${m[1]}</td><td>${m[2]}</td><td>${m[4]}%</td><td>${m[3]}</td></tr>`;})).join('')}</tbody></table></div>`;}
function renderProdCalendarEn(){const by={};Object.entries(productionMetaEn).forEach(([n,m])=>{(by[m[2]]??=[]).push(+n)});return `<div class="shoot-calendar">${Object.keys(by).sort().map(d=>`<article><header><strong>${d}</strong><span>${by[d].length} episodes</span></header><div>${by[d].map(n=>{const ep=episodes.find(e=>e[0]===n);return `<button onclick="openEpisodeDetail(${n})"><b>EP${String(n).padStart(2,'0')}</b><span>${ep[1]}</span></button>`}).join('')}</div></article>`).join('')}</div>`;}
window.setProdViewEn=(v,btn)=>{document.querySelectorAll('.production-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('productionViewEn').innerHTML=v==='board'?renderProdBoardEn():v==='list'?renderProdListEn():renderProdCalendarEn();};
window.filterProductionEn=()=>{const q=(document.getElementById('prodSearchEn')?.value||'').toLowerCase(),owner=document.getElementById('prodOwnerEn')?.value||'',pri=document.getElementById('prodPriorityEn')?.value||'',blocked=document.getElementById('prodBlockedEn')?.checked;document.querySelectorAll('.prod-card').forEach(card=>{const n=+card.querySelector('.prod-card-top span').textContent.replace('EP',''),m=productionMetaEn[n],ep=episodes.find(e=>e[0]===n);card.style.display=((!q||ep[1].toLowerCase().includes(q)||String(n).includes(q))&&(!owner||m[0]===owner)&&(!pri||m[1]===pri)&&(!blocked||m[3]!=='None'))?'':'none';});};
