(function(){
const scenes=[
{n:1,title:'The Ultimatum',loc:'Living Room',time:'Night',runtime:'1:45',status:'Script locked',props:'Whiteboard + marker · two bowls of supper',shots:'MS whiteboard + Angeline · two-shot sofa reactions · CU two columns → title card',beat:'Angeline lays out the Singapore vs Kuala Lumpur numbers and gives the household two weeks to name one reason to stay. Food and safety do not count.',script:`ANGELINE: （敲白板）同样的工作。那边 partner 开的条件：赚头多百分之四十。Centre 租金，一半。住的地方，两倍大。\n(beat. She caps the marker.)\nANGELINE: 讲一个留下来的理由。\nJOSEPH: （立刻举手）Food——\nANGELINE: 不要讲 food。\n(Joseph's hand lowers slowly. Long silence. James opens his mouth—)\nANGELINE: 也不要讲“这里很安全”。安全是 base line，不是理由。\n(James closes his mouth.)\nANGELINE: （看表）国庆那天晚上，KL 那边要答案。你们有两个星期。\nJOSEPH: （小声）她是不是在跟我们 negotiate？\nJAMES: 不是。Negotiate 的人会给你 counter 的空间。这个是 ultimatum。`},
{n:2,title:'The Committee',loc:'Dining Table',time:'Day',runtime:'2:00',status:'Script locked',props:'TOP SECRET agenda · notebook · pen',shots:'WS dining table with empty chair · CU minutes · singles',beat:'James and Joseph launch Campaign Stay Lah with zero budget and selfish motives, then realise they need nobler reasons.',script:`JAMES: 今天的 agenda 只有一个：留住 Angeline。\nJOSEPH: 行动代号呢？每个 campaign 要有名字。\nJAMES: ……“Stay lah”。\nJOSEPH: “Campaign Stay Lah。” Budget 多少？\nJAMES: 零。\nJOSEPH: James，我做 marketing 十几年，zero budget 的 campaign 叫做“祝你好运”。\nJAMES: 我，房东，她走了我少一份租金。你——\nJOSEPH: 我不喜欢改变。还有 utilities 三个人 share 比较便宜。\nJAMES: ……这些理由不能讲出去。\nJOSEPH: 所以 campaign 第一条：我们需要比我们自己高尚的理由。\nJAMES: 对。这个叫 rebranding。`},
{n:3,title:'Rehearsal On TV',loc:'Living Room',time:'Day',runtime:'1:45',status:'Script locked',props:'Laptop · phone · earpiece',shots:'WS three people working · CU “free of charge” · follow-focus Angeline exit',beat:'National Day rehearsal plays while all three work overtime. Ideals on television clash with the reality in their hands.',script:`TV (V.O.): （国庆歌曲，隐约）\nJOSEPH: （对手机）没问题，第三次改，free of charge……对，final 这次。\n（挂断）他上次也是讲 final。\nJAMES: 这首歌的时候，我还相信我以后会有 landed。\nJOSEPH: 现在呢？\nJAMES: 现在我帮别人卖 landed。\nANGELINE: （对耳机走过）KL 的 campus 我要看 layout，还有 teacher pipeline——\nJOSEPH: 她连“看 layout”都讲到好像要赢。\nJAMES: 这种 tenant，你去哪里找。`},
{n:4,title:'Food Is Not Food',loc:'Open Kitchen',time:'Night',runtime:'2:00',status:'Script locked',props:'5–6 local dishes · fake client message',shots:'MS over counter · shot/reverse-shot · CU message → phone face-down',beat:'Joseph argues food is memory. A client message reveals he is being replaced by a cheaper vendor.',script:`JOSEPH: 我知道你讲不要讲 food。但是我要 argue：food 不是 food。\nANGELINE: Food 是 food。\nJOSEPH: Food 是记忆。你在 KL 吃到一样的 laksa，也不是这碗 laksa。\nANGELINE: KL 的 laksa 便宜三成。\nJOSEPH: 但是味道——\nANGELINE: 我做过 blind test 给我的学生。他们分不出。\nJOSEPH: 你对 food 做 blind test……\n(His phone buzzes: client is switching to a cheaper vendor. He puts it face-down.)\nANGELINE: ……这个 sambal 可以。\nJOSEPH: 我加了 belacan。`},
{n:5,title:'Pitching The Country',loc:'Dining',time:'Night',runtime:'2:30',status:'Script locked',props:'Flip chart · suit jacket + home shorts · marker',shots:'WS presentation with shorts visible · CU pages · slow push-in on final line',beat:'James presents Singapore as a property, flaws first, then gives the only selling point not written on the chart.',script:`JAMES: Angeline。今天我不是房东。我是 agent。我要 present 一个 property 给你。\nANGELINE: 你要 present 整个国家。\nJAMES: 对。先讲缺点。我做二十年 agent，先讲缺点的 agent，你才能信。\n（翻页：“小。贵。热。”）\nJAMES: 面积小。价钱贵。天气热。邻居 kiasu。养车是抢劫。讲完了。\nJOSEPH: 这个 pitch 开头很大胆。\nJAMES: Location：全世界的中间。治安：你半夜两点走路回家，想的是明天的事，不是后面的人。制度：慢，但是 predictable。\nJAMES: 还有一个 selling point，我没有写在 chart 上。\nANGELINE: 讲。\nJAMES: 我 present 过几百个 unit。每一个我都讲“很好住，相信我”。这个，是我唯一真的住过的。\nANGELINE: ……你 present 的时候，眼睛有光。\nJAMES: 谢谢。\nANGELINE: 但是光不能付 KL 的两倍薪水。\nJAMES: ……对。这个我 handle 不到。`},
{n:6,title:'Hanging The Flag',loc:'Corridor / Entry',time:'Day',runtime:'1:45',status:'Script locked',props:'National flag · fixtures',shots:'Symmetric corridor WS · CU flag · Joseph single',beat:'James reveals he hangs the flag even when living alone. Joseph remembers an office that moved to KL for cost.',script:`JAMES: 高一点。左边。旗不可以碰到地。\nJOSEPH: 你去年也是这样指挥的吗？\nJAMES: 每年都是。这个屋子挂了六年。你们来之前就挂。\nANGELINE: 你一个人住的时候，也挂？\nJAMES: 一个人住的时候，更加要挂。\nJOSEPH: 我以前 office 楼下每年挂到整条街都是。今年那个 office 没有了。搬去 KL 了。Cost。\nJOSEPH: ……但是他们 CEO 很后悔！听讲的。\nANGELINE: 听讲的。`},
{n:7,title:"James's Math",loc:'Dining',time:'Late Night',runtime:'2:15',status:'Script locked',props:'Laptop · water glass',shots:'Symmetric two-shot · CU James · end on laptop ignored',beat:'James admits he once calculated moving to Perth. The numbers won, but he stayed.',script:`JAMES: 还在算？\nANGELINE: 每天都在算。数字没有变。变的是我。今天想留，明天想走。\nJAMES: 我跟你讲一件事。你不要告诉 Joseph。二〇一九，我最差的一年。开单，四张。我算过 Perth。\nANGELINE: 算出来呢？\nJAMES: 那边的数字，赢。赢很多。\nANGELINE: 那你为什么还在这里？\nJAMES: 我发现每一个留下来的人，都不是没有算过。是算完，还是留下来。那个差别，就是理由。我讲不出它的名字，但是它在。\nANGELINE: 你这个答案，比你的 flip chart 好。\nJAMES: Flip chart 是给客户的。这个是给屋友的。`},
{n:8,title:'The List That Grows',loc:'Dining',time:'Day',runtime:'2:00',status:'Script locked',props:'Printed spreadsheet with handwritten rows · pen',shots:'Three-shot · CU Column B · Joseph single',beat:'The quantifiable column says leave; the unquantifiable column keeps growing on its own.',script:`ANGELINE: 我做了最后的 analysis。Column A：可以量化的。KL 全部赢。\nJOSEPH: Column B 是什么？\nANGELINE: “无法量化”。我妈的星期天晚餐。我教了三年的那批学生，明年考 O Level。楼下 mama shop 的 uncle 记得我不要葱。\nJAMES: 这一行是什么？“MRT 到站时间是准的”？\nANGELINE: 你去过别的国家等火车吗？\nJAMES: ……understood。\nANGELINE: 问题是这个 column，每天都变长。我删掉一行，它自己长两行。这个不是 analysis 的态度。\nJOSEPH: 当一个 list 自己会长的时候——那个不是 list。那个是答案在排队。`},
{n:9,title:'The Morning Of Aug 9',loc:'Open Kitchen',time:'Day',runtime:'1:30',status:'Script locked',props:'Toaster · kaya · eggs · kopi · phone',shots:'Continuous kitchen blocking · CU phone · CU burnt toast',beat:'KL calls for the final answer. Angeline says she will decide after the fireworks.',script:`ANGELINE: Hello。……对。今晚给你 final answer。对，今晚。烟花之后。\nANGELINE: 你们的 toast 要焦了。\nJOSEPH: 为什么要烟花之后？\nANGELINE: 做大决定，要在自己头脑最清楚的时候。\nJAMES: 烟花的时候头脑会清楚吗？\nANGELINE: 不会。所以要看它会不会骗到我。`},
{n:10,title:'Watching The Parade',loc:'Living Room',time:'Evening',runtime:'2:30',status:'Script locked',props:'Red/white outfits · flags · clapper · cheek sticker',shots:'Sofa three-shot · slow pan across faces · CU arms uncrossing',beat:'Deadpan commentary gives way to muscle memory during the anthem and pledge.',script:`JOSEPH: 来了来了，飞机来了！\nJAMES: 每一架的价钱我不敢想。\nANGELINE: 六架。一秒钟飞掉我 centre 十年的 revenue。\nJOSEPH: 你们两个看 airshow 的方式很不健康。\n(The anthem begins. All three straighten up. Joseph sings softly. Angeline's arms uncross.)\nJOSEPH: ……我还记得。\nJAMES: 小学念了六年，当然记得。\nANGELINE: 问题不是记不记得。是念的时候，心里有没有东西动一下。\nJOSEPH: ……有吗？\nANGELINE: 烟花之后讲。`},
{n:11,title:'After The Fireworks',loc:'Corridor / Window',time:'Night',runtime:'2:30',status:'Script locked',props:'Phone · clapper',shots:'Three backs WS · phone call side MS · final faces hold',beat:'Watching distant fireworks between blocks, Angeline declines the KL offer on her own terms.',script:`JOSEPH: 从这里看，好小。\nJAMES: 全国大部分人看到的都是这个 size。Marina Bay 那边的人看到大的。我们看到的，是自己家楼下的。\nANGELINE: （对电话）Hello。……我决定了。我不来了。\n(Joseph's clapper gives one involuntary clap. James elbows him.)\nANGELINE: 原因我讲给你听，因为你是生意人，你会明白。我的生意，是教外国学生看懂这个地方。如果我自己都走了——我卖的东西，我自己都不信。这种生意做不久的。\nANGELINE: 以后 KL 要开分校，我们再谈。用我的 terms。\nJAMES: 好的决定。完全理性。\nANGELINE: 还有一个原因我没跟他讲。\nJOSEPH: 什么？\nANGELINE: 我的房东会哭。\nJAMES: 我不会。`},
{n:12,title:'Tag · The Whiteboard',loc:'Living Room',time:'Night',runtime:'1:00',status:'Script locked',props:'Whiteboard with Scene 1 writing · marker',shots:'MS writing · two-shot · CU whiteboard → black',beat:'Angeline adds “屋檐 × 1（会升值）” to the Singapore column, then immediately negotiates a loyalty discount.',script:`(Angeline writes: “屋檐 × 1（会升值）”)\nJAMES: 这个是我的 IP。\nANGELINE: 你要收 royalty？\nJAMES: ……国庆促销。免费。\nANGELINE: 既然我留下来——renew 的时候，租金 discount。\nJAMES: 为什么？！\nANGELINE: 忠诚客户 retention program。你自己教我的：留住一个旧的，比找一个新的便宜。\nJAMES: 我教她的……\nJOSEPH (O.S.): 抽风机开五分钟！`}
];
const shorts=[['S1','“Don’t say food”','45s','Aug 6–7','Hook before full episode'],['S5','Pitching the whole country','60–90s','After episode','Strongest share clip'],['S7','“Everyone has done the math”','60s','After episode','Emotional resonance'],['S8','“Answers queueing up”','45s','After episode','Quotable clip'],['S10','Three reciting the pledge','60s','Aug 9','National Day release'],['S11','“My landlord will cry”','45s','After episode','Laugh-then-cry clip']];
function esc(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
function page(lang='zh'){
 const zh=lang==='zh';
 const labels=zh?{title:'特别篇制作项目',subtitle:'完整剧本、分场、制作资料、短视频拆条与发布排期统一管理',overview:'项目总览',scenes:'12场完整剧本',shorts:'短视频拆条',schedule:'制作倒计时',facts:'核实与风险',storyboard:'查看 Storyboard PPT',open:'展开剧本',close:'收起剧本'}:{title:'Special Production Project',subtitle:'One workspace for the full script, scene breakdown, production notes, shorts and release schedule',overview:'Project Overview',scenes:'12-Scene Full Script',shorts:'Shorts Plan',schedule:'Production Countdown',facts:'Fact Checks & Risks',storyboard:'Open Storyboard PPT',open:'Open Script',close:'Close Script'};
 return `<div class="special-project">
 <section class="special-hero"><div><p class="eyebrow">NATIONAL DAY SPECIAL · SG61</p><h2>《留下来的理由》 <span>A Reason to Stay</span></h2><p>${zh?'国庆特别篇 · 死板喜剧语气 · 问题到希望：表格说离开，无法量化的一栏说留下。':'National Day Special · Deadpan throughout · Problem to hope: the spreadsheet says leave, the unquantifiable column says stay.'}</p></div><a class="primary-btn" href="assets/nd-special-storyboard-deck.pptx" target="_blank" rel="noopener">${labels.storyboard}</a></section>
 <section class="special-kpis"><article><span>${zh?'目标时长':'Runtime'}</span><strong>19–22 min</strong></article><article><span>${zh?'场次':'Scenes'}</span><strong>12</strong></article><article><span>${zh?'主要地点':'Locations'}</span><strong>5</strong></article><article><span>${zh?'目标发布':'Release'}</span><strong>8–9 Aug</strong></article><article><span>${zh?'当前状态':'Status'}</span><strong>${zh?'剧本已锁定':'Script Locked'}</strong></article></section>
 <section class="special-grid"><article class="special-panel"><h3>${labels.overview}</h3><dl><dt>${zh?'核心议题':'Core topic'}</dt><dd>${zh?'几乎每个工作中的成年人都偷偷算过移民账：更高收入、更便宜住房、另一种生活。留下不是默认，而是每天重新做出的选择。':'The emigration math almost every working adult has done: better pay, cheaper housing, elsewhere. Staying is a choice, not a default.'}</dd><dt>${zh?'情绪主线':'Emotional spine'}</dt><dd>${zh?'表格说离开 → 无法量化的一栏说留下。没有宣传，也不犬儒。':'The spreadsheet says leave → the unquantifiable column says stay. No propaganda, no cynicism.'}</dd><dt>${zh?'拍摄铁律':'Iron rules'}</dt><dd>${zh?'全程冷面。镜头里没人哭，观众哭。整集只使用两次明显运镜。':'Deadpan throughout. Nobody cries on camera; the audience does. Only two deliberate camera moves.'}</dd></dl></article><article class="special-panel"><h3>${zh?'固定制作规则':'Standing Production Rules'}</h3><ul><li>${zh?'不拍卧室；地点只用客厅、饭厅、开放式厨房、入口/走廊、窗边。':'No bedroom scenes; use living room, dining, open kitchen, entry/corridor and window only.'}</li><li>${zh?'白板从第一场保留到第十二场，不能擦掉。':'The whiteboard carries through from Scene 1 to Scene 12; continuity is critical.'}</li><li>${zh?'电视画面虚焦或只保留声音，不直接翻拍NDP播出画面。':'Keep NDP footage soft-focus or audio-only; never re-film the broadcast directly.'}</li><li>${zh?'国旗必须状态良好、方向正确、不接触地面。':'Flag must be in good condition, correctly displayed and never touch the floor.'}</li></ul></article></section>
 <section class="special-section"><div class="special-head"><div><h3>${labels.scenes}</h3><p>${zh?'点击每一场查看对白与制作说明。':'Open each scene for dialogue and production notes.'}</p></div><span class="badge green">23.5 min raw</span></div><div class="scene-list">${scenes.map(s=>`<details class="scene-card"><summary><span class="scene-num">S${String(s.n).padStart(2,'0')}</span><span class="scene-main"><strong>${s.title}</strong><small>${s.loc} · ${s.time}</small></span><span class="scene-runtime">${s.runtime}</span><span class="badge green">${zh?'已锁定':'Locked'}</span></summary><div class="scene-body"><div class="scene-meta"><div><span>${zh?'剧情作用':'Story beat'}</span><p>${s.beat}</p></div><div><span>${zh?'镜头':'Shots'}</span><p>${s.shots}</p></div><div><span>${zh?'道具':'Props'}</span><p>${s.props}</p></div></div><pre>${esc(s.script)}</pre></div></details>`).join('')}</div></section>
 <section class="special-grid"><article class="special-panel"><h3>${labels.shorts}</h3><div class="shorts-list">${shorts.map(x=>`<div><b>${x[0]}</b><span><strong>${x[1]}</strong><small>${x[2]} · ${x[3]} · ${x[4]}</small></span></div>`).join('')}</div></article><article class="special-panel"><h3>${labels.schedule}</h3><div class="special-timeline"><div><b>27–29 Jul</b><span>${zh?'James围读、台词调整、锁定剧本':'James read-through, line adjustments, script lock'}</span></div><div><b>30–31 Jul</b><span>${zh?'美术、道具、假截图、服装准备':'Art, props, fake screenshots and wardrobe ready'}</span></div><div><b>1–2 Aug</b><span>${zh?'两天拍摄；白天场与夜间场分开':'Two-day shoot; day and night scenes grouped'}</span></div><div><b>3–6 Aug</b><span>${zh?'剪辑与中文字幕':'Edit and Chinese subtitles'}</span></div><div><b>7 Aug</b><span>${zh?'James审片；未批准不得发布':'James review gate; no release before approval'}</span></div><div><b>8–9 Aug</b><span>${zh?'正片发布；国庆当天发布宣誓短片':'Full release; pledge short on National Day'}</span></div></div></article></section>
 <section class="special-section"><div class="special-head"><div><h3>${labels.facts}</h3></div></div><div class="fact-grid"><article class="fact-ok"><b>✓</b><span>${zh?'40%、一半租金、两倍面积均为角色私人报价中的虚构数字，不作为市场数据。':'40%, half-rent and twice-the-space figures are fictional offer details, not market claims.'}</span></article><article class="fact-warn"><b>!</b><span>${zh?'拍摄前再次确认当前国旗展示指引。':'Reconfirm current flag-display guidance before filming.'}</span></article><article class="fact-warn"><b>!</b><span>${zh?'后期必须坚持NDP画面虚焦或仅声音处理。':'The edit must keep NDP broadcast footage soft-focus or audio-only.'}</span></article><article class="fact-ok"><b>✓</b><span>${zh?'战机和收入对比属于人物夸张对白，不是事实陈述。':'Jet and revenue comparisons are character hyperbole, not factual claims.'}</span></article></div></section>
 </div>`;
}
window.SharedSpecial={page};
})();
