(function(){
const API='/api/team'; let members=[]; let editing=null; let lang='zh';
const tx={
 zh:{title:'团队成员',sub:'管理固定成员、项目制成员、职责与权限；连接 D1 后所有人看到同一份资料。',add:'＋ 新增成员',core:'核心团队',others:'其他成员',empty:'暂无成员',edit:'编辑',active:'在组',inactive:'暂停',permanent:'固定成员',project:'项目制成员',guest:'客串／嘉宾',view:'仅查看',editp:'可编辑',admin:'管理员',contact:'联系方式',joined:'加入日期',resp:'主要职责',form:'成员资料',name:'姓名',roleZh:'中文职位',roleEn:'英文职位',respZh:'中文职责',respEn:'英文职责',type:'成员类型',status:'状态',perm:'系统权限',coreFlag:'核心成员',sort:'显示顺序',save:'保存成员',cancel:'取消',del:'删除',yes:'是',no:'否'},
 en:{title:'Team Members',sub:'Manage permanent and project-based members, responsibilities and permissions. With D1 connected, everyone sees the same records.',add:'+ Add Member',core:'Core Team',others:'Other Members',empty:'No members',edit:'Edit',active:'Active',inactive:'Inactive',permanent:'Permanent',project:'Project-based',guest:'Guest / Cameo',view:'View only',editp:'Can edit',admin:'Administrator',contact:'Contact',joined:'Join Date',resp:'Main Responsibilities',form:'Member Details',name:'Name',roleZh:'Chinese Role',roleEn:'English Role',respZh:'Chinese Responsibilities',respEn:'English Responsibilities',type:'Member Type',status:'Status',perm:'System Permission',coreFlag:'Core Member',sort:'Display Order',save:'Save Member',cancel:'Cancel',del:'Delete',yes:'Yes',no:'No'}
};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function labels(){return tx[lang];}
function role(m){return lang==='en'?(m.role_en||m.role_zh):(m.role_zh||m.role_en)}
function resp(m){return lang==='en'?(m.responsibilities_en||m.responsibilities_zh):(m.responsibilities_zh||m.responsibilities_en)}
function badgeType(v){const t=labels();return v==='project'?t.project:v==='guest'?t.guest:t.permanent}
function perm(v){const t=labels();return v==='admin'?t.admin:v==='edit'?t.editp:t.view}
function card(m){const t=labels();const initial=esc((m.name||'?').charAt(0).toUpperCase());return `<article class="member-card ${m.is_core?'core-member':''}"><div class="member-card-head"><div class="member-avatar">${initial}</div><div><h4>${esc(m.name)}</h4><p>${esc(role(m))}</p></div><button class="mini-btn" onclick="openTeamMember(${m.id})">${t.edit}</button></div><div class="member-tags"><span>${badgeType(m.member_type)}</span><span class="${m.status==='active'?'status-active':'status-inactive'}">${m.status==='active'?t.active:t.inactive}</span><span>${perm(m.permissions)}</span></div><p class="member-resp">${esc(resp(m)||'—')}</p><dl class="member-meta">${m.contact?`<div><dt>${t.contact}</dt><dd>${esc(m.contact)}</dd></div>`:''}${m.joined_at?`<div><dt>${t.joined}</dt><dd>${esc(m.joined_at)}</dd></div>`:''}</dl></article>`}
async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error('API');members=(await r.json()).members||[];}catch(e){members=JSON.parse(localStorage.getItem('uor_team')||'[]');} render();}
function render(){const root=document.getElementById('teamDynamic');if(!root)return;const t=labels();const core=members.filter(m=>Number(m.is_core)===1),other=members.filter(m=>Number(m.is_core)!==1);root.innerHTML=`<div class="team-head"><div><h3>${t.title}</h3><p>${t.sub}</p></div><button class="primary-btn" onclick="openTeamMember()">${t.add}</button></div>${group(t.core,core)}${group(t.others,other)}`;}
function group(title,list){const t=labels();return `<section class="team-group"><div class="team-group-title"><h3>${title}</h3><span>${list.length}</span></div><div class="member-grid">${list.length?list.map(card).join(''):`<div class="empty">${t.empty}</div>`}</div></section>`}
function modal(){let el=document.getElementById('teamModal');if(el)return el;el=document.createElement('div');el.id='teamModal';el.className='modal';document.body.appendChild(el);return el;}
window.openTeamMember=function(id){editing=members.find(x=>x.id===id)||null;const t=labels(),m=editing||{};const el=modal();el.innerHTML=`<div class="modal-card team-modal-card"><div class="modal-header"><h3>${t.form}</h3><button class="icon-btn" type="button" onclick="closeTeamMember()">×</button></div><form id="teamForm" class="form-grid"><label><span>${t.name}</span><input name="name" required value="${esc(m.name||'')}"></label><label><span>${t.contact}</span><input name="contact" value="${esc(m.contact||'')}"></label><label><span>${t.roleZh}</span><input name="role_zh" value="${esc(m.role_zh||'')}"></label><label><span>${t.roleEn}</span><input name="role_en" value="${esc(m.role_en||'')}"></label><label class="full"><span>${t.respZh}</span><textarea name="responsibilities_zh">${esc(m.responsibilities_zh||'')}</textarea></label><label class="full"><span>${t.respEn}</span><textarea name="responsibilities_en">${esc(m.responsibilities_en||'')}</textarea></label><label><span>${t.type}</span><select name="member_type"><option value="permanent" ${m.member_type==='permanent'?'selected':''}>${t.permanent}</option><option value="project" ${m.member_type==='project'?'selected':''}>${t.project}</option><option value="guest" ${m.member_type==='guest'?'selected':''}>${t.guest}</option></select></label><label><span>${t.status}</span><select name="status"><option value="active" ${m.status!=='inactive'?'selected':''}>${t.active}</option><option value="inactive" ${m.status==='inactive'?'selected':''}>${t.inactive}</option></select></label><label><span>${t.perm}</span><select name="permissions"><option value="view" ${m.permissions==='view'?'selected':''}>${t.view}</option><option value="edit" ${m.permissions==='edit'?'selected':''}>${t.editp}</option><option value="admin" ${m.permissions==='admin'?'selected':''}>${t.admin}</option></select></label><label><span>${t.joined}</span><input type="date" name="joined_at" value="${esc(m.joined_at||'')}"></label><label><span>${t.coreFlag}</span><select name="is_core"><option value="1" ${Number(m.is_core)===1?'selected':''}>${t.yes}</option><option value="0" ${Number(m.is_core)!==1?'selected':''}>${t.no}</option></select></label><label><span>${t.sort}</span><input type="number" name="sort_order" value="${Number(m.sort_order||0)}"></label><div class="modal-actions full">${editing?`<button type="button" class="danger-btn" onclick="deleteTeamMember()">${t.del}</button>`:''}<span class="modal-spacer"></span><button type="button" class="ghost-btn" onclick="closeTeamMember()">${t.cancel}</button><button class="primary-btn" type="submit">${t.save}</button></div></form></div>`;el.classList.add('open');el.setAttribute('aria-hidden','false');document.getElementById('teamForm').onsubmit=save;}
window.closeTeamMember=function(){const el=modal();el.classList.remove('open');el.setAttribute('aria-hidden','true')}
async function save(e){e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.is_core=b.is_core==='1';b.sort_order=Number(b.sort_order||0);if(editing)b.id=editing.id;try{const r=await fetch(API,{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});if(!r.ok)throw new Error('API');}catch(err){if(editing){members=members.map(x=>x.id===editing.id?{...x,...b}:x)}else{members.push({...b,id:Date.now()})}localStorage.setItem('uor_team',JSON.stringify(members));}closeTeamMember();load();}
window.deleteTeamMember=async function(){if(!editing)return;try{const r=await fetch(API+'?id='+editing.id,{method:'DELETE'});if(!r.ok)throw new Error('API');}catch(e){members=members.filter(x=>x.id!==editing.id);localStorage.setItem('uor_team',JSON.stringify(members));}closeTeamMember();load();}
window.teamPage=function(l){lang=l;setTimeout(load,0);return `<div id="teamDynamic"><div class="empty">Loading…</div></div>`}
window.initTeamSeed=async function(){if(members.length)return;}
})();
