(function(){
const API='/api/team'; let members=[]; let editing=null; let lang='zh';
const tx={
 zh:{title:'团队成员',sub:'管理固定成员、项目制成员、职责与权限；连接 D1 后所有人看到同一份资料。',add:'＋ 新增成员',core:'核心团队',others:'其他成员',recommended:'建议未来补充的岗位',recommendedSub:'这些是短剧团队常见但目前尚未加入的岗位。确认人选后，可直接添加为正式成员。',addRole:'添加此岗位',empty:'暂无成员',edit:'编辑',active:'在组',inactive:'暂停',permanent:'固定成员',project:'项目制成员',guest:'客串／嘉宾',view:'仅查看',editp:'可编辑',admin:'管理员',contact:'联系方式',joined:'加入日期',resp:'主要职责',form:'成员资料',name:'姓名',roleZh:'中文职位',roleEn:'英文职位',respZh:'中文职责',respEn:'英文职责',type:'成员类型',status:'状态',perm:'系统权限',coreFlag:'核心成员',sort:'显示顺序',save:'保存成员',cancel:'取消',del:'删除',yes:'是',no:'否'},
 en:{title:'Team Members',sub:'Manage permanent and project-based members, responsibilities and permissions. With D1 connected, everyone sees the same records.',add:'+ Add Member',core:'Core Team',others:'Other Members',recommended:'Recommended Future Roles',recommendedSub:'Common roles that may be added as the short-drama team grows. Once a person is confirmed, add them directly as a member.',addRole:'Add This Role',empty:'No members',edit:'Edit',active:'Active',inactive:'Inactive',permanent:'Permanent',project:'Project-based',guest:'Guest / Cameo',view:'View only',editp:'Can edit',admin:'Administrator',contact:'Contact',joined:'Join Date',resp:'Main Responsibilities',form:'Member Details',name:'Name',roleZh:'Chinese Role',roleEn:'English Role',respZh:'Chinese Responsibilities',respEn:'English Responsibilities',type:'Member Type',status:'Status',perm:'System Permission',coreFlag:'Core Member',sort:'Display Order',save:'Save Member',cancel:'Cancel',del:'Delete',yes:'Yes',no:'No'}
};

const recommendedRoles=[
 {icon:'演',icon_en:'A',role_zh:'演员',role_en:'Actor',responsibilities_zh:'出演固定角色、配角或客串人物；参与走戏、排练、拍摄与必要补拍。',responsibilities_en:'Perform as a recurring character, supporting role or guest; join rehearsals, filming and required reshoots.',member_type:'project',permissions:'view'},
 {icon:'编',icon_en:'W',role_zh:'编剧',role_en:'Writer',responsibilities_zh:'开发选题、三幕剧情、分场与完整台词，并维护人物设定和前后连贯性。',responsibilities_en:'Develop story ideas, three-act plots, scenes and full dialogue while maintaining character and continuity consistency.',member_type:'project',permissions:'edit'},
 {icon:'导',icon_en:'D',role_zh:'导演',role_en:'Director',responsibilities_zh:'统一表演、镜头、节奏和现场调度，确保每集达到既定喜剧与叙事效果。',responsibilities_en:'Lead performance, camera, pacing and set execution so each episode meets its intended comedy and story goals.',member_type:'project',permissions:'edit'},
 {icon:'摄',icon_en:'C',role_zh:'摄影／灯光',role_en:'Camera / Lighting',responsibilities_zh:'负责机位、构图、曝光、灯光和画面连续性，并管理拍摄设备。',responsibilities_en:'Handle camera positions, composition, exposure, lighting, visual continuity and filming equipment.',member_type:'project',permissions:'view'},
 {icon:'音',icon_en:'S',role_zh:'收音',role_en:'Sound Recordist',responsibilities_zh:'负责无线麦克风、环境声、录音监听和现场音质检查。',responsibilities_en:'Manage wireless microphones, ambience, audio monitoring and on-set sound quality checks.',member_type:'project',permissions:'view'},
 {icon:'剪',icon_en:'E',role_zh:'剪辑',role_en:'Editor',responsibilities_zh:'完成素材整理、粗剪、精剪、节奏控制、版本导出和修改记录。',responsibilities_en:'Organise footage, complete rough and final cuts, control pacing, export versions and track revisions.',member_type:'project',permissions:'edit'},
 {icon:'字',icon_en:'T',role_zh:'字幕／双语校对',role_en:'Subtitles / Bilingual Review',responsibilities_zh:'制作中英文字幕，校对专有名词、Singlish和新加坡文化信息。',responsibilities_en:'Create Chinese and English subtitles and verify terminology, Singlish and Singapore cultural references.',member_type:'project',permissions:'edit'},
 {icon:'制',icon_en:'P',role_zh:'制片／现场统筹',role_en:'Producer / Production Coordinator',responsibilities_zh:'管理拍摄日程、通告单、人员确认、预算、场地、餐饮和现场执行。',responsibilities_en:'Manage shoot schedules, call sheets, confirmations, budgets, locations, meals and on-set operations.',member_type:'permanent',permissions:'edit'},
 {icon:'道',icon_en:'R',role_zh:'道具／服装',role_en:'Props / Wardrobe',responsibilities_zh:'按集数准备、登记和恢复道具与服装，确保跨场景连续一致。',responsibilities_en:'Prepare, track and reset props and wardrobe by episode while maintaining continuity across scenes.',member_type:'project',permissions:'view'},
 {icon:'运',icon_en:'O',role_zh:'内容运营',role_en:'Content Operations',responsibilities_zh:'管理发布排期、标题、封面、平台上传、评论反馈和数据复盘。',responsibilities_en:'Manage release schedules, titles, thumbnails, platform uploads, audience feedback and performance reviews.',member_type:'permanent',permissions:'edit'},
 {icon:'商',icon_en:'B',role_zh:'商务合作',role_en:'Partnerships',responsibilities_zh:'负责品牌植入、合作洽谈、报价、合同和商业合作交付。',responsibilities_en:'Manage brand integrations, partnership discussions, pricing, contracts and commercial delivery.',member_type:'project',permissions:'view'},
 {icon:'妆',icon_en:'M',role_zh:'化妆／造型',role_en:'Makeup / Styling',responsibilities_zh:'管理角色妆发、造型和连续性照片，配合不同场景与拍摄日。',responsibilities_en:'Manage makeup, hair, styling and continuity photos across scenes and shoot days.',member_type:'project',permissions:'view'}
];

function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function labels(){return tx[lang];}
function role(m){return lang==='en'?(m.role_en||m.role_zh):(m.role_zh||m.role_en)}
function resp(m){return lang==='en'?(m.responsibilities_en||m.responsibilities_zh):(m.responsibilities_zh||m.responsibilities_en)}
function badgeType(v){const t=labels();return v==='project'?t.project:v==='guest'?t.guest:t.permanent}
function perm(v){const t=labels();return v==='admin'?t.admin:v==='edit'?t.editp:t.view}
function card(m){const t=labels();const initial=esc((m.name||'?').charAt(0).toUpperCase());return `<article class="member-card ${m.is_core?'core-member':''}"><div class="member-card-head"><div class="member-avatar">${initial}</div><div><h4>${esc(m.name)}</h4><p>${esc(role(m))}</p></div><button class="mini-btn" onclick="openTeamMember(${m.id})">${t.edit}</button></div><div class="member-tags"><span>${badgeType(m.member_type)}</span><span class="${m.status==='active'?'status-active':'status-inactive'}">${m.status==='active'?t.active:t.inactive}</span><span>${perm(m.permissions)}</span></div><p class="member-resp">${esc(resp(m)||'—')}</p><dl class="member-meta">${m.contact?`<div><dt>${t.contact}</dt><dd>${esc(m.contact)}</dd></div>`:''}${m.joined_at?`<div><dt>${t.joined}</dt><dd>${esc(m.joined_at)}</dd></div>`:''}</dl></article>`}
async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error('API');members=(await r.json()).members||[];}catch(e){members=JSON.parse(localStorage.getItem('uor_team')||'[]');} render();}
function render(){const root=document.getElementById('teamDynamic');if(!root)return;const t=labels();const core=members.filter(m=>Number(m.is_core)===1),other=members.filter(m=>Number(m.is_core)!==1);root.innerHTML=`<div class="team-head"><div><h3>${t.title}</h3><p>${t.sub}</p></div><button class="primary-btn" onclick="openTeamMember()">${t.add}</button></div>${group(t.core,core)}${group(t.others,other)}${recommendedSection()}`;}
function group(title,list){const t=labels();return `<section class="team-group"><div class="team-group-title"><h3>${title}</h3><span>${list.length}</span></div><div class="member-grid">${list.length?list.map(card).join(''):`<div class="empty">${t.empty}</div>`}</div></section>`}
function recommendedSection(){const t=labels();return `<section class="team-group recommended-group"><div class="team-group-title recommended-title"><div><h3>${t.recommended}</h3><p>${t.recommendedSub}</p></div><span>${recommendedRoles.length}</span></div><div class="recommended-grid">${recommendedRoles.map((r,i)=>`<article class="recommended-role role-${i%6}"><div class="recommended-icon ${lang==='en'?'recommended-icon-en':''}">${lang==='en'?(r.icon_en||r.icon):r.icon}</div><div class="recommended-copy"><h4>${esc(lang==='en'?r.role_en:r.role_zh)}</h4><p>${esc(lang==='en'?r.responsibilities_en:r.responsibilities_zh)}</p></div><button class="role-add-btn" onclick="openRecommendedRole(${i})">＋ ${t.addRole}</button></article>`).join('')}</div></section>`}
window.openRecommendedRole=function(i){const r=recommendedRoles[i];if(!r)return;openTeamMember(null,r)}
function modal(){let el=document.getElementById('teamModal');if(el)return el;el=document.createElement('div');el.id='teamModal';el.className='modal';document.body.appendChild(el);return el;}
window.openTeamMember=function(id,preset){editing=members.find(x=>x.id===id)||null;const t=labels(),m=editing||preset||{};const el=modal();el.innerHTML=`<div class="modal-card team-modal-card"><div class="modal-header"><h3>${t.form}</h3><button class="icon-btn" type="button" onclick="closeTeamMember()">×</button></div><form id="teamForm" class="form-grid"><label><span>${t.name}</span><input name="name" required value="${esc(m.name||'')}"></label><label><span>${t.contact}</span><input name="contact" value="${esc(m.contact||'')}"></label><label><span>${t.roleZh}</span><input name="role_zh" value="${esc(m.role_zh||'')}"></label><label><span>${t.roleEn}</span><input name="role_en" value="${esc(m.role_en||'')}"></label><label class="full"><span>${t.respZh}</span><textarea name="responsibilities_zh">${esc(m.responsibilities_zh||'')}</textarea></label><label class="full"><span>${t.respEn}</span><textarea name="responsibilities_en">${esc(m.responsibilities_en||'')}</textarea></label><label><span>${t.type}</span><select name="member_type"><option value="permanent" ${m.member_type==='permanent'?'selected':''}>${t.permanent}</option><option value="project" ${m.member_type==='project'?'selected':''}>${t.project}</option><option value="guest" ${m.member_type==='guest'?'selected':''}>${t.guest}</option></select></label><label><span>${t.status}</span><select name="status"><option value="active" ${m.status!=='inactive'?'selected':''}>${t.active}</option><option value="inactive" ${m.status==='inactive'?'selected':''}>${t.inactive}</option></select></label><label><span>${t.perm}</span><select name="permissions"><option value="view" ${m.permissions==='view'?'selected':''}>${t.view}</option><option value="edit" ${m.permissions==='edit'?'selected':''}>${t.editp}</option><option value="admin" ${m.permissions==='admin'?'selected':''}>${t.admin}</option></select></label><label><span>${t.joined}</span><input type="date" name="joined_at" value="${esc(m.joined_at||'')}"></label><label><span>${t.coreFlag}</span><select name="is_core"><option value="1" ${Number(m.is_core)===1?'selected':''}>${t.yes}</option><option value="0" ${Number(m.is_core)!==1?'selected':''}>${t.no}</option></select></label><label><span>${t.sort}</span><input type="number" name="sort_order" value="${Number(m.sort_order||0)}"></label><div class="modal-actions full">${editing?`<button type="button" class="danger-btn" onclick="deleteTeamMember()">${t.del}</button>`:''}<span class="modal-spacer"></span><button type="button" class="ghost-btn" onclick="closeTeamMember()">${t.cancel}</button><button class="primary-btn" type="submit">${t.save}</button></div></form></div>`;el.classList.add('open');el.setAttribute('aria-hidden','false');document.getElementById('teamForm').onsubmit=save;}
window.closeTeamMember=function(){const el=modal();el.classList.remove('open');el.setAttribute('aria-hidden','true')}
async function save(e){e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.is_core=b.is_core==='1';b.sort_order=Number(b.sort_order||0);if(editing)b.id=editing.id;try{const r=await fetch(API,{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});if(!r.ok)throw new Error('API');}catch(err){if(editing){members=members.map(x=>x.id===editing.id?{...x,...b}:x)}else{members.push({...b,id:Date.now()})}localStorage.setItem('uor_team',JSON.stringify(members));}closeTeamMember();load();}
window.deleteTeamMember=async function(){if(!editing)return;try{const r=await fetch(API+'?id='+editing.id,{method:'DELETE'});if(!r.ok)throw new Error('API');}catch(e){members=members.filter(x=>x.id!==editing.id);localStorage.setItem('uor_team',JSON.stringify(members));}closeTeamMember();load();}
window.teamPage=function(l){lang=l;setTimeout(load,0);return `<div id="teamDynamic"><div class="empty">Loading…</div></div>`}
window.initTeamSeed=async function(){if(members.length)return;}
})();
