const ScriptManager = (() => {
  const KEY = 'roofScriptsSharedV1';
  const defaults = [
    {id:'demo-1',title:'空调遥控器失踪了',titleEn:'The Air-Conditioner Remote Is Missing',statusCode:'idea',owner:'',version:'v0.1',summary:'James 限制空调时长，遥控器却突然不见。',summaryEn:'James limits air-conditioner use, but the remote suddenly disappears.',updatedAt:new Date().toISOString()},
    {id:'demo-2',title:'新加坡为什么到处排队',titleEn:'Why Singaporeans Queue Everywhere',statusCode:'idea',owner:'',version:'v0.1',summary:'三个人对排队文化产生不同理解。',summaryEn:'The trio interpret Singapore queue culture differently.',updatedAt:new Date().toISOString()},
    {id:'demo-3',title:'纸巾不是垃圾',titleEn:'Tissue Is Not Rubbish',statusCode:'discussion',owner:'',version:'v0.1',summary:'Joseph 把占座纸巾当垃圾丢掉。',summaryEn:'Joseph throws away a tissue being used to reserve a seat.',updatedAt:new Date().toISOString()},
    {id:'demo-4',title:'谁睡最大间',titleEn:'Who Gets the Largest Room',statusCode:'discussion',owner:'',version:'v0.1',summary:'三个人争论房间分配。',summaryEn:'The trio argue over room allocation.',updatedAt:new Date().toISOString()},
    {id:'demo-5',title:'富二代租了最小的房间',titleEn:'The Wealthy Student Rents the Smallest Room',statusCode:'writing',owner:'Angeline',version:'v0.2',summary:'第一集正在编写。',summaryEn:'Episode 1 is being written.',updatedAt:new Date().toISOString()}
  ];
  let items=[]; let lang='zh';
  const labels={zh:{title:'剧本中心',sub:'在这里新增、编辑和移动剧本；连接 Cloudflare D1 后三个人会看到同一份内容。',add:'＋ 新建剧本',empty:'暂无剧本',edit:'编辑',owner:'负责人',version:'版本',updated:'更新',save:'保存剧本',cancel:'取消',delete:'删除',formTitle:'剧本资料',name:'标题',summary:'剧情简介／备注',status:'状态',statuses:{idea:'灵感箱',discussion:'待讨论',writing:'编写中',final:'最终版'}},en:{title:'Script Center',sub:'Add, edit and move scripts here. With Cloudflare D1 connected, all three team members see the same content.',add:'+ New Script',empty:'No scripts',edit:'Edit',owner:'Owner',version:'Version',updated:'Updated',save:'Save Script',cancel:'Cancel',delete:'Delete',formTitle:'Script Details',name:'Title',summary:'Story Summary / Notes',status:'Status',statuses:{idea:'Idea Box',discussion:'For Discussion',writing:'Writing',final:'Final'}}};
  function getLocal(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||defaults}catch{return defaults}}
  function setLocal(v){localStorage.setItem(KEY,JSON.stringify(v))}
  async function load(){try{const r=await fetch('/api/scripts');if(!r.ok)throw 0;const d=await r.json();items=d.scripts?.length?d.scripts:getLocal()}catch{items=getLocal()} setLocal(items); renderBoard();}
  function page(language){lang=language;const t=labels[lang];setTimeout(()=>init(),0);return `<section class="section script-center-section"><div class="section-header script-center-header"><div><h3>${t.title}</h3><p>${t.sub}</p></div><button class="primary-btn" id="newScriptBtn">${t.add}</button></div><div id="scriptBoard" class="script-kanban"></div></section>`}
  function init(){document.getElementById('newScriptBtn')?.addEventListener('click',()=>open());load()}
  function renderBoard(){const mount=document.getElementById('scriptBoard');if(!mount)return;const t=labels[lang];const order=['idea','discussion','writing','final'];mount.innerHTML=order.map((code,i)=>{const group=items.filter(x=>x.statusCode===code);return `<div class="script-column status-${code}"><div class="script-column-head"><div><span class="status-dot-lg"></span><h4>${t.statuses[code]}</h4></div><span class="script-count">${group.length}</span></div><div class="script-card-list">${group.length?group.map(x=>card(x)).join(''):`<div class="script-empty">${t.empty}</div>`}</div></div>`}).join('');mount.querySelectorAll('[data-script-id]').forEach(el=>el.onclick=()=>open(items.find(x=>String(x.id)===el.dataset.scriptId)))}
  function card(x){const t=labels[lang];const title=lang==='en'?(x.titleEn||x.title):(x.title||x.titleEn);const summary=lang==='en'?(x.summaryEn||x.summary):(x.summary||x.summaryEn);return `<button class="script-card" data-script-id="${x.id}"><div class="script-card-top"><strong>${escapeHtml(title)}</strong><span>→</span></div>${summary?`<p>${escapeHtml(summary)}</p>`:''}<div class="script-meta"><span>${t.version}: ${escapeHtml(x.version||'v0.1')}</span><span>${t.owner}: ${escapeHtml(x.owner||'—')}</span></div></button>`}
  function open(x={}){const t=labels[lang];const modal=document.getElementById('scriptEditModal');modal.dataset.id=x.id||'';document.getElementById('scriptEditTitle').textContent=t.formTitle;document.getElementById('scriptTitleLabel').textContent=t.name;document.getElementById('scriptSummaryLabel').textContent=t.summary;document.getElementById('scriptStatusLabel').textContent=t.status;document.getElementById('scriptOwnerLabel').textContent=t.owner;document.getElementById('scriptVersionLabel').textContent=t.version;document.getElementById('scriptSaveBtn').textContent=t.save;document.getElementById('scriptCancelBtn').textContent=t.cancel;document.getElementById('scriptDeleteBtn').textContent=t.delete;document.getElementById('scriptDeleteBtn').style.display=x.id?'inline-flex':'none';document.getElementById('scriptTitleInput').value=lang==='en'?(x.titleEn||x.title||''):(x.title||x.titleEn||'');document.getElementById('scriptSummaryInput').value=lang==='en'?(x.summaryEn||x.summary||''):(x.summary||x.summaryEn||'');document.getElementById('scriptOwnerInput').value=x.owner||'';document.getElementById('scriptVersionInput').value=x.version||'v0.1';document.getElementById('scriptStatusInput').innerHTML=Object.entries(t.statuses).map(([k,v])=>`<option value="${k}" ${x.statusCode===k?'selected':''}>${v}</option>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
  async function save(e){e.preventDefault();const modal=document.getElementById('scriptEditModal');const old=items.find(x=>String(x.id)===modal.dataset.id)||{};const title=document.getElementById('scriptTitleInput').value.trim();const summary=document.getElementById('scriptSummaryInput').value.trim();const payload={...old,statusCode:document.getElementById('scriptStatusInput').value,owner:document.getElementById('scriptOwnerInput').value.trim(),version:document.getElementById('scriptVersionInput').value.trim()||'v0.1'};if(lang==='en'){payload.titleEn=title;payload.summaryEn=summary;payload.title=payload.title||title;payload.summary=payload.summary||summary}else{payload.title=title;payload.summary=summary;payload.titleEn=payload.titleEn||title;payload.summaryEn=payload.summaryEn||summary}try{const r=await fetch('/api/scripts',{method:old.id&&!String(old.id).startsWith('demo-')?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw 0;const d=await r.json();const saved=d.script;items=[saved,...items.filter(x=>String(x.id)!==String(old.id))]}catch{const saved={...payload,id:old.id||`local-${Date.now()}`,updatedAt:new Date().toISOString()};items=[saved,...items.filter(x=>String(x.id)!==String(old.id))]}setLocal(items);close();renderBoard()}
  async function remove(){const modal=document.getElementById('scriptEditModal');const id=modal.dataset.id;if(!id)return;try{if(!String(id).startsWith('demo-')&&!String(id).startsWith('local-'))await fetch(`/api/scripts?id=${encodeURIComponent(id)}`,{method:'DELETE'})}catch{}items=items.filter(x=>String(x.id)!==String(id));setLocal(items);close();renderBoard()}
  function close(){const m=document.getElementById('scriptEditModal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
  function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('scriptEditForm')?.addEventListener('submit',save);document.getElementById('scriptCancelBtn')?.addEventListener('click',close);document.getElementById('scriptDeleteBtn')?.addEventListener('click',remove);document.querySelectorAll('[data-close-script-modal]').forEach(x=>x.addEventListener('click',close))});
  return {page};
})();
