import { json, ensureColumn, logAudit, requireId } from '../_lib/db.js';
async function ensure(db){
 await db.prepare(`CREATE TABLE IF NOT EXISTS availability (id INTEGER PRIMARY KEY AUTOINCREMENT,member TEXT NOT NULL DEFAULT '',availability_date TEXT NOT NULL DEFAULT '',day_of_week INTEGER NOT NULL DEFAULT 1,start_time TEXT NOT NULL DEFAULT '',end_time TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',deleted_at TEXT)`).run();
 await ensureColumn(db,'availability','availability_date',"TEXT NOT NULL DEFAULT ''");
 await ensureColumn(db,'availability','deleted_at','TEXT');
 await db.prepare('CREATE INDEX IF NOT EXISTS idx_availability_date ON availability(availability_date,start_time)').run();
}
const clean=b=>({availabilityDate:String(b.availabilityDate||''),member:['Angeline','James','Joseph'].includes(String(b.member))?String(b.member):'Angeline',dayOfWeek:Math.max(1,Math.min(7,Number(b.dayOfWeek)||1)),startTime:String(b.startTime||''),endTime:String(b.endTime||''),note:String(b.note||'')});
const cols='id,availability_date AS availabilityDate,member,day_of_week AS dayOfWeek,start_time AS startTime,end_time AS endTime,note';
export async function onRequestGet({env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const {results}=await env.DB.prepare(`SELECT ${cols} FROM availability WHERE deleted_at IS NULL ORDER BY availability_date,start_time,member`).all();return json({availability:results||[]})}
export async function onRequestPost({request,env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);let b;try{b=clean(await request.json())}catch{return json({error:'Invalid JSON'},400)}if(!b.availabilityDate||!b.startTime||!b.endTime||b.endTime<=b.startTime)return json({error:'Valid time range required'},400);const r=await env.DB.prepare('INSERT INTO availability(availability_date,member,day_of_week,start_time,end_time,note) VALUES(?,?,?,?,?,?)').bind(b.availabilityDate,b.member,b.dayOfWeek,b.startTime,b.endTime,b.note).run();const id=r.meta.last_row_id;await logAudit(env.DB,'availability',id,'create',b);return json({availability:{id,...b}},201)}
export async function onRequestPut({request,env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);let raw;try{raw=await request.json()}catch{return json({error:'Invalid JSON'},400)}const id=Number(raw.id);if(!id)return json({error:'Valid id required'},400);const b=clean(raw);if(!b.availabilityDate||!b.startTime||!b.endTime||b.endTime<=b.startTime)return json({error:'Valid time range required'},400);await env.DB.prepare('UPDATE availability SET availability_date=?,member=?,day_of_week=?,start_time=?,end_time=?,note=? WHERE id=? AND deleted_at IS NULL').bind(b.availabilityDate,b.member,b.dayOfWeek,b.startTime,b.endTime,b.note,id).run();await logAudit(env.DB,'availability',id,'update',b);return json({availability:{id,...b}})}
export async function onRequestDelete({request,env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const id=requireId(request);if(!id)return json({error:'Valid id required'},400);await env.DB.prepare('UPDATE availability SET deleted_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL').bind(id).run();await logAudit(env.DB,'availability',id,'soft_delete');return json({ok:true,id})}
