const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const titlesZh=['富二代租了最小的房间','照片里明明不是这样','她带了八个行李箱','有钱为什么不租整套房','房东的二十条规则','押金和面子到底哪个重要','空调为什么不能一直开','她第一次自己洗衣服','谁又没有关灯','冰箱里的东西是谁的','在家里煮火锅','榴梿可以带回家吗','富二代第一次洗厕所','带同学回家要不要通知','客厅到底是谁的','用纸巾占座','第一次自己端小贩中心餐盘','Can Can 是不是更可以','第一次坐巴士坐过站','MRT里面不能做什么','垃圾到底怎么丢','有钱也不能避开的罚款','新加坡为什么说下雨就下雨','她想搬走却舍不得押金','Angeline想把客厅变成私人会所','James带买家来看房','Joseph把看房拍成广告','家里打来视频查岗','新租客来看房','到底谁才是一家之主'];
const titlesEn=['The Wealthy Student Rents the Smallest Room','The Photos Looked Nothing Like This','She Brought Eight Suitcases','Why Not Rent the Whole Unit?','The Landlord’s Twenty Rules','Deposit or Pride?','Why Can’t the Air-Con Stay On?','Her First Time Doing Laundry','Who Left the Lights On?','Who Owns the Food in the Fridge?','Hotpot at Home','Can Durian Come Home?','A Wealthy Student Cleans the Toilet','Must She Tell the Landlord About Guests?','Who Owns the Living Room?','Tissue Paper Means Reserved','Her First Hawker-Centre Tray','Does Can Can Mean More Can?','Her First Bus Ride Goes Wrong','What You Cannot Do on the MRT','How Do You Throw Away Rubbish?','Fines Even Money Cannot Avoid','Singapore Rain Arrives Without Warning','She Wants to Move but Hates Losing the Deposit','Angeline Turns the Living Room into a Private Club','James Brings a Buyer Home','Joseph Turns a Viewing into an Advertisement','The Family Video Call','A New Tenant Comes to View','Who Is Really in Charge?'];
const categoriesZh=['入住篇','生活习惯篇','新加坡文化篇','关系升级篇'];
const categoriesEn=['Moving In','Living Habits','Singapore Culture','Relationship Growth'];
const stageFor=n=>n<=6?'outline':n<=11?'writing':n<=15?'locked':n<=19?'shoot':n<=22?'filmed':n<=25?'post':'publish';
const scriptFor=st=>st==='outline'?'idea':st==='writing'?'writing':['locked','shoot','filmed','post','publish'].includes(st)?'final':'discussion';
const ownerFor=n=>['Angeline','Joseph','James'][n%3];
const priorityFor=n=>n%5===0?'low':n%3===0?'high':'medium';
const dateFor=n=>`2026-${String(8+Math.floor((n-1)/12)).padStart(2,'0')}-${String(2+((n-1)%4)*7).padStart(2,'0')}`;
async function seed(env){const c=await env.DB.prepare('SELECT COUNT(*) AS c FROM episodes').first();if(Number(c?.c||0)>0)return;const stmt=env.DB.prepare(`INSERT INTO episodes(episode_no,title_zh,title_en,category_zh,category_en,summary_zh,summary_en,script_status,production_stage,owner,priority,shoot_date,progress,open_issues,version,culture_point_zh,culture_point_en) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);for(let i=1;i<=30;i++){const cat=i<=6?0:i<=15?1:i<=23?2:3;const st=stageFor(i);const issue=i%4===0?'待确认场景或道具':'';await stmt.bind(i,titlesZh[i-1],titlesEn[i-1],categoriesZh[cat],categoriesEn[cat],`${titlesZh[i-1]}的短剧大纲、人物冲突与制作资料。`,`${titlesEn[i-1]} — story outline, character conflict and production notes.`,scriptFor(st),st,ownerFor(i),priorityFor(i),dateFor(i),Math.min(95,20+i*2),issue,'v0.1','新加坡生活与文化差异','Singapore lifestyle and cultural differences').run();}}
const cols=`id,episode_no AS episodeNo,title_zh AS titleZh,title_en AS titleEn,category_zh AS categoryZh,category_en AS categoryEn,summary_zh AS summaryZh,summary_en AS summaryEn,script_status AS scriptStatus,production_stage AS productionStage,owner,priority,shoot_date AS shootDate,publish_date AS publishDate,progress,open_issues AS openIssues,version,script_zh AS scriptZh,script_en AS scriptEn,culture_point_zh AS culturePointZh,culture_point_en AS culturePointEn,views,retention_30 AS retention30,retention_60 AS retention60,avg_watch_seconds AS avgWatchSeconds,completion_rate AS completionRate,next_episode_rate AS nextEpisodeRate,followers_gained AS followersGained,top_comment AS topComment,updated_at AS updatedAt`;
export async function onRequestGet({env}){if(!env.DB)return json({error:'D1 binding DB is not configured.'},503);await seed(env);const {results}=await env.DB.prepare(`SELECT ${cols} FROM episodes ORDER BY episode_no`).all();return json({episodes:results||[]});}
const clean=b=>({episodeNo:+b.episodeNo||0,titleZh:String(b.titleZh||'').slice(0,180),titleEn:String(b.titleEn||'').slice(0,180),categoryZh:String(b.categoryZh||'').slice(0,100),categoryEn:String(b.categoryEn||'').slice(0,100),summaryZh:String(b.summaryZh||'').slice(0,4000),summaryEn:String(b.summaryEn||'').slice(0,4000),scriptStatus:['idea','discussion','writing','revision','final'].includes(b.scriptStatus)?b.scriptStatus:'idea',productionStage:['outline','writing','locked','shoot','filmed','post','publish'].includes(b.productionStage)?b.productionStage:'outline',owner:String(b.owner||'').slice(0,100),priority:['high','medium','low'].includes(b.priority)?b.priority:'medium',shootDate:String(b.shootDate||'').slice(0,20),publishDate:String(b.publishDate||'').slice(0,20),progress:Math.max(0,Math.min(100,+b.progress||0)),openIssues:String(b.openIssues||'').slice(0,2000),version:String(b.version||'v0.1').slice(0,40),scriptZh:String(b.scriptZh||'').slice(0,30000),scriptEn:String(b.scriptEn||'').slice(0,30000),culturePointZh:String(b.culturePointZh||'').slice(0,3000),culturePointEn:String(b.culturePointEn||'').slice(0,3000),views:Math.max(0,+b.views||0),retention30:+b.retention30||0,retention60:+b.retention60||0,avgWatchSeconds:+b.avgWatchSeconds||0,completionRate:+b.completionRate||0,nextEpisodeRate:+b.nextEpisodeRate||0,followersGained:Math.max(0,+b.followersGained||0),topComment:String(b.topComment||'').slice(0,3000)});
export async function onRequestPut({request,env}){if(!env.DB)return json({error:'D1 binding DB is not configured.'},503);let raw;try{raw=await request.json()}catch{return json({error:'Invalid JSON.'},400)}const id=Number(raw.id);if(!id)return json({error:'Valid id required.'},400);const b=clean(raw);await env.DB.prepare(`UPDATE episodes SET title_zh=?,title_en=?,category_zh=?,category_en=?,summary_zh=?,summary_en=?,script_status=?,production_stage=?,owner=?,priority=?,shoot_date=?,publish_date=?,progress=?,open_issues=?,version=?,script_zh=?,script_en=?,culture_point_zh=?,culture_point_en=?,views=?,retention_30=?,retention_60=?,avg_watch_seconds=?,completion_rate=?,next_episode_rate=?,followers_gained=?,top_comment=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.titleZh,b.titleEn,b.categoryZh,b.categoryEn,b.summaryZh,b.summaryEn,b.scriptStatus,b.productionStage,b.owner,b.priority,b.shootDate,b.publishDate,b.progress,b.openIssues,b.version,b.scriptZh,b.scriptEn,b.culturePointZh,b.culturePointEn,b.views,b.retention30,b.retention60,b.avgWatchSeconds,b.completionRate,b.nextEpisodeRate,b.followersGained,b.topComment,id).run();return json({episode:{id,...b,updatedAt:new Date().toISOString()}})}
