import { json, ensureColumn, logAudit, requireId } from '../_lib/db.js';

async function ensure(db){
  await db.prepare(`CREATE TABLE IF NOT EXISTS schedules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL DEFAULT '',call_time TEXT NOT NULL DEFAULT '',start_time TEXT NOT NULL DEFAULT '',end_time TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '',episodes TEXT NOT NULL DEFAULT '',"cast" TEXT NOT NULL DEFAULT '',crew TEXT NOT NULL DEFAULT '',owner TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'planning',issues TEXT NOT NULL DEFAULT '',timeline TEXT NOT NULL DEFAULT '',wardrobe_props TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',deleted_at TEXT
  )`).run();
  await ensureColumn(db,'schedules','deleted_at','TEXT');
  await ensureColumn(db,'schedules','event_type',"TEXT NOT NULL DEFAULT 'shoot'");
  await ensureColumn(db,'schedules','title',"TEXT NOT NULL DEFAULT ''");
  await ensureColumn(db,'schedules','assignee',"TEXT NOT NULL DEFAULT ''");
  await db.prepare('CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date)').run();
}
const clean=b=>({eventType:['shoot','editing'].includes(b.eventType)?b.eventType:'shoot',title:String(b.title||''),assignee:String(b.assignee||''),date:String(b.date||''),callTime:String(b.callTime||''),startTime:String(b.startTime||''),endTime:String(b.endTime||''),location:String(b.location||''),episodes:String(b.episodes||''),cast:String(b.cast||''),crew:String(b.crew||''),owner:String(b.owner||''),status:['planning','confirmed','shooting','completed','reshoot'].includes(b.status)?b.status:'planning',issues:String(b.issues||''),timeline:String(b.timeline||''),wardrobeProps:String(b.wardrobeProps||''),notes:String(b.notes||'')});
const cols=`id,event_type AS eventType,title,assignee,date,call_time AS callTime,start_time AS startTime,end_time AS endTime,location,episodes,"cast" AS "cast",crew,owner,status,issues,timeline,wardrobe_props AS wardrobeProps,notes`;
export async function onRequestGet({env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const {results}=await env.DB.prepare(`SELECT ${cols} FROM schedules WHERE deleted_at IS NULL ORDER BY date,id`).all();return json({schedules:results||[]})}
export async function onRequestPost({request,env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);let b;try{b=clean(await request.json())}catch{return json({error:'Invalid JSON'},400)}const r=await env.DB.prepare(`INSERT INTO schedules(event_type,title,assignee,date,call_time,start_time,end_time,location,episodes,"cast",crew,owner,status,issues,timeline,wardrobe_props,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(b.eventType,b.title,b.assignee,b.date,b.callTime,b.startTime,b.endTime,b.location,b.episodes,b.cast,b.crew,b.owner,b.status,b.issues,b.timeline,b.wardrobeProps,b.notes).run();const id=r.meta.last_row_id;await logAudit(env.DB,'schedule',id,'create',{date:b.date,eventType:b.eventType,title:b.title});return json({schedule:{id,...b}},201)}
export async function onRequestPut({request,env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);let raw;try{raw=await request.json()}catch{return json({error:'Invalid JSON'},400)}const id=Number(raw.id);if(!id)return json({error:'Valid id required'},400);const b=clean(raw);await env.DB.prepare(`UPDATE schedules SET event_type=?,title=?,assignee=?,date=?,call_time=?,start_time=?,end_time=?,location=?,episodes=?,"cast"=?,crew=?,owner=?,status=?,issues=?,timeline=?,wardrobe_props=?,notes=? WHERE id=? AND deleted_at IS NULL`).bind(b.eventType,b.title,b.assignee,b.date,b.callTime,b.startTime,b.endTime,b.location,b.episodes,b.cast,b.crew,b.owner,b.status,b.issues,b.timeline,b.wardrobeProps,b.notes,id).run();await logAudit(env.DB,'schedule',id,'update',{date:b.date,eventType:b.eventType,title:b.title});return json({schedule:{id,...b}})}
export async function onRequestDelete({request,env}){if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const id=requireId(request);if(!id)return json({error:'Valid id required'},400);await env.DB.prepare('UPDATE schedules SET deleted_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL').bind(id).run();await logAudit(env.DB,'schedule',id,'soft_delete');return json({ok:true,id})}
