import { json, ensureColumn, logAudit, requireId } from '../_lib/db.js';
const DEFAULTS=[
['隔壁邻居','Next-door Neighbour'],['James 的房产客户','James’s Property Client'],['买家与租客','Buyer or Tenant'],['合作房产中介','Partner Property Agent'],['Angeline 的同学','Angeline’s Classmate'],['学校老师','School Lecturer'],['中国留学生家长','Chinese Student Parent'],['Joseph 的广告客户','Joseph’s Advertising Client'],['内容创作者','Content Creator'],['平台客户经理','Platform Account Manager'],['新租客','New Tenant'],['快递员','Delivery Rider'],['清洁阿姨','Cleaner'],['ICA 工作人员','ICA Officer'],['小贩中心老板','Hawker Stall Owner']
];
async function ensure(db){await db.prepare(`CREATE TABLE IF NOT EXISTS supporting_characters (id INTEGER PRIMARY KEY AUTOINCREMENT,name_zh TEXT NOT NULL DEFAULT '',name_en TEXT NOT NULL DEFAULT '',character_type TEXT NOT NULL DEFAULT 'recurring',background_zh TEXT NOT NULL DEFAULT '',background_en TEXT NOT NULL DEFAULT '',relation_zh TEXT NOT NULL DEFAULT '',relation_en TEXT NOT NULL DEFAULT '',first_episode INTEGER NOT NULL DEFAULT 0,storyline_zh TEXT NOT NULL DEFAULT '',storyline_en TEXT NOT NULL DEFAULT '',actor_name TEXT NOT NULL DEFAULT '',actor_contact TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'planned',notes TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT)`).run();await ensureColumn(db,'supporting_characters','deleted_at','TEXT');await db.prepare('CREATE INDEX IF NOT EXISTS idx_supporting_order ON supporting_characters(sort_order ASC,id ASC)').run();}
async function seed(db){const c=await db.prepare('SELECT COUNT(*) AS c FROM supporting_characters WHERE deleted_at IS NULL').first();if(Number(c?.c||0)>0)return;const q=db.prepare(`INSERT INTO supporting_characters(name_zh,name_en,character_type,background_zh,background_en,status,sort_order) VALUES(?,?,?,?,?,?,?)`);for(let i=0;i<DEFAULTS.length;i++){const [zh,en]=DEFAULTS[i];await q.bind(zh,en,'recurring','记录人设、与主角关系、首次出现集数、可重复剧情和演员资料。','Record characterisation, relationship to the main cast, first appearance, repeatable storylines, and actor details.','planned',i+1).run();}}
const map=r=>({id:r.id,name_zh:r.name_zh,name_en:r.name_en,character_type:r.character_type,background_zh:r.background_zh,background_en:r.background_en,relation_zh:r.relation_zh,relation_en:r.relation_en,first_episode:r.first_episode,storyline_zh:r.storyline_zh,storyline_en:r.storyline_en,actor_name:r.actor_name,actor_contact:r.actor_contact,status:r.status,notes:r.notes,sort_order:r.sort_order,updated_at:r.updated_at});
export async function onRequestGet({env}){try{if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);await seed(env.DB);const {results}=await env.DB.prepare('SELECT * FROM supporting_characters WHERE deleted_at IS NULL ORDER BY sort_order ASC,id ASC').all();return json({characters:(results||[]).map(map)});}catch(e){return json({error:e.message},500)}}
export async function onRequestPost({request,env}){try{if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const b=await request.json();if(!String(b.name_zh||b.name_en||'').trim())return json({error:'name required'},400);const r=await env.DB.prepare(`INSERT INTO supporting_characters(name_zh,name_en,character_type,background_zh,background_en,relation_zh,relation_en,first_episode,storyline_zh,storyline_en,actor_name,actor_contact,status,notes,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING *`).bind(b.name_zh||'',b.name_en||'',b.character_type||'recurring',b.background_zh||'',b.background_en||'',b.relation_zh||'',b.relation_en||'',Number(b.first_episode||0),b.storyline_zh||'',b.storyline_en||'',b.actor_name||'',b.actor_contact||'',b.status||'planned',b.notes||'',Number(b.sort_order||999)).first();await logAudit(env.DB,'supporting_character',r.id,'create',{name:r.name_zh||r.name_en});return json({character:map(r)},201);}catch(e){return json({error:e.message},500)}}
export async function onRequestPut({request,env}){try{if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const b=await request.json(),id=Number(b.id);if(!id)return json({error:'id required'},400);const r=await env.DB.prepare(`UPDATE supporting_characters SET name_zh=?,name_en=?,character_type=?,background_zh=?,background_en=?,relation_zh=?,relation_en=?,first_episode=?,storyline_zh=?,storyline_en=?,actor_name=?,actor_contact=?,status=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL RETURNING *`).bind(b.name_zh||'',b.name_en||'',b.character_type||'recurring',b.background_zh||'',b.background_en||'',b.relation_zh||'',b.relation_en||'',Number(b.first_episode||0),b.storyline_zh||'',b.storyline_en||'',b.actor_name||'',b.actor_contact||'',b.status||'planned',b.notes||'',id).first();if(!r)return json({error:'not found'},404);await logAudit(env.DB,'supporting_character',id,'update',{name:r.name_zh||r.name_en});return json({character:map(r)});}catch(e){return json({error:e.message},500)}}
export async function onRequestDelete({request,env}){try{if(!env.DB)return json({error:'DB unavailable'},503);await ensure(env.DB);const id=requireId(request);if(!id)return json({error:'id required'},400);await env.DB.prepare('UPDATE supporting_characters SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL').bind(id).run();await logAudit(env.DB,'supporting_character',id,'soft_delete');return json({ok:true,id});}catch(e){return json({error:e.message},500)}}
